/* TA-LIB Copyright (c) 1999-2026, Mario Fortier
* All rights reserved.
*
* Redistribution and use in source and binary forms, with or
* without modification, are permitted provided that the following
* conditions are met:
*
* - Redistributions of source code must retain the above copyright
*   notice, this list of conditions and the following disclaimer.
*
* - Redistributions in binary form must reproduce the above copyright
*   notice, this list of conditions and the following disclaimer in
*   the documentation and/or other materials provided with the
*   distribution.
*
* - Neither name of author nor the names of its contributors
*   may be used to endorse or promote products derived from this
*   software without specific prior written permission.
*
* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
* ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
* LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
* FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
* REGENTS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
* INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
* (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
* OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
* INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
* WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
* OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
* EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

/* AUTO-GENERATED by ta_codegen — DO NOT EDIT.
* Source of truth: ta_codegen/input/<name>/  (regenerate: cd ta_codegen/generator && cargo run -- generate)
*/

#include <string.h>
#include <math.h>
#include "ta_func.h"
#include "ta_utility.h"
#include "ta_memory.h"
#include "ta_func_stream_private.h"

/* List of contributors:
 *
 *  Initial  Name/description
 *  -------------------------------------------------------------------
 *  KL       Kevin Lin
 *
 * Change history:
 *
 *  MMDDYY BY     Description
 *  -------------------------------------------------------------------
 *  090526 KL     First version (issue #371).
 */

TA_LIB_API int TA_FRACTAL_Lookback( int optInLeftBars, int optInRightBars )
{
   if( (int)optInLeftBars == TA_INTEGER_DEFAULT )
      optInLeftBars = 2;
   else if( (int)optInLeftBars < 1 || (int)optInLeftBars > 100000 )
      return -1;
   if( (int)optInRightBars == TA_INTEGER_DEFAULT )
      optInRightBars = 2;
   else if( (int)optInRightBars < 1 || (int)optInRightBars > 100000 )
      return -1;
   return optInLeftBars + optInRightBars;
}

TA_LIB_API TA_RetCode TA_FRACTAL( int    startIdx,
                                  int    endIdx,
                                  const double inHigh[],
                                  const double inLow[],
                                  int optInLeftBars,
                                  int optInRightBars,
                                  int          *outBegIdx,
                                  int          *outNBElement,
                                  int        outSwingHigh[],
                                  int        outSwingLow[] )
{
   double candHigh;
   double candLow;
   int outIdx;
   int lookbackTotal;
   int today;
   int candIdx;
   int trailingIdx;
   int i;
   int swingHigh;
   int swingLow;

   if( (startIdx < 0) || (startIdx > TA_MAX_INDEX) )
      return TA_OUT_OF_RANGE_START_INDEX;
   if( (endIdx < 0) || (endIdx > TA_MAX_INDEX) || (endIdx < startIdx) )
      return TA_OUT_OF_RANGE_END_INDEX;

   if( (int)optInLeftBars == TA_INTEGER_DEFAULT )
      optInLeftBars = 2;
   else if( (int)optInLeftBars < 1 || (int)optInLeftBars > 100000 )
      return TA_BAD_PARAM;
   if( (int)optInRightBars == TA_INTEGER_DEFAULT )
      optInRightBars = 2;
   else if( (int)optInRightBars < 1 || (int)optInRightBars > 100000 )
      return TA_BAD_PARAM;
   if( !inHigh )
      return TA_BAD_PARAM;
   if( !inLow )
      return TA_BAD_PARAM;
   if( !outBegIdx || !outNBElement )
      return TA_BAD_PARAM;
   if( !outSwingHigh )
      return TA_BAD_PARAM;
   if( !outSwingLow )
      return TA_BAD_PARAM;
   if( outSwingHigh == outSwingLow )
      return TA_BAD_PARAM;

   /* A bar is a swing high when its high is STRICTLY above the high of
    * every one of the optInLeftBars bars before it and of the
    * optInRightBars bars after it; the swing low is the mirror on inLow.
    * The verdict on a candidate bar can only be reached once its right
    * arm exists, so it is reported at the confirmation bar
    * candidate+optInRightBars -- that offset is what makes the function
    * causal, and it is where both oracle libraries report it too.
    *
    * A window that ties on either arm is not a pivot. Both arms use the
    * same strict comparison; the asymmetric >-left / >=-right variant some
    * charting docs describe would flag the later bar of a flat top.
    */
   lookbackTotal = optInLeftBars + optInRightBars;
   /* Move up the start index if there is not
    * enough initial data.
    */
   if( startIdx < lookbackTotal )
   {
      startIdx = lookbackTotal;
   }
   /* Make sure there is still something to evaluate. */
   if( startIdx > endIdx )
   {
      *outBegIdx= 0;
      *outNBElement= 0;
      return TA_SUCCESS;
   }
   /* The window is rescanned per bar (as MIN/MAX do when their cached
    * extremum leaves): a cached running extremum cannot answer this
    * question, because the candidate sits in the MIDDLE of the window and
    * a tie has to be distinguished from a strict win.
    *
    * The integer outputs can never share a real input's buffer -- different
    * element type; issue #130.
    */
   outIdx = 0;
   today = startIdx;
   trailingIdx = startIdx - lookbackTotal;
   while( today <= endIdx )
   {
      candIdx = trailingIdx + optInLeftBars;
      candHigh = inHigh[candIdx];
      candLow = inLow[candIdx];
      swingHigh = 100;
      swingLow = 100;
      i = trailingIdx;
      TA_UNROLL(4)
      while( i < candIdx )
      {
         if( inHigh[i] >= candHigh )
         {
            swingHigh = 0;
         }
         if( inLow[i] <= candLow )
         {
            swingLow = 0;
         }
         i += 1;
      }
      i = candIdx + 1;
      TA_UNROLL(4)
      while( i <= today )
      {
         if( inHigh[i] >= candHigh )
         {
            swingHigh = 0;
         }
         if( inLow[i] <= candLow )
         {
            swingLow = 0;
         }
         i += 1;
      }
      outSwingHigh[outIdx] = swingHigh;
      outSwingLow[outIdx] = swingLow;
      outIdx += 1;
      trailingIdx += 1;
      today += 1;
   }
   /* Keep the outBegIdx relative to the
    * caller input before returning.
    */
   *outBegIdx= startIdx;
   *outNBElement= outIdx;
   return TA_SUCCESS;
}

TA_RetCode TA_S_FRACTAL( int    startIdx,
                         int    endIdx,
                         const float inHigh[],
                         const float inLow[],
                         int optInLeftBars,
                         int optInRightBars,
                         int          *outBegIdx,
                         int          *outNBElement,
                         int        outSwingHigh[],
                         int        outSwingLow[] )
{
   double candHigh;
   double candLow;
   int outIdx;
   int lookbackTotal;
   int today;
   int candIdx;
   int trailingIdx;
   int i;
   int swingHigh;
   int swingLow;

   if( (startIdx < 0) || (startIdx > TA_MAX_INDEX) )
      return TA_OUT_OF_RANGE_START_INDEX;
   if( (endIdx < 0) || (endIdx > TA_MAX_INDEX) || (endIdx < startIdx) )
      return TA_OUT_OF_RANGE_END_INDEX;

   if( (int)optInLeftBars == TA_INTEGER_DEFAULT )
      optInLeftBars = 2;
   else if( (int)optInLeftBars < 1 || (int)optInLeftBars > 100000 )
      return TA_BAD_PARAM;
   if( (int)optInRightBars == TA_INTEGER_DEFAULT )
      optInRightBars = 2;
   else if( (int)optInRightBars < 1 || (int)optInRightBars > 100000 )
      return TA_BAD_PARAM;
   if( !inHigh )
      return TA_BAD_PARAM;
   if( !inLow )
      return TA_BAD_PARAM;
   if( !outBegIdx || !outNBElement )
      return TA_BAD_PARAM;
   if( !outSwingHigh )
      return TA_BAD_PARAM;
   if( !outSwingLow )
      return TA_BAD_PARAM;
   if( outSwingHigh == outSwingLow )
      return TA_BAD_PARAM;

   lookbackTotal = optInLeftBars + optInRightBars;
   if( startIdx < lookbackTotal )
   {
      startIdx = lookbackTotal;
   }
   if( startIdx > endIdx )
   {
      *outBegIdx= 0;
      *outNBElement= 0;
      return TA_SUCCESS;
   }
   outIdx = 0;
   today = startIdx;
   trailingIdx = startIdx - lookbackTotal;
   while( today <= endIdx )
   {
      candIdx = trailingIdx + optInLeftBars;
      candHigh = (double)inHigh[candIdx];
      candLow = (double)inLow[candIdx];
      swingHigh = 100;
      swingLow = 100;
      i = trailingIdx;
      TA_UNROLL(4)
      while( i < candIdx )
      {
         if( (double)inHigh[i] >= candHigh )
         {
            swingHigh = 0;
         }
         if( (double)inLow[i] <= candLow )
         {
            swingLow = 0;
         }
         i += 1;
      }
      i = candIdx + 1;
      TA_UNROLL(4)
      while( i <= today )
      {
         if( (double)inHigh[i] >= candHigh )
         {
            swingHigh = 0;
         }
         if( (double)inLow[i] <= candLow )
         {
            swingLow = 0;
         }
         i += 1;
      }
      outSwingHigh[outIdx] = swingHigh;
      outSwingLow[outIdx] = swingLow;
      outIdx += 1;
      trailingIdx += 1;
      today += 1;
   }
   *outBegIdx= startIdx;
   *outNBElement= outIdx;
   return TA_SUCCESS;
}

/**** Streaming API *****/

struct TA_FRACTAL_Stream {
   /* The bars this handle has an output for (see TA_StreamOutRange).
    * Kept first, and in this order, in every stream struct. */
   int outRangeBegIdx;
   int outRangeCount;
   /* The value(s) at the last bar the stream counted (see TA_FRACTAL_Value). */
   int cur_outSwingHigh;
   int cur_outSwingLow;
   int optInLeftBars;
   int optInRightBars;
   int trailingIdx;
   int candIdx;
   int i;
   int today;
   int xCap;
   int xPhys;
   int xMask;
   double *x_inHigh;
   double *x_inLow;
};

/* Private function, not in public API. */
static void TA_FRACTAL_ReleaseImpl( struct TA_FRACTAL_Stream *sp )
{
   if( !sp ) return;
   if( sp->x_inHigh ) TA_Free( sp->x_inHigh );
   if( sp->x_inLow ) TA_Free( sp->x_inLow );
   TA_Free( sp );
}

/* Private function, not in public API. */
static void TA_FRACTAL_StepImpl( struct TA_FRACTAL_Stream *sp, double inHigh, double inLow, int *outSwingHigh, int *outSwingLow )
{
   double candHigh;
   double candLow;
   int swingHigh;
   int swingLow;

   if( sp->today >= 1073741824 )
   {
      int rebaseShift = sp->trailingIdx & ~sp->xMask;
      sp->today -= rebaseShift;
      sp->trailingIdx -= rebaseShift;
      sp->candIdx -= rebaseShift;
      sp->i -= rebaseShift;
   }
   sp->x_inHigh[sp->today & sp->xMask] = inHigh;
   sp->x_inLow[sp->today & sp->xMask] = inLow;
   sp->candIdx = sp->trailingIdx + sp->optInLeftBars;
   candHigh = sp->x_inHigh[sp->candIdx & sp->xMask];
   candLow = sp->x_inLow[sp->candIdx & sp->xMask];
   swingHigh = 100;
   swingLow = 100;
   sp->i = sp->trailingIdx;
   TA_UNROLL(4)
   while( sp->i < sp->candIdx )
   {
      if( sp->x_inHigh[sp->i & sp->xMask] >= candHigh )
      {
         swingHigh = 0;
      }
      if( sp->x_inLow[sp->i & sp->xMask] <= candLow )
      {
         swingLow = 0;
      }
      sp->i += 1;
   }
   sp->i = sp->candIdx + 1;
   TA_UNROLL(4)
   while( sp->i <= sp->today )
   {
      if( sp->x_inHigh[sp->i & sp->xMask] >= candHigh )
      {
         swingHigh = 0;
      }
      if( sp->x_inLow[sp->i & sp->xMask] <= candLow )
      {
         swingLow = 0;
      }
      sp->i += 1;
   }
   *outSwingHigh= swingHigh;
   *outSwingLow= swingLow;
   sp->trailingIdx += 1;
   sp->today += 1;
   sp->cur_outSwingHigh = *outSwingHigh;
   sp->cur_outSwingLow = *outSwingLow;
}

static TA_RetCode TA_FRACTAL_OpenImpl( struct TA_FRACTAL_Stream **stream, const double inHigh[], const double inLow[], int startIdx, int historyLen, int optInLeftBars, int optInRightBars, int *outBegIdx, int *outNBElement, int outSwingHigh[], int outSwingLow[], int outStride )
{
   struct TA_FRACTAL_Stream *sp;
   int endIdx;

   if( !stream ) return TA_BAD_PARAM;
   *stream = NULL;
   if( historyLen < 1 ) return TA_OUT_OF_RANGE_START_INDEX;
   if( historyLen > TA_MAX_INDEX + 1 ) return TA_OUT_OF_RANGE_END_INDEX;
   if( !inHigh || !inLow || !outSwingHigh || !outSwingLow ) return TA_BAD_PARAM;
   if( (int)optInLeftBars == TA_INTEGER_DEFAULT )
      optInLeftBars = 2;
   else if( (int)optInLeftBars < 1 || (int)optInLeftBars > 100000 )
      return TA_BAD_PARAM;
   if( (int)optInRightBars == TA_INTEGER_DEFAULT )
      optInRightBars = 2;
   else if( (int)optInRightBars < 1 || (int)optInRightBars > 100000 )
      return TA_BAD_PARAM;
   if( startIdx > historyLen - 1 )
   {
      *outBegIdx = 0;
      *outNBElement = 0;
      return TA_INSUFFICIENT_HISTORY;
   }

   endIdx = historyLen - 1;

   {
      double candHigh;
      double candLow;
      int outIdx;
      int lookbackTotal;
      int today = 0;
      int candIdx = 0;
      int trailingIdx = 0;
      int i = 0;
      int swingHigh;
      int swingLow;
      /* A bar is a swing high when its high is STRICTLY above the high of
       * every one of the optInLeftBars bars before it and of the
       * optInRightBars bars after it; the swing low is the mirror on inLow.
       * The verdict on a candidate bar can only be reached once its right
       * arm exists, so it is reported at the confirmation bar
       * candidate+optInRightBars -- that offset is what makes the function
       * causal, and it is where both oracle libraries report it too.
       *
       * A window that ties on either arm is not a pivot. Both arms use the
       * same strict comparison; the asymmetric >-left / >=-right variant some
       * charting docs describe would flag the later bar of a flat top.
       */
      lookbackTotal = optInLeftBars + optInRightBars;
      /* Move up the start index if there is not
       * enough initial data.
       */
      if( startIdx < lookbackTotal )
      {
         startIdx = lookbackTotal;
      }
      /* Make sure there is still something to evaluate. */
      if( startIdx > endIdx )
      {
         *outBegIdx= 0;
         *outNBElement= 0;
         return TA_INSUFFICIENT_HISTORY;
      }
      /* The window is rescanned per bar (as MIN/MAX do when their cached
       * extremum leaves): a cached running extremum cannot answer this
       * question, because the candidate sits in the MIDDLE of the window and
       * a tie has to be distinguished from a strict win.
       *
       * The integer outputs can never share a real input's buffer -- different
       * element type; issue #130.
       */
      outIdx = 0;
      today = startIdx;
      trailingIdx = startIdx - lookbackTotal;
      while( today <= endIdx )
      {
         candIdx = trailingIdx + optInLeftBars;
         candHigh = inHigh[candIdx];
         candLow = inLow[candIdx];
         swingHigh = 100;
         swingLow = 100;
         i = trailingIdx;
         TA_UNROLL(4)
         while( i < candIdx )
         {
            if( inHigh[i] >= candHigh )
            {
               swingHigh = 0;
            }
            if( inLow[i] <= candLow )
            {
               swingLow = 0;
            }
            i += 1;
         }
         i = candIdx + 1;
         TA_UNROLL(4)
         while( i <= today )
         {
            if( inHigh[i] >= candHigh )
            {
               swingHigh = 0;
            }
            if( inLow[i] <= candLow )
            {
               swingLow = 0;
            }
            i += 1;
         }
         outSwingHigh[outIdx * outStride] = swingHigh;
         outSwingLow[outIdx * outStride] = swingLow;
         outIdx += 1;
         trailingIdx += 1;
         today += 1;
      }
      /* Keep the outBegIdx relative to the
       * caller input before returning.
       */
      *outBegIdx= startIdx;
      *outNBElement= outIdx;

      /* Capture the live batch state into the handle. */
      sp = (struct TA_FRACTAL_Stream *)TA_Malloc( sizeof(*sp) );
      if( !sp ) { return TA_ALLOC_ERR; }
      memset( sp, 0, sizeof(*sp) );
      sp->optInLeftBars = optInLeftBars;
      sp->optInRightBars = optInRightBars;
      sp->trailingIdx = trailingIdx;
      sp->candIdx = candIdx;
      sp->i = i;
      sp->today = today;
      sp->xCap = (int)(today - trailingIdx) + 1;
      if( sp->xCap < 1 || sp->xCap > historyLen ) { TA_FRACTAL_ReleaseImpl( sp ); return TA_INTERNAL_ERROR(420); }
      sp->xPhys = 1;
      while( sp->xPhys < sp->xCap ) sp->xPhys <<= 1;
      sp->xMask = sp->xPhys - 1;
      sp->x_inHigh = (double *)TA_Malloc( sizeof(double) * (size_t)sp->xPhys );
      if( !sp->x_inHigh ) { TA_FRACTAL_ReleaseImpl( sp ); return TA_ALLOC_ERR; }
      sp->x_inLow = (double *)TA_Malloc( sizeof(double) * (size_t)sp->xPhys );
      if( !sp->x_inLow ) { TA_FRACTAL_ReleaseImpl( sp ); return TA_ALLOC_ERR; }
      { int fillJ;
        for( fillJ = historyLen - sp->xCap; fillJ < historyLen; fillJ++ )
        {
           sp->x_inHigh[fillJ & sp->xMask] = inHigh[fillJ];
           sp->x_inLow[fillJ & sp->xMask] = inLow[fillJ];
        }
      }
      sp->outRangeBegIdx = *outBegIdx;
      sp->outRangeCount = *outNBElement;
      sp->cur_outSwingHigh = outSwingHigh[(*outNBElement - 1) * outStride];
      sp->cur_outSwingLow = outSwingLow[(*outNBElement - 1) * outStride];
      *stream = sp;
      return TA_SUCCESS;
   }
}

/* Private function, not in public API. */
TA_RetCode TA_FRACTAL_OpenInternal( struct TA_FRACTAL_Stream **stream, const double inHigh[], const double inLow[], int startIdx, int historyLen, int optInLeftBars, int optInRightBars, int *outSwingHigh, int *outSwingLow )
{
   TA_RetCode retCode;
   int dummyBegIdx = 0;
   int dummyNBElement = 0;
   int sink_outSwingHigh = 0;
   int sink_outSwingLow = 0;
   retCode = TA_FRACTAL_OpenImpl( stream, inHigh, inLow, startIdx, historyLen, optInLeftBars, optInRightBars, &dummyBegIdx, &dummyNBElement, &sink_outSwingHigh, &sink_outSwingLow, 0 );
   if( retCode == TA_SUCCESS )
   {
      *outSwingHigh = sink_outSwingHigh;
      *outSwingLow = sink_outSwingLow;
   }
   return retCode;
}

TA_LIB_API TA_RetCode TA_FRACTAL_Open( TA_FRACTAL_Stream **stream, const double inHigh[], const double inLow[], int historyLen, int optInLeftBars, int optInRightBars, int *outSwingHigh, int *outSwingLow )
{
   if( !stream ) return TA_BAD_PARAM;
   *stream = NULL;
   if( historyLen < 1 ) return TA_OUT_OF_RANGE_START_INDEX;
   if( historyLen > TA_MAX_INDEX + 1 ) return TA_OUT_OF_RANGE_END_INDEX;
   if( !inHigh || !inLow || !outSwingHigh || !outSwingLow ) return TA_BAD_PARAM;
   return TA_FRACTAL_OpenInternal( stream, inHigh, inLow, 0, historyLen, optInLeftBars, optInRightBars, outSwingHigh, outSwingLow );
}

TA_LIB_API TA_RetCode TA_FRACTAL_OpenAndFill( TA_FRACTAL_Stream **stream, const double inHigh[], const double inLow[], int historyLen, int optInLeftBars, int optInRightBars, int *outBegIdx, int *outNBElement, int outSwingHigh[], int outSwingLow[] )
{
   if( !stream ) return TA_BAD_PARAM;
   *stream = NULL;
   if( historyLen < 1 ) return TA_OUT_OF_RANGE_START_INDEX;
   if( historyLen > TA_MAX_INDEX + 1 ) return TA_OUT_OF_RANGE_END_INDEX;
   if( !inHigh || !inLow || !outBegIdx || !outNBElement || !outSwingHigh || !outSwingLow ) return TA_BAD_PARAM;
   if( (const void *)outSwingHigh == (const void *)inHigh || (const void *)outSwingHigh == (const void *)inLow || (const void *)outSwingLow == (const void *)inHigh || (const void *)outSwingLow == (const void *)inLow || (const void *)outSwingHigh == (const void *)outSwingLow ) return TA_BAD_PARAM;
   return TA_FRACTAL_OpenAndFillInternal( stream, inHigh, inLow, 0, historyLen, optInLeftBars, optInRightBars, outBegIdx, outNBElement, outSwingHigh, outSwingLow );
}

/* Private function, not in public API. */
TA_RetCode TA_FRACTAL_OpenAndFillInternal( struct TA_FRACTAL_Stream **stream, const double inHigh[], const double inLow[], int startIdx, int historyLen, int optInLeftBars, int optInRightBars, int *outBegIdx, int *outNBElement, int outSwingHigh[], int outSwingLow[] )
{
   return TA_FRACTAL_OpenImpl( stream, inHigh, inLow, startIdx, historyLen, optInLeftBars, optInRightBars, outBegIdx, outNBElement, outSwingHigh, outSwingLow, 1 );
}

TA_LIB_API TA_RetCode TA_FRACTAL_Update( TA_FRACTAL_Stream *stream, double inHigh, double inLow, int *outSwingHigh, int *outSwingLow )
{
   if( !stream || !outSwingHigh || !outSwingLow ) return TA_BAD_PARAM;
   if( !TA_IS_FINITE( inHigh ) || !TA_IS_FINITE( inLow ) )
   {
      if( stream->outRangeCount < TA_MAX_INDEX ) stream->outRangeCount++;
      return TA_BAD_PARAM;
   }
   TA_FRACTAL_StepImpl( stream, inHigh, inLow, outSwingHigh, outSwingLow );
   if( stream->outRangeCount < TA_MAX_INDEX ) stream->outRangeCount++;
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_FRACTAL_Peek( const TA_FRACTAL_Stream *stream, double inHigh, double inLow, int *outSwingHigh, int *outSwingLow )
{
   const struct TA_FRACTAL_Stream *sp = stream;
   double candHigh;
   double candLow;
   int swingHigh;
   int swingLow;
   int candIdx;
   int i;
   int today;
   int trailingIdx;
   double *x_inHigh;
   double *x_inLow;
   int pkSlot0 = -1;
   double pkVal0 = 0.0;
   int pkSlot1 = -1;
   double pkVal1 = 0.0;

   if( !stream || !outSwingHigh || !outSwingLow ) return TA_BAD_PARAM;
   if( !TA_IS_FINITE( inHigh ) || !TA_IS_FINITE( inLow ) ) return TA_BAD_PARAM;
   candIdx = sp->candIdx;
   i = sp->i;
   today = sp->today;
   trailingIdx = sp->trailingIdx;
   x_inHigh = sp->x_inHigh;
   x_inLow = sp->x_inLow;
   if( today >= 1073741824 )
   {
      int rebaseShift = trailingIdx & ~sp->xMask;
      today -= rebaseShift;
      trailingIdx -= rebaseShift;
      candIdx -= rebaseShift;
      i -= rebaseShift;
   }
   pkSlot0 = today & sp->xMask;
   pkVal0 = inHigh;
   pkSlot1 = today & sp->xMask;
   pkVal1 = inLow;
   candIdx = trailingIdx + sp->optInLeftBars;
   candHigh = ((candIdx & sp->xMask) != pkSlot0) ? x_inHigh[candIdx & sp->xMask] : pkVal0;
   candLow = ((candIdx & sp->xMask) != pkSlot1) ? x_inLow[candIdx & sp->xMask] : pkVal1;
   swingHigh = 100;
   swingLow = 100;
   i = trailingIdx;
   TA_UNROLL(4)
   while( i < candIdx )
   {
      if( (((i & sp->xMask) != pkSlot0) ? x_inHigh[i & sp->xMask] : pkVal0) >= candHigh )
      {
         swingHigh = 0;
      }
      if( (((i & sp->xMask) != pkSlot1) ? x_inLow[i & sp->xMask] : pkVal1) <= candLow )
      {
         swingLow = 0;
      }
      i += 1;
   }
   i = candIdx + 1;
   TA_UNROLL(4)
   while( i <= today )
   {
      if( (((i & sp->xMask) != pkSlot0) ? x_inHigh[i & sp->xMask] : pkVal0) >= candHigh )
      {
         swingHigh = 0;
      }
      if( (((i & sp->xMask) != pkSlot1) ? x_inLow[i & sp->xMask] : pkVal1) <= candLow )
      {
         swingLow = 0;
      }
      i += 1;
   }
   *outSwingHigh= swingHigh;
   *outSwingLow= swingLow;
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_FRACTAL_UpdateAndFill( TA_FRACTAL_Stream *stream, const double inHigh[], const double inLow[], int barCount, int outSwingHigh[], int outSwingLow[] )
{
   int i;

   if( !stream || !inHigh || !inLow || !outSwingHigh || !outSwingLow ) return TA_BAD_PARAM;
   if( barCount < 0 ) return TA_BAD_PARAM;
   if( (const void *)outSwingHigh == (const void *)inHigh || (const void *)outSwingHigh == (const void *)inLow || (const void *)outSwingLow == (const void *)inHigh || (const void *)outSwingLow == (const void *)inLow || (const void *)outSwingHigh == (const void *)outSwingLow ) return TA_BAD_PARAM;
   for( i = 0; i < barCount; i++ )
   {
      if( !TA_IS_FINITE( inHigh[i] ) || !TA_IS_FINITE( inLow[i] ) )
      {
         if( stream->outRangeCount < TA_MAX_INDEX ) stream->outRangeCount++;
         return TA_BAD_PARAM;
      }
      TA_FRACTAL_StepImpl( stream, inHigh[i], inLow[i], &outSwingHigh[i], &outSwingLow[i] );
      if( stream->outRangeCount < TA_MAX_INDEX ) stream->outRangeCount++;
   }
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_FRACTAL_Close( TA_FRACTAL_Stream *stream )
{
   TA_FRACTAL_ReleaseImpl( stream );
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_FRACTAL_Value( const TA_FRACTAL_Stream *stream, int *outSwingHigh, int *outSwingLow )
{
   if( !stream || !outSwingHigh || !outSwingLow ) return TA_BAD_PARAM;
   *outSwingHigh = stream->cur_outSwingHigh;
   *outSwingLow = stream->cur_outSwingLow;
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_FRACTAL_Clone( const TA_FRACTAL_Stream *stream, TA_FRACTAL_Stream **clone )
{
   struct TA_FRACTAL_Stream *sp;

   if( !clone ) return TA_BAD_PARAM;
   *clone = NULL;
   if( !stream ) return TA_BAD_PARAM;
   sp = (struct TA_FRACTAL_Stream *)TA_Malloc( sizeof(*sp) );
   if( !sp ) return TA_ALLOC_ERR;
   *sp = *stream;
   sp->x_inHigh = NULL;
   sp->x_inLow = NULL;
   if( stream->x_inHigh )
   { size_t copyN = (size_t)(sp->xPhys);
     sp->x_inHigh = (double *)TA_Malloc( sizeof(double) * copyN );
     if( !sp->x_inHigh ) { TA_FRACTAL_Close( sp ); return TA_ALLOC_ERR; }
     memcpy( sp->x_inHigh, stream->x_inHigh, sizeof(double) * copyN ); }
   if( stream->x_inLow )
   { size_t copyN = (size_t)(sp->xPhys);
     sp->x_inLow = (double *)TA_Malloc( sizeof(double) * copyN );
     if( !sp->x_inLow ) { TA_FRACTAL_Close( sp ); return TA_ALLOC_ERR; }
     memcpy( sp->x_inLow, stream->x_inLow, sizeof(double) * copyN ); }
   *clone = sp;
   return TA_SUCCESS;
}

