/* TA-LIB Copyright (c) 1999-2026, Mario Fortier
* All rights reserved.
*
* Redistribution and use in source and binary forms, with or
* without modification, are permitted provided that the following
* conditions are met:
*
* - Redistributions of source code must retain the above copyright
*   notice, this list of conditions and the following disclaimer.
*
* - Redistributions in binary form must reproduce the above copyright
*   notice, this list of conditions and the following disclaimer in
*   the documentation and/or other materials provided with the
*   distribution.
*
* - Neither name of author nor the names of its contributors
*   may be used to endorse or promote products derived from this
*   software without specific prior written permission.
*
* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
* ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
* LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
* FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
* REGENTS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
* INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
* (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
* OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
* INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
* WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
* OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
* EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

/* AUTO-GENERATED by ta_codegen — DO NOT EDIT.
* Source of truth: ta_codegen/input/<name>/  (regenerate: cd ta_codegen/generator && cargo run -- generate)
*/

#include <string.h>
#include <math.h>
#include "ta_func.h"
#include "ta_utility.h"
#include "ta_memory.h"
#include "ta_func_stream_private.h"

/* List of contributors:
 *
 *  Initial  Name/description
 *  -------------------------------------------------------------------
 *  KL       Kevin Lin
 *
 * Change history:
 *
 *  MMDDYY BY     Description
 *  -------------------------------------------------------------------
 *  090526 KL     First version (issue #373).
 */

TA_LIB_API int TA_HA_Lookback( void )
{
   /* The unstable period is the ONLY lookback: bar 0 is computable on its
    * own, so with the knob at its default 0 every input bar produces an
    * output bar.
    */
   return TA_GLOBALS_UNSTABLE_PERIOD(TA_FUNC_UNST_HA,Ha);
}

TA_LIB_API TA_RetCode TA_HA( int    startIdx,
                             int    endIdx,
                             const double inOpen[],
                             const double inHigh[],
                             const double inLow[],
                             const double inClose[],
                             int          *outBegIdx,
                             int          *outNBElement,
                             double        outHAOpen[],
                             double        outHAHigh[],
                             double        outHALow[],
                             double        outHAClose[] )
{
   int today;
   int outIdx;
   int lookbackTotal;
   double haOpen;
   double haClose;
   double haHigh;
   double haLow;
   double prevHAOpen;
   double prevHAClose;
   double tempOpen;
   double tempHigh;
   double tempLow;
   double tempClose;

   if( (startIdx < 0) || (startIdx > TA_MAX_INDEX) )
      return TA_OUT_OF_RANGE_START_INDEX;
   if( (endIdx < 0) || (endIdx > TA_MAX_INDEX) || (endIdx < startIdx) )
      return TA_OUT_OF_RANGE_END_INDEX;

   if( !inOpen )
      return TA_BAD_PARAM;
   if( !inHigh )
      return TA_BAD_PARAM;
   if( !inLow )
      return TA_BAD_PARAM;
   if( !inClose )
      return TA_BAD_PARAM;
   if( !outBegIdx || !outNBElement )
      return TA_BAD_PARAM;
   if( !outHAOpen )
      return TA_BAD_PARAM;
   if( !outHAHigh )
      return TA_BAD_PARAM;
   if( !outHALow )
      return TA_BAD_PARAM;
   if( !outHAClose )
      return TA_BAD_PARAM;
   if( outHAOpen == outHAHigh || outHAOpen == outHALow || outHAOpen == outHAClose || outHAHigh == outHALow || outHAHigh == outHAClose || outHALow == outHAClose )
      return TA_BAD_PARAM;

   /* Heikin-Ashi ("average bar"): an OHLC-to-OHLC smoothing transform.
    *
    *   HA_close[i] = (open[i] + high[i] + low[i] + close[i]) / 4
    *   HA_open [0] = (open[0] + close[0]) / 2
    *   HA_open [i] = (HA_open[i-1] + HA_close[i-1]) / 2
    *   HA_high [i] = max(high[i], HA_open[i], HA_close[i])
    *   HA_low  [i] = min(low [i], HA_open[i], HA_close[i])
    *
    * Keep the four-term sum in THIS left-to-right order. It is the oracles'
    * association, and floating-point addition is not associative:
    * TA_AVGPRICE sums the same four terms as (H+L+C+O)/4 and differs from
    * HA_close in the last place on ordinary bars, so HA_close is not a
    * composed AVGPRICE call and the two must not be unified.
    *
    * Every operation is one addition or one division by an exact power of
    * two, so the transform is exact whenever its inputs are -- which is why
    * the external captures are frozen at tolerance 0 rather than a band.
    *
    * BOTH stability flags are declared, and they answer different questions.
    * `unstable_period` is the ABI knob: the open's recursion carries a factor
    * of 1/2 per bar, so a seed's influence halves every step and dies out
    * entirely within a few dozen bars -- a caller who spends them gets a
    * start-independent series (56 bars suffice on the regtest history, and
    * test_ha.c pins that). `path_dependent` declares
    * what is true at the DEFAULT of 0: the recursion re-seeds at the anchor,
    * so HA(3, 7, ...) starts its open at (open[3]+close[3])/2 rather than
    * warming up from bar 0. Without it the range-stability leg compares a
    * sub-range call against a full-range one and fails; with only it, the
    * knob that makes the two converge would not exist.
    */
   lookbackTotal = TA_HA_Lookback();
   if( startIdx < lookbackTotal )
   {
      startIdx = lookbackTotal;
   }
   /* Make sure there is still something to evaluate. */
   if( startIdx > endIdx )
   {
      *outBegIdx= 0;
      *outNBElement= 0;
      return TA_SUCCESS;
   }
   /* The seed is carried as a VIRTUAL previous candle rather than as a
    * special first iteration: seeding the pair with the anchor bar's own
    * open and close makes the uniform recursion produce
    * (open+close)/2 at that bar, which is the published seed. One loop body
    * then serves the anchor bar and every bar after it -- and that same pair
    * is the streaming tier's initial state, so batch and stream share one
    * definition of "where the recursion starts".
    */
   today = startIdx - lookbackTotal;
   prevHAOpen = inOpen[today];
   prevHAClose = inClose[today];
   /* Warm-up: advance the recursion across the unstable-period bars without
    * emitting. Empty at the default knob of 0.
    */
   while( today < startIdx )
   {
      tempOpen = inOpen[today];
      tempHigh = inHigh[today];
      tempLow = inLow[today];
      tempClose = inClose[today];
      haOpen = (prevHAOpen + prevHAClose) / 2.0;
      haClose = (tempOpen + tempHigh + tempLow + tempClose) / 4.0;
      prevHAOpen = haOpen;
      prevHAClose = haClose;
      today += 1;
   }
   outIdx = 0;
   while( today <= endIdx )
   {
      tempOpen = inOpen[today];
      tempHigh = inHigh[today];
      tempLow = inLow[today];
      tempClose = inClose[today];
      haOpen = (prevHAOpen + prevHAClose) / 2.0;
      haClose = (tempOpen + tempHigh + tempLow + tempClose) / 4.0;
      /* An elementwise clamp of the raw bar against the two body edges, so
       * the extremes carry no state of their own.
       */
      haHigh = tempHigh;
      if( haOpen > haHigh )
      {
         haHigh = haOpen;
      }
      if( haClose > haHigh )
      {
         haHigh = haClose;
      }
      haLow = tempLow;
      if( haOpen < haLow )
      {
         haLow = haOpen;
      }
      if( haClose < haLow )
      {
         haLow = haClose;
      }
      /* Written only after this bar's four inputs are in locals above: an
       * output buffer is allowed to alias any input, and output slot k lands
       * on input bar k, which is at or behind `today`.
       */
      outHAOpen[outIdx] = haOpen;
      outHAHigh[outIdx] = haHigh;
      outHALow[outIdx] = haLow;
      outHAClose[outIdx] = haClose;
      outIdx += 1;
      prevHAOpen = haOpen;
      prevHAClose = haClose;
      today += 1;
   }
   *outBegIdx= startIdx;
   *outNBElement= outIdx;
   return TA_SUCCESS;
}

TA_RetCode TA_S_HA( int    startIdx,
                    int    endIdx,
                    const float inOpen[],
                    const float inHigh[],
                    const float inLow[],
                    const float inClose[],
                    int          *outBegIdx,
                    int          *outNBElement,
                    double        outHAOpen[],
                    double        outHAHigh[],
                    double        outHALow[],
                    double        outHAClose[] )
{
   int today;
   int outIdx;
   int lookbackTotal;
   double haOpen;
   double haClose;
   double haHigh;
   double haLow;
   double prevHAOpen;
   double prevHAClose;
   double tempOpen;
   double tempHigh;
   double tempLow;
   double tempClose;

   if( (startIdx < 0) || (startIdx > TA_MAX_INDEX) )
      return TA_OUT_OF_RANGE_START_INDEX;
   if( (endIdx < 0) || (endIdx > TA_MAX_INDEX) || (endIdx < startIdx) )
      return TA_OUT_OF_RANGE_END_INDEX;

   if( !inOpen )
      return TA_BAD_PARAM;
   if( !inHigh )
      return TA_BAD_PARAM;
   if( !inLow )
      return TA_BAD_PARAM;
   if( !inClose )
      return TA_BAD_PARAM;
   if( !outBegIdx || !outNBElement )
      return TA_BAD_PARAM;
   if( !outHAOpen )
      return TA_BAD_PARAM;
   if( !outHAHigh )
      return TA_BAD_PARAM;
   if( !outHALow )
      return TA_BAD_PARAM;
   if( !outHAClose )
      return TA_BAD_PARAM;
   if( outHAOpen == outHAHigh || outHAOpen == outHALow || outHAOpen == outHAClose || outHAHigh == outHALow || outHAHigh == outHAClose || outHALow == outHAClose )
      return TA_BAD_PARAM;

   lookbackTotal = TA_HA_Lookback();
   if( startIdx < lookbackTotal )
   {
      startIdx = lookbackTotal;
   }
   if( startIdx > endIdx )
   {
      *outBegIdx= 0;
      *outNBElement= 0;
      return TA_SUCCESS;
   }
   today = startIdx - lookbackTotal;
   prevHAOpen = (double)inOpen[today];
   prevHAClose = (double)inClose[today];
   while( today < startIdx )
   {
      tempOpen = (double)inOpen[today];
      tempHigh = (double)inHigh[today];
      tempLow = (double)inLow[today];
      tempClose = (double)inClose[today];
      haOpen = (prevHAOpen + prevHAClose) / 2.0;
      haClose = (tempOpen + tempHigh + tempLow + tempClose) / 4.0;
      prevHAOpen = haOpen;
      prevHAClose = haClose;
      today += 1;
   }
   outIdx = 0;
   while( today <= endIdx )
   {
      tempOpen = (double)inOpen[today];
      tempHigh = (double)inHigh[today];
      tempLow = (double)inLow[today];
      tempClose = (double)inClose[today];
      haOpen = (prevHAOpen + prevHAClose) / 2.0;
      haClose = (tempOpen + tempHigh + tempLow + tempClose) / 4.0;
      haHigh = tempHigh;
      if( haOpen > haHigh )
      {
         haHigh = haOpen;
      }
      if( haClose > haHigh )
      {
         haHigh = haClose;
      }
      haLow = tempLow;
      if( haOpen < haLow )
      {
         haLow = haOpen;
      }
      if( haClose < haLow )
      {
         haLow = haClose;
      }
      outHAOpen[outIdx] = haOpen;
      outHAHigh[outIdx] = haHigh;
      outHALow[outIdx] = haLow;
      outHAClose[outIdx] = haClose;
      outIdx += 1;
      prevHAOpen = haOpen;
      prevHAClose = haClose;
      today += 1;
   }
   *outBegIdx= startIdx;
   *outNBElement= outIdx;
   return TA_SUCCESS;
}

/**** Streaming API *****/

struct TA_HA_Stream {
   /* The bars this handle has an output for (see TA_StreamOutRange).
    * Kept first, and in this order, in every stream struct. */
   int outRangeBegIdx;
   int outRangeCount;
   /* The value(s) at the last bar the stream counted (see TA_HA_Value). */
   double cur_outHAOpen;
   double cur_outHAHigh;
   double cur_outHALow;
   double cur_outHAClose;
   double prevHAOpen;
   double prevHAClose;
};

/* Private function, not in public API. */
static void TA_HA_StepImpl( struct TA_HA_Stream *sp, double inOpen, double inHigh, double inLow, double inClose, double *outHAOpen, double *outHAHigh, double *outHALow, double *outHAClose )
{
   double haOpen;
   double haClose;
   double haHigh;
   double haLow;
   double tempOpen;
   double tempHigh;
   double tempLow;
   double tempClose;

   tempOpen = inOpen;
   tempHigh = inHigh;
   tempLow = inLow;
   tempClose = inClose;
   haOpen = (sp->prevHAOpen + sp->prevHAClose) / 2.0;
   haClose = (tempOpen + tempHigh + tempLow + tempClose) / 4.0;
   /* An elementwise clamp of the raw bar against the two body edges, so
    * the extremes carry no state of their own.
    */
   haHigh = tempHigh;
   if( haOpen > haHigh )
   {
      haHigh = haOpen;
   }
   if( haClose > haHigh )
   {
      haHigh = haClose;
   }
   haLow = tempLow;
   if( haOpen < haLow )
   {
      haLow = haOpen;
   }
   if( haClose < haLow )
   {
      haLow = haClose;
   }
   /* Written only after this bar's four inputs are in locals above: an
    * output buffer is allowed to alias any input, and output slot k lands
    * on input bar k, which is at or behind `today`.
    */
   *outHAOpen= haOpen;
   *outHAHigh= haHigh;
   *outHALow= haLow;
   *outHAClose= haClose;
   sp->prevHAOpen = haOpen;
   sp->prevHAClose = haClose;
   sp->cur_outHAOpen = *outHAOpen;
   sp->cur_outHAHigh = *outHAHigh;
   sp->cur_outHALow = *outHALow;
   sp->cur_outHAClose = *outHAClose;
}

static TA_RetCode TA_HA_OpenImpl( struct TA_HA_Stream **stream, const double inOpen[], const double inHigh[], const double inLow[], const double inClose[], int startIdx, int historyLen, int *outBegIdx, int *outNBElement, double outHAOpen[], double outHAHigh[], double outHALow[], double outHAClose[], int outStride )
{
   struct TA_HA_Stream *sp;
   int endIdx;

   if( !stream ) return TA_BAD_PARAM;
   *stream = NULL;
   if( historyLen < 1 ) return TA_OUT_OF_RANGE_START_INDEX;
   if( historyLen > TA_MAX_INDEX + 1 ) return TA_OUT_OF_RANGE_END_INDEX;
   if( !inOpen || !inHigh || !inLow || !inClose || !outHAOpen || !outHAHigh || !outHALow || !outHAClose ) return TA_BAD_PARAM;
   if( startIdx > historyLen - 1 )
   {
      *outBegIdx = 0;
      *outNBElement = 0;
      return TA_INSUFFICIENT_HISTORY;
   }

   endIdx = historyLen - 1;

   {
      int today;
      int outIdx;
      int lookbackTotal;
      double haOpen;
      double haClose;
      double haHigh;
      double haLow;
      double prevHAOpen = 0.0;
      double prevHAClose = 0.0;
      double tempOpen;
      double tempHigh;
      double tempLow;
      double tempClose;
      /* Heikin-Ashi ("average bar"): an OHLC-to-OHLC smoothing transform.
       *
       *   HA_close[i] = (open[i] + high[i] + low[i] + close[i]) / 4
       *   HA_open [0] = (open[0] + close[0]) / 2
       *   HA_open [i] = (HA_open[i-1] + HA_close[i-1]) / 2
       *   HA_high [i] = max(high[i], HA_open[i], HA_close[i])
       *   HA_low  [i] = min(low [i], HA_open[i], HA_close[i])
       *
       * Keep the four-term sum in THIS left-to-right order. It is the oracles'
       * association, and floating-point addition is not associative:
       * TA_AVGPRICE sums the same four terms as (H+L+C+O)/4 and differs from
       * HA_close in the last place on ordinary bars, so HA_close is not a
       * composed AVGPRICE call and the two must not be unified.
       *
       * Every operation is one addition or one division by an exact power of
       * two, so the transform is exact whenever its inputs are -- which is why
       * the external captures are frozen at tolerance 0 rather than a band.
       *
       * BOTH stability flags are declared, and they answer different questions.
       * `unstable_period` is the ABI knob: the open's recursion carries a factor
       * of 1/2 per bar, so a seed's influence halves every step and dies out
       * entirely within a few dozen bars -- a caller who spends them gets a
       * start-independent series (56 bars suffice on the regtest history, and
       * test_ha.c pins that). `path_dependent` declares
       * what is true at the DEFAULT of 0: the recursion re-seeds at the anchor,
       * so HA(3, 7, ...) starts its open at (open[3]+close[3])/2 rather than
       * warming up from bar 0. Without it the range-stability leg compares a
       * sub-range call against a full-range one and fails; with only it, the
       * knob that makes the two converge would not exist.
       */
      lookbackTotal = TA_HA_Lookback();
      if( startIdx < lookbackTotal )
      {
         startIdx = lookbackTotal;
      }
      /* Make sure there is still something to evaluate. */
      if( startIdx > endIdx )
      {
         *outBegIdx= 0;
         *outNBElement= 0;
         return TA_INSUFFICIENT_HISTORY;
      }
      /* The seed is carried as a VIRTUAL previous candle rather than as a
       * special first iteration: seeding the pair with the anchor bar's own
       * open and close makes the uniform recursion produce
       * (open+close)/2 at that bar, which is the published seed. One loop body
       * then serves the anchor bar and every bar after it -- and that same pair
       * is the streaming tier's initial state, so batch and stream share one
       * definition of "where the recursion starts".
       */
      today = startIdx - lookbackTotal;
      prevHAOpen = inOpen[today];
      prevHAClose = inClose[today];
      /* Warm-up: advance the recursion across the unstable-period bars without
       * emitting. Empty at the default knob of 0.
       */
      while( today < startIdx )
      {
         tempOpen = inOpen[today];
         tempHigh = inHigh[today];
         tempLow = inLow[today];
         tempClose = inClose[today];
         haOpen = (prevHAOpen + prevHAClose) / 2.0;
         haClose = (tempOpen + tempHigh + tempLow + tempClose) / 4.0;
         prevHAOpen = haOpen;
         prevHAClose = haClose;
         today += 1;
      }
      outIdx = 0;
      while( today <= endIdx )
      {
         tempOpen = inOpen[today];
         tempHigh = inHigh[today];
         tempLow = inLow[today];
         tempClose = inClose[today];
         haOpen = (prevHAOpen + prevHAClose) / 2.0;
         haClose = (tempOpen + tempHigh + tempLow + tempClose) / 4.0;
         /* An elementwise clamp of the raw bar against the two body edges, so
          * the extremes carry no state of their own.
          */
         haHigh = tempHigh;
         if( haOpen > haHigh )
         {
            haHigh = haOpen;
         }
         if( haClose > haHigh )
         {
            haHigh = haClose;
         }
         haLow = tempLow;
         if( haOpen < haLow )
         {
            haLow = haOpen;
         }
         if( haClose < haLow )
         {
            haLow = haClose;
         }
         /* Written only after this bar's four inputs are in locals above: an
          * output buffer is allowed to alias any input, and output slot k lands
          * on input bar k, which is at or behind `today`.
          */
         outHAOpen[outIdx * outStride] = haOpen;
         outHAHigh[outIdx * outStride] = haHigh;
         outHALow[outIdx * outStride] = haLow;
         outHAClose[outIdx * outStride] = haClose;
         outIdx += 1;
         prevHAOpen = haOpen;
         prevHAClose = haClose;
         today += 1;
      }
      *outBegIdx= startIdx;
      *outNBElement= outIdx;

      /* Capture the live batch state into the handle. */
      sp = (struct TA_HA_Stream *)TA_Malloc( sizeof(*sp) );
      if( !sp ) { return TA_ALLOC_ERR; }
      memset( sp, 0, sizeof(*sp) );
      sp->prevHAOpen = prevHAOpen;
      sp->prevHAClose = prevHAClose;
      sp->outRangeBegIdx = *outBegIdx;
      sp->outRangeCount = *outNBElement;
      sp->cur_outHAOpen = outHAOpen[(*outNBElement - 1) * outStride];
      sp->cur_outHAHigh = outHAHigh[(*outNBElement - 1) * outStride];
      sp->cur_outHALow = outHALow[(*outNBElement - 1) * outStride];
      sp->cur_outHAClose = outHAClose[(*outNBElement - 1) * outStride];
      *stream = sp;
      return TA_SUCCESS;
   }
}

/* Private function, not in public API. */
TA_RetCode TA_HA_OpenInternal( struct TA_HA_Stream **stream, const double inOpen[], const double inHigh[], const double inLow[], const double inClose[], int startIdx, int historyLen, double *outHAOpen, double *outHAHigh, double *outHALow, double *outHAClose )
{
   TA_RetCode retCode;
   int dummyBegIdx = 0;
   int dummyNBElement = 0;
   double sink_outHAOpen = 0.0;
   double sink_outHAHigh = 0.0;
   double sink_outHALow = 0.0;
   double sink_outHAClose = 0.0;
   retCode = TA_HA_OpenImpl( stream, inOpen, inHigh, inLow, inClose, startIdx, historyLen, &dummyBegIdx, &dummyNBElement, &sink_outHAOpen, &sink_outHAHigh, &sink_outHALow, &sink_outHAClose, 0 );
   if( retCode == TA_SUCCESS )
   {
      *outHAOpen = sink_outHAOpen;
      *outHAHigh = sink_outHAHigh;
      *outHALow = sink_outHALow;
      *outHAClose = sink_outHAClose;
   }
   return retCode;
}

TA_LIB_API TA_RetCode TA_HA_Open( TA_HA_Stream **stream, const double inOpen[], const double inHigh[], const double inLow[], const double inClose[], int historyLen, double *outHAOpen, double *outHAHigh, double *outHALow, double *outHAClose )
{
   if( !stream ) return TA_BAD_PARAM;
   *stream = NULL;
   if( historyLen < 1 ) return TA_OUT_OF_RANGE_START_INDEX;
   if( historyLen > TA_MAX_INDEX + 1 ) return TA_OUT_OF_RANGE_END_INDEX;
   if( !inOpen || !inHigh || !inLow || !inClose || !outHAOpen || !outHAHigh || !outHALow || !outHAClose ) return TA_BAD_PARAM;
   return TA_HA_OpenInternal( stream, inOpen, inHigh, inLow, inClose, 0, historyLen, outHAOpen, outHAHigh, outHALow, outHAClose );
}

TA_LIB_API TA_RetCode TA_HA_OpenAndFill( TA_HA_Stream **stream, const double inOpen[], const double inHigh[], const double inLow[], const double inClose[], int historyLen, int *outBegIdx, int *outNBElement, double outHAOpen[], double outHAHigh[], double outHALow[], double outHAClose[] )
{
   if( !stream ) return TA_BAD_PARAM;
   *stream = NULL;
   if( historyLen < 1 ) return TA_OUT_OF_RANGE_START_INDEX;
   if( historyLen > TA_MAX_INDEX + 1 ) return TA_OUT_OF_RANGE_END_INDEX;
   if( !inOpen || !inHigh || !inLow || !inClose || !outBegIdx || !outNBElement || !outHAOpen || !outHAHigh || !outHALow || !outHAClose ) return TA_BAD_PARAM;
   if( (const void *)outHAOpen == (const void *)inOpen || (const void *)outHAOpen == (const void *)inHigh || (const void *)outHAOpen == (const void *)inLow || (const void *)outHAOpen == (const void *)inClose || (const void *)outHAHigh == (const void *)inOpen || (const void *)outHAHigh == (const void *)inHigh || (const void *)outHAHigh == (const void *)inLow || (const void *)outHAHigh == (const void *)inClose || (const void *)outHALow == (const void *)inOpen || (const void *)outHALow == (const void *)inHigh || (const void *)outHALow == (const void *)inLow || (const void *)outHALow == (const void *)inClose || (const void *)outHAClose == (const void *)inOpen || (const void *)outHAClose == (const void *)inHigh || (const void *)outHAClose == (const void *)inLow || (const void *)outHAClose == (const void *)inClose || (const void *)outHAOpen == (const void *)outHAHigh || (const void *)outHAOpen == (const void *)outHALow || (const void *)outHAOpen == (const void *)outHAClose || (const void *)outHAHigh == (const void *)outHALow || (const void *)outHAHigh == (const void *)outHAClose || (const void *)outHALow == (const void *)outHAClose ) return TA_BAD_PARAM;
   return TA_HA_OpenAndFillInternal( stream, inOpen, inHigh, inLow, inClose, 0, historyLen, outBegIdx, outNBElement, outHAOpen, outHAHigh, outHALow, outHAClose );
}

/* Private function, not in public API. */
TA_RetCode TA_HA_OpenAndFillInternal( struct TA_HA_Stream **stream, const double inOpen[], const double inHigh[], const double inLow[], const double inClose[], int startIdx, int historyLen, int *outBegIdx, int *outNBElement, double outHAOpen[], double outHAHigh[], double outHALow[], double outHAClose[] )
{
   return TA_HA_OpenImpl( stream, inOpen, inHigh, inLow, inClose, startIdx, historyLen, outBegIdx, outNBElement, outHAOpen, outHAHigh, outHALow, outHAClose, 1 );
}

TA_LIB_API TA_RetCode TA_HA_Update( TA_HA_Stream *stream, double inOpen, double inHigh, double inLow, double inClose, double *outHAOpen, double *outHAHigh, double *outHALow, double *outHAClose )
{
   if( !stream || !outHAOpen || !outHAHigh || !outHALow || !outHAClose ) return TA_BAD_PARAM;
   if( !TA_IS_FINITE( inOpen ) || !TA_IS_FINITE( inHigh ) || !TA_IS_FINITE( inLow ) || !TA_IS_FINITE( inClose ) )
   {
      if( stream->outRangeCount < TA_MAX_INDEX ) stream->outRangeCount++;
      return TA_BAD_PARAM;
   }
   TA_HA_StepImpl( stream, inOpen, inHigh, inLow, inClose, outHAOpen, outHAHigh, outHALow, outHAClose );
   if( stream->outRangeCount < TA_MAX_INDEX ) stream->outRangeCount++;
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_HA_Peek( const TA_HA_Stream *stream, double inOpen, double inHigh, double inLow, double inClose, double *outHAOpen, double *outHAHigh, double *outHALow, double *outHAClose )
{
   const struct TA_HA_Stream *sp = stream;
   double haOpen;
   double haClose;
   double haHigh;
   double haLow;
   double tempOpen;
   double tempHigh;
   double tempLow;
   double tempClose;

   if( !stream || !outHAOpen || !outHAHigh || !outHALow || !outHAClose ) return TA_BAD_PARAM;
   if( !TA_IS_FINITE( inOpen ) || !TA_IS_FINITE( inHigh ) || !TA_IS_FINITE( inLow ) || !TA_IS_FINITE( inClose ) ) return TA_BAD_PARAM;
   tempOpen = inOpen;
   tempHigh = inHigh;
   tempLow = inLow;
   tempClose = inClose;
   haOpen = (sp->prevHAOpen + sp->prevHAClose) / 2.0;
   haClose = (tempOpen + tempHigh + tempLow + tempClose) / 4.0;
   /* An elementwise clamp of the raw bar against the two body edges, so
    * the extremes carry no state of their own.
    */
   haHigh = tempHigh;
   if( haOpen > haHigh )
   {
      haHigh = haOpen;
   }
   if( haClose > haHigh )
   {
      haHigh = haClose;
   }
   haLow = tempLow;
   if( haOpen < haLow )
   {
      haLow = haOpen;
   }
   if( haClose < haLow )
   {
      haLow = haClose;
   }
   /* Written only after this bar's four inputs are in locals above: an
    * output buffer is allowed to alias any input, and output slot k lands
    * on input bar k, which is at or behind `today`.
    */
   *outHAOpen= haOpen;
   *outHAHigh= haHigh;
   *outHALow= haLow;
   *outHAClose= haClose;
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_HA_UpdateAndFill( TA_HA_Stream *stream, const double inOpen[], const double inHigh[], const double inLow[], const double inClose[], int barCount, double outHAOpen[], double outHAHigh[], double outHALow[], double outHAClose[] )
{
   int i;

   if( !stream || !inOpen || !inHigh || !inLow || !inClose || !outHAOpen || !outHAHigh || !outHALow || !outHAClose ) return TA_BAD_PARAM;
   if( barCount < 0 ) return TA_BAD_PARAM;
   if( (const void *)outHAOpen == (const void *)inOpen || (const void *)outHAOpen == (const void *)inHigh || (const void *)outHAOpen == (const void *)inLow || (const void *)outHAOpen == (const void *)inClose || (const void *)outHAHigh == (const void *)inOpen || (const void *)outHAHigh == (const void *)inHigh || (const void *)outHAHigh == (const void *)inLow || (const void *)outHAHigh == (const void *)inClose || (const void *)outHALow == (const void *)inOpen || (const void *)outHALow == (const void *)inHigh || (const void *)outHALow == (const void *)inLow || (const void *)outHALow == (const void *)inClose || (const void *)outHAClose == (const void *)inOpen || (const void *)outHAClose == (const void *)inHigh || (const void *)outHAClose == (const void *)inLow || (const void *)outHAClose == (const void *)inClose || (const void *)outHAOpen == (const void *)outHAHigh || (const void *)outHAOpen == (const void *)outHALow || (const void *)outHAOpen == (const void *)outHAClose || (const void *)outHAHigh == (const void *)outHALow || (const void *)outHAHigh == (const void *)outHAClose || (const void *)outHALow == (const void *)outHAClose ) return TA_BAD_PARAM;
   for( i = 0; i < barCount; i++ )
   {
      if( !TA_IS_FINITE( inOpen[i] ) || !TA_IS_FINITE( inHigh[i] ) || !TA_IS_FINITE( inLow[i] ) || !TA_IS_FINITE( inClose[i] ) )
      {
         if( stream->outRangeCount < TA_MAX_INDEX ) stream->outRangeCount++;
         return TA_BAD_PARAM;
      }
      TA_HA_StepImpl( stream, inOpen[i], inHigh[i], inLow[i], inClose[i], &outHAOpen[i], &outHAHigh[i], &outHALow[i], &outHAClose[i] );
      if( stream->outRangeCount < TA_MAX_INDEX ) stream->outRangeCount++;
   }
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_HA_Close( TA_HA_Stream *stream )
{
   if( stream ) TA_Free( stream );
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_HA_Value( const TA_HA_Stream *stream, double *outHAOpen, double *outHAHigh, double *outHALow, double *outHAClose )
{
   if( !stream || !outHAOpen || !outHAHigh || !outHALow || !outHAClose ) return TA_BAD_PARAM;
   *outHAOpen = stream->cur_outHAOpen;
   *outHAHigh = stream->cur_outHAHigh;
   *outHALow = stream->cur_outHALow;
   *outHAClose = stream->cur_outHAClose;
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_HA_Clone( const TA_HA_Stream *stream, TA_HA_Stream **clone )
{
   struct TA_HA_Stream *sp;

   if( !clone ) return TA_BAD_PARAM;
   *clone = NULL;
   if( !stream ) return TA_BAD_PARAM;
   sp = (struct TA_HA_Stream *)TA_Malloc( sizeof(*sp) );
   if( !sp ) return TA_ALLOC_ERR;
   *sp = *stream;
   *clone = sp;
   return TA_SUCCESS;
}

