/* TA-LIB Copyright (c) 1999-2026, Mario Fortier
* All rights reserved.
*
* Redistribution and use in source and binary forms, with or
* without modification, are permitted provided that the following
* conditions are met:
*
* - Redistributions of source code must retain the above copyright
*   notice, this list of conditions and the following disclaimer.
*
* - Redistributions in binary form must reproduce the above copyright
*   notice, this list of conditions and the following disclaimer in
*   the documentation and/or other materials provided with the
*   distribution.
*
* - Neither name of author nor the names of its contributors
*   may be used to endorse or promote products derived from this
*   software without specific prior written permission.
*
* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
* ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
* LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
* FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
* REGENTS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
* INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
* (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
* OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
* INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
* WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
* OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
* EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

/* AUTO-GENERATED by ta_codegen — DO NOT EDIT.
* Source of truth: ta_codegen/input/<name>/  (regenerate: cd ta_codegen/generator && cargo run -- generate)
*/

#include <string.h>
#include <math.h>
#include "ta_func.h"
#include "ta_utility.h"
#include "ta_memory.h"
#include "ta_func_stream_private.h"

/* List of contributors:
 *
 *  Initial  Name/description
 *  -------------------------------------------------------------------
 *  KL       Kevin Lin
 *
 * Change history:
 *
 *  MMDDYY BY     Description
 *  -------------------------------------------------------------------
 *  090526 KL     First version (issue #373).
 */

TA_LIB_API int TA_HA_Lookback( void )
{
   return TA_GLOBALS_UNSTABLE_PERIOD(TA_FUNC_UNST_HA,Ha);
}

TA_LIB_API TA_RetCode TA_HA( int    startIdx,
                             int    endIdx,
                             const double inOpen[],
                             const double inHigh[],
                             const double inLow[],
                             const double inClose[],
                             int          *outBegIdx,
                             int          *outNBElement,
                             double        outHAOpen[],
                             double        outHAHigh[],
                             double        outHALow[],
                             double        outHAClose[] )
{
   int i;
   int outIdx;
   int today;
   int lookbackTotal;
   double haOpen;
   double haClose;
   double tempHigh;
   double tempLow;

   if( (startIdx < 0) || (startIdx > TA_MAX_INDEX) )
      return TA_OUT_OF_RANGE_START_INDEX;
   if( (endIdx < 0) || (endIdx > TA_MAX_INDEX) || (endIdx < startIdx) )
      return TA_OUT_OF_RANGE_END_INDEX;

   if( !inOpen )
      return TA_BAD_PARAM;
   if( !inHigh )
      return TA_BAD_PARAM;
   if( !inLow )
      return TA_BAD_PARAM;
   if( !inClose )
      return TA_BAD_PARAM;
   if( !outBegIdx || !outNBElement )
      return TA_BAD_PARAM;
   if( !outHAOpen )
      return TA_BAD_PARAM;
   if( !outHAHigh )
      return TA_BAD_PARAM;
   if( !outHALow )
      return TA_BAD_PARAM;
   if( !outHAClose )
      return TA_BAD_PARAM;
   if( outHAOpen == outHAHigh || outHAOpen == outHALow || outHAOpen == outHAClose || outHAHigh == outHALow || outHAHigh == outHAClose || outHALow == outHAClose )
      return TA_BAD_PARAM;

   *outBegIdx= 0;
   *outNBElement= 0;
   lookbackTotal = TA_HA_Lookback();
   if( startIdx < lookbackTotal )
   {
      startIdx = lookbackTotal;
   }
   if( startIdx > endIdx )
   {
      return TA_SUCCESS;
   }
   /* The seed is the published convention: the first candle opens at the raw
    * bar's own midpoint. Its influence halves every bar, which is why the
    * function is unstable-period rather than path-dependent -- a longer warm-up
    * buys convergence, it does not change the answer forever.
    */
   today = startIdx - lookbackTotal;
   haOpen = (inOpen[today] + inClose[today]) / 2.0;
   haClose = (inOpen[today] + inHigh[today] + inLow[today] + inClose[today]) / 4.0;
   /* Warm-up. Emits nothing; it only carries the pair forward to startIdx. */
   for( i = today + 1; i <= startIdx; i += 1 )
   {
      haOpen = (haOpen + haClose) / 2.0;
      haClose = (inOpen[i] + inHigh[i] + inLow[i] + inClose[i]) / 4.0;
   }
   /* The summation order ((o+h)+l)+c and the two exact power-of-two divisions
    * are the whole numeric contract: every published implementation sums in
    * that order, so the result is bit-exact against them rather than close.
    * TA_AVGPRICE's (h+l+c+o)/4 is a different order and differs by 1 ulp.
    *
    * The high and low are elementwise over bar-i quantities only, so they carry
    * no state -- haOpen and haClose remain the entire recurrence.
    *
    * In-place is supported: this bar's four input values are read into the
    * recurrence (and into tempHigh/tempLow) before the first store, so an
    * output aliasing any input cannot clobber a value still owed to this bar.
    * The dialect has no 3-arg max/min; nest the 2-arg builtins.
    */
   outIdx = 0;
   tempHigh = inHigh[startIdx];
   tempLow = inLow[startIdx];
   outHAOpen[outIdx] = haOpen;
   outHAHigh[outIdx] = max(max(tempHigh,haOpen),haClose);
   outHALow[outIdx] = min(min(tempLow,haOpen),haClose);
   outHAClose[outIdx] = haClose;
   outIdx += 1;
   for( i = startIdx + 1; i <= endIdx; i += 1 )
   {
      tempHigh = inHigh[i];
      tempLow = inLow[i];
      haOpen = (haOpen + haClose) / 2.0;
      haClose = (inOpen[i] + tempHigh + tempLow + inClose[i]) / 4.0;
      outHAOpen[outIdx] = haOpen;
      outHAHigh[outIdx] = max(max(tempHigh,haOpen),haClose);
      outHALow[outIdx] = min(min(tempLow,haOpen),haClose);
      outHAClose[outIdx] = haClose;
      outIdx += 1;
   }
   *outBegIdx= startIdx;
   *outNBElement= outIdx;
   return TA_SUCCESS;
}

TA_RetCode TA_S_HA( int    startIdx,
                    int    endIdx,
                    const float inOpen[],
                    const float inHigh[],
                    const float inLow[],
                    const float inClose[],
                    int          *outBegIdx,
                    int          *outNBElement,
                    double        outHAOpen[],
                    double        outHAHigh[],
                    double        outHALow[],
                    double        outHAClose[] )
{
   int i;
   int outIdx;
   int today;
   int lookbackTotal;
   double haOpen;
   double haClose;
   double tempHigh;
   double tempLow;

   if( (startIdx < 0) || (startIdx > TA_MAX_INDEX) )
      return TA_OUT_OF_RANGE_START_INDEX;
   if( (endIdx < 0) || (endIdx > TA_MAX_INDEX) || (endIdx < startIdx) )
      return TA_OUT_OF_RANGE_END_INDEX;

   if( !inOpen )
      return TA_BAD_PARAM;
   if( !inHigh )
      return TA_BAD_PARAM;
   if( !inLow )
      return TA_BAD_PARAM;
   if( !inClose )
      return TA_BAD_PARAM;
   if( !outBegIdx || !outNBElement )
      return TA_BAD_PARAM;
   if( !outHAOpen )
      return TA_BAD_PARAM;
   if( !outHAHigh )
      return TA_BAD_PARAM;
   if( !outHALow )
      return TA_BAD_PARAM;
   if( !outHAClose )
      return TA_BAD_PARAM;
   if( outHAOpen == outHAHigh || outHAOpen == outHALow || outHAOpen == outHAClose || outHAHigh == outHALow || outHAHigh == outHAClose || outHALow == outHAClose )
      return TA_BAD_PARAM;

   *outBegIdx= 0;
   *outNBElement= 0;
   lookbackTotal = TA_HA_Lookback();
   if( startIdx < lookbackTotal )
   {
      startIdx = lookbackTotal;
   }
   if( startIdx > endIdx )
   {
      return TA_SUCCESS;
   }
   today = startIdx - lookbackTotal;
   haOpen = ((double)inOpen[today] + (double)inClose[today]) / 2.0;
   haClose = ((double)inOpen[today] + (double)inHigh[today] + (double)inLow[today] + (double)inClose[today]) / 4.0;
   for( i = today + 1; i <= startIdx; i += 1 )
   {
      haOpen = (haOpen + haClose) / 2.0;
      haClose = ((double)inOpen[i] + (double)inHigh[i] + (double)inLow[i] + (double)inClose[i]) / 4.0;
   }
   outIdx = 0;
   tempHigh = (double)inHigh[startIdx];
   tempLow = (double)inLow[startIdx];
   outHAOpen[outIdx] = haOpen;
   outHAHigh[outIdx] = max(max(tempHigh,haOpen),haClose);
   outHALow[outIdx] = min(min(tempLow,haOpen),haClose);
   outHAClose[outIdx] = haClose;
   outIdx += 1;
   for( i = startIdx + 1; i <= endIdx; i += 1 )
   {
      tempHigh = (double)inHigh[i];
      tempLow = (double)inLow[i];
      haOpen = (haOpen + haClose) / 2.0;
      haClose = ((double)inOpen[i] + tempHigh + tempLow + (double)inClose[i]) / 4.0;
      outHAOpen[outIdx] = haOpen;
      outHAHigh[outIdx] = max(max(tempHigh,haOpen),haClose);
      outHALow[outIdx] = min(min(tempLow,haOpen),haClose);
      outHAClose[outIdx] = haClose;
      outIdx += 1;
   }
   *outBegIdx= startIdx;
   *outNBElement= outIdx;
   return TA_SUCCESS;
}

/**** Streaming API *****/

struct TA_HA_Stream {
   /* The bars this handle has an output for (see TA_StreamOutRange).
    * Kept first, and in this order, in every stream struct. */
   int outRangeBegIdx;
   int outRangeCount;
   /* The value(s) at the last bar the stream counted (see TA_HA_Value). */
   double cur_outHAOpen;
   double cur_outHAHigh;
   double cur_outHALow;
   double cur_outHAClose;
   double haOpen;
   double haClose;
};

/* Private function, not in public API. */
static void TA_HA_StepImpl( struct TA_HA_Stream *sp, double inOpen, double inHigh, double inLow, double inClose, double *outHAOpen, double *outHAHigh, double *outHALow, double *outHAClose )
{
   double tempHigh;
   double tempLow;
   double haOpen;
   double haClose;

   haOpen = sp->haOpen;
   haClose = sp->haClose;
   tempHigh = inHigh;
   tempLow = inLow;
   haOpen = (haOpen + haClose) / 2.0;
   haClose = (inOpen + tempHigh + tempLow + inClose) / 4.0;
   *outHAOpen= haOpen;
   *outHAHigh= max(max(tempHigh,haOpen),haClose);
   *outHALow= min(min(tempLow,haOpen),haClose);
   *outHAClose= haClose;
   sp->cur_outHAOpen = *outHAOpen;
   sp->cur_outHAHigh = *outHAHigh;
   sp->cur_outHALow = *outHALow;
   sp->cur_outHAClose = *outHAClose;
   sp->haOpen = haOpen;
   sp->haClose = haClose;
}

static TA_RetCode TA_HA_OpenImpl( struct TA_HA_Stream **stream, const double inOpen[], const double inHigh[], const double inLow[], const double inClose[], int startIdx, int historyLen, int *outBegIdx, int *outNBElement, double outHAOpen[], double outHAHigh[], double outHALow[], double outHAClose[], int outStride )
{
   struct TA_HA_Stream *sp;
   int endIdx;

   if( !stream ) return TA_BAD_PARAM;
   *stream = NULL;
   if( historyLen < 1 ) return TA_OUT_OF_RANGE_START_INDEX;
   if( historyLen > TA_MAX_INDEX + 1 ) return TA_OUT_OF_RANGE_END_INDEX;
   if( !inOpen || !inHigh || !inLow || !inClose || !outHAOpen || !outHAHigh || !outHALow || !outHAClose ) return TA_BAD_PARAM;
   if( startIdx > historyLen - 1 )
   {
      *outBegIdx = 0;
      *outNBElement = 0;
      return TA_INSUFFICIENT_HISTORY;
   }

   endIdx = historyLen - 1;

   {
      int i;
      int outIdx;
      int today;
      int lookbackTotal;
      double haOpen = 0.0;
      double haClose = 0.0;
      double tempHigh;
      double tempLow;
      *outBegIdx= 0;
      *outNBElement= 0;
      lookbackTotal = TA_HA_Lookback();
      if( startIdx < lookbackTotal )
      {
         startIdx = lookbackTotal;
      }
      if( startIdx > endIdx )
      {
         return TA_INSUFFICIENT_HISTORY;
      }
      /* The seed is the published convention: the first candle opens at the raw
       * bar's own midpoint. Its influence halves every bar, which is why the
       * function is unstable-period rather than path-dependent -- a longer warm-up
       * buys convergence, it does not change the answer forever.
       */
      today = startIdx - lookbackTotal;
      haOpen = (inOpen[today] + inClose[today]) / 2.0;
      haClose = (inOpen[today] + inHigh[today] + inLow[today] + inClose[today]) / 4.0;
      /* Warm-up. Emits nothing; it only carries the pair forward to startIdx. */
      for( i = today + 1; i <= startIdx; i += 1 )
      {
         haOpen = (haOpen + haClose) / 2.0;
         haClose = (inOpen[i] + inHigh[i] + inLow[i] + inClose[i]) / 4.0;
      }
      /* The summation order ((o+h)+l)+c and the two exact power-of-two divisions
       * are the whole numeric contract: every published implementation sums in
       * that order, so the result is bit-exact against them rather than close.
       * TA_AVGPRICE's (h+l+c+o)/4 is a different order and differs by 1 ulp.
       *
       * The high and low are elementwise over bar-i quantities only, so they carry
       * no state -- haOpen and haClose remain the entire recurrence.
       *
       * In-place is supported: this bar's four input values are read into the
       * recurrence (and into tempHigh/tempLow) before the first store, so an
       * output aliasing any input cannot clobber a value still owed to this bar.
       * The dialect has no 3-arg max/min; nest the 2-arg builtins.
       */
      outIdx = 0;
      tempHigh = inHigh[startIdx];
      tempLow = inLow[startIdx];
      outHAOpen[outIdx * outStride] = haOpen;
      outHAHigh[outIdx * outStride] = max(max(tempHigh,haOpen),haClose);
      outHALow[outIdx * outStride] = min(min(tempLow,haOpen),haClose);
      outHAClose[outIdx * outStride] = haClose;
      outIdx += 1;
      for( i = startIdx + 1; i <= endIdx; i += 1 )
      {
         tempHigh = inHigh[i];
         tempLow = inLow[i];
         haOpen = (haOpen + haClose) / 2.0;
         haClose = (inOpen[i] + tempHigh + tempLow + inClose[i]) / 4.0;
         outHAOpen[outIdx * outStride] = haOpen;
         outHAHigh[outIdx * outStride] = max(max(tempHigh,haOpen),haClose);
         outHALow[outIdx * outStride] = min(min(tempLow,haOpen),haClose);
         outHAClose[outIdx * outStride] = haClose;
         outIdx += 1;
      }
      *outBegIdx= startIdx;
      *outNBElement= outIdx;

      /* Capture the live batch state into the handle. */
      sp = (struct TA_HA_Stream *)TA_Malloc( sizeof(*sp) );
      if( !sp ) { return TA_ALLOC_ERR; }
      memset( sp, 0, sizeof(*sp) );
      sp->haOpen = haOpen;
      sp->haClose = haClose;
      sp->outRangeBegIdx = *outBegIdx;
      sp->outRangeCount = *outNBElement;
      sp->cur_outHAOpen = outHAOpen[(*outNBElement - 1) * outStride];
      sp->cur_outHAHigh = outHAHigh[(*outNBElement - 1) * outStride];
      sp->cur_outHALow = outHALow[(*outNBElement - 1) * outStride];
      sp->cur_outHAClose = outHAClose[(*outNBElement - 1) * outStride];
      *stream = sp;
      return TA_SUCCESS;
   }
}

/* Private function, not in public API. */
TA_RetCode TA_HA_OpenInternal( struct TA_HA_Stream **stream, const double inOpen[], const double inHigh[], const double inLow[], const double inClose[], int startIdx, int historyLen, double *outHAOpen, double *outHAHigh, double *outHALow, double *outHAClose )
{
   TA_RetCode retCode;
   int dummyBegIdx = 0;
   int dummyNBElement = 0;
   double sink_outHAOpen = 0.0;
   double sink_outHAHigh = 0.0;
   double sink_outHALow = 0.0;
   double sink_outHAClose = 0.0;
   retCode = TA_HA_OpenImpl( stream, inOpen, inHigh, inLow, inClose, startIdx, historyLen, &dummyBegIdx, &dummyNBElement, &sink_outHAOpen, &sink_outHAHigh, &sink_outHALow, &sink_outHAClose, 0 );
   if( retCode == TA_SUCCESS )
   {
      *outHAOpen = sink_outHAOpen;
      *outHAHigh = sink_outHAHigh;
      *outHALow = sink_outHALow;
      *outHAClose = sink_outHAClose;
   }
   return retCode;
}

TA_LIB_API TA_RetCode TA_HA_Open( TA_HA_Stream **stream, const double inOpen[], const double inHigh[], const double inLow[], const double inClose[], int historyLen, double *outHAOpen, double *outHAHigh, double *outHALow, double *outHAClose )
{
   if( !stream ) return TA_BAD_PARAM;
   *stream = NULL;
   if( historyLen < 1 ) return TA_OUT_OF_RANGE_START_INDEX;
   if( historyLen > TA_MAX_INDEX + 1 ) return TA_OUT_OF_RANGE_END_INDEX;
   if( !inOpen || !inHigh || !inLow || !inClose || !outHAOpen || !outHAHigh || !outHALow || !outHAClose ) return TA_BAD_PARAM;
   return TA_HA_OpenInternal( stream, inOpen, inHigh, inLow, inClose, 0, historyLen, outHAOpen, outHAHigh, outHALow, outHAClose );
}

TA_LIB_API TA_RetCode TA_HA_OpenAndFill( TA_HA_Stream **stream, const double inOpen[], const double inHigh[], const double inLow[], const double inClose[], int historyLen, int *outBegIdx, int *outNBElement, double outHAOpen[], double outHAHigh[], double outHALow[], double outHAClose[] )
{
   if( !stream ) return TA_BAD_PARAM;
   *stream = NULL;
   if( historyLen < 1 ) return TA_OUT_OF_RANGE_START_INDEX;
   if( historyLen > TA_MAX_INDEX + 1 ) return TA_OUT_OF_RANGE_END_INDEX;
   if( !inOpen || !inHigh || !inLow || !inClose || !outBegIdx || !outNBElement || !outHAOpen || !outHAHigh || !outHALow || !outHAClose ) return TA_BAD_PARAM;
   if( (const void *)outHAOpen == (const void *)inOpen || (const void *)outHAOpen == (const void *)inHigh || (const void *)outHAOpen == (const void *)inLow || (const void *)outHAOpen == (const void *)inClose || (const void *)outHAHigh == (const void *)inOpen || (const void *)outHAHigh == (const void *)inHigh || (const void *)outHAHigh == (const void *)inLow || (const void *)outHAHigh == (const void *)inClose || (const void *)outHALow == (const void *)inOpen || (const void *)outHALow == (const void *)inHigh || (const void *)outHALow == (const void *)inLow || (const void *)outHALow == (const void *)inClose || (const void *)outHAClose == (const void *)inOpen || (const void *)outHAClose == (const void *)inHigh || (const void *)outHAClose == (const void *)inLow || (const void *)outHAClose == (const void *)inClose || (const void *)outHAOpen == (const void *)outHAHigh || (const void *)outHAOpen == (const void *)outHALow || (const void *)outHAOpen == (const void *)outHAClose || (const void *)outHAHigh == (const void *)outHALow || (const void *)outHAHigh == (const void *)outHAClose || (const void *)outHALow == (const void *)outHAClose ) return TA_BAD_PARAM;
   return TA_HA_OpenAndFillInternal( stream, inOpen, inHigh, inLow, inClose, 0, historyLen, outBegIdx, outNBElement, outHAOpen, outHAHigh, outHALow, outHAClose );
}

/* Private function, not in public API. */
TA_RetCode TA_HA_OpenAndFillInternal( struct TA_HA_Stream **stream, const double inOpen[], const double inHigh[], const double inLow[], const double inClose[], int startIdx, int historyLen, int *outBegIdx, int *outNBElement, double outHAOpen[], double outHAHigh[], double outHALow[], double outHAClose[] )
{
   return TA_HA_OpenImpl( stream, inOpen, inHigh, inLow, inClose, startIdx, historyLen, outBegIdx, outNBElement, outHAOpen, outHAHigh, outHALow, outHAClose, 1 );
}

TA_LIB_API TA_RetCode TA_HA_Update( TA_HA_Stream *stream, double inOpen, double inHigh, double inLow, double inClose, double *outHAOpen, double *outHAHigh, double *outHALow, double *outHAClose )
{
   if( !stream || !outHAOpen || !outHAHigh || !outHALow || !outHAClose ) return TA_BAD_PARAM;
   if( !TA_IS_FINITE( inOpen ) || !TA_IS_FINITE( inHigh ) || !TA_IS_FINITE( inLow ) || !TA_IS_FINITE( inClose ) )
   {
      if( stream->outRangeCount < TA_MAX_INDEX ) stream->outRangeCount++;
      return TA_BAD_PARAM;
   }
   TA_HA_StepImpl( stream, inOpen, inHigh, inLow, inClose, outHAOpen, outHAHigh, outHALow, outHAClose );
   if( stream->outRangeCount < TA_MAX_INDEX ) stream->outRangeCount++;
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_HA_Peek( const TA_HA_Stream *stream, double inOpen, double inHigh, double inLow, double inClose, double *outHAOpen, double *outHAHigh, double *outHALow, double *outHAClose )
{
   const struct TA_HA_Stream *sp = stream;
   double tempHigh;
   double tempLow;
   double haClose;
   double haOpen;

   if( !stream || !outHAOpen || !outHAHigh || !outHALow || !outHAClose ) return TA_BAD_PARAM;
   if( !TA_IS_FINITE( inOpen ) || !TA_IS_FINITE( inHigh ) || !TA_IS_FINITE( inLow ) || !TA_IS_FINITE( inClose ) ) return TA_BAD_PARAM;
   haClose = sp->haClose;
   haOpen = sp->haOpen;
   tempHigh = inHigh;
   tempLow = inLow;
   haOpen = (haOpen + haClose) / 2.0;
   haClose = (inOpen + tempHigh + tempLow + inClose) / 4.0;
   *outHAOpen= haOpen;
   *outHAHigh= max(max(tempHigh,haOpen),haClose);
   *outHALow= min(min(tempLow,haOpen),haClose);
   *outHAClose= haClose;
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_HA_UpdateAndFill( TA_HA_Stream *stream, const double inOpen[], const double inHigh[], const double inLow[], const double inClose[], int barCount, double outHAOpen[], double outHAHigh[], double outHALow[], double outHAClose[] )
{
   int i;

   if( !stream || !inOpen || !inHigh || !inLow || !inClose || !outHAOpen || !outHAHigh || !outHALow || !outHAClose ) return TA_BAD_PARAM;
   if( barCount < 0 ) return TA_BAD_PARAM;
   if( (const void *)outHAOpen == (const void *)inOpen || (const void *)outHAOpen == (const void *)inHigh || (const void *)outHAOpen == (const void *)inLow || (const void *)outHAOpen == (const void *)inClose || (const void *)outHAHigh == (const void *)inOpen || (const void *)outHAHigh == (const void *)inHigh || (const void *)outHAHigh == (const void *)inLow || (const void *)outHAHigh == (const void *)inClose || (const void *)outHALow == (const void *)inOpen || (const void *)outHALow == (const void *)inHigh || (const void *)outHALow == (const void *)inLow || (const void *)outHALow == (const void *)inClose || (const void *)outHAClose == (const void *)inOpen || (const void *)outHAClose == (const void *)inHigh || (const void *)outHAClose == (const void *)inLow || (const void *)outHAClose == (const void *)inClose || (const void *)outHAOpen == (const void *)outHAHigh || (const void *)outHAOpen == (const void *)outHALow || (const void *)outHAOpen == (const void *)outHAClose || (const void *)outHAHigh == (const void *)outHALow || (const void *)outHAHigh == (const void *)outHAClose || (const void *)outHALow == (const void *)outHAClose ) return TA_BAD_PARAM;
   for( i = 0; i < barCount; i++ )
   {
      if( !TA_IS_FINITE( inOpen[i] ) || !TA_IS_FINITE( inHigh[i] ) || !TA_IS_FINITE( inLow[i] ) || !TA_IS_FINITE( inClose[i] ) )
      {
         if( stream->outRangeCount < TA_MAX_INDEX ) stream->outRangeCount++;
         return TA_BAD_PARAM;
      }
      TA_HA_StepImpl( stream, inOpen[i], inHigh[i], inLow[i], inClose[i], &outHAOpen[i], &outHAHigh[i], &outHALow[i], &outHAClose[i] );
      if( stream->outRangeCount < TA_MAX_INDEX ) stream->outRangeCount++;
   }
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_HA_Close( TA_HA_Stream *stream )
{
   if( stream ) TA_Free( stream );
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_HA_Value( const TA_HA_Stream *stream, double *outHAOpen, double *outHAHigh, double *outHALow, double *outHAClose )
{
   if( !stream || !outHAOpen || !outHAHigh || !outHALow || !outHAClose ) return TA_BAD_PARAM;
   *outHAOpen = stream->cur_outHAOpen;
   *outHAHigh = stream->cur_outHAHigh;
   *outHALow = stream->cur_outHALow;
   *outHAClose = stream->cur_outHAClose;
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_HA_Clone( const TA_HA_Stream *stream, TA_HA_Stream **clone )
{
   struct TA_HA_Stream *sp;

   if( !clone ) return TA_BAD_PARAM;
   *clone = NULL;
   if( !stream ) return TA_BAD_PARAM;
   sp = (struct TA_HA_Stream *)TA_Malloc( sizeof(*sp) );
   if( !sp ) return TA_ALLOC_ERR;
   *sp = *stream;
   *clone = sp;
   return TA_SUCCESS;
}

