/* TA-LIB Copyright (c) 1999-2026, Mario Fortier
* All rights reserved.
*
* Redistribution and use in source and binary forms, with or
* without modification, are permitted provided that the following
* conditions are met:
*
* - Redistributions of source code must retain the above copyright
*   notice, this list of conditions and the following disclaimer.
*
* - Redistributions in binary form must reproduce the above copyright
*   notice, this list of conditions and the following disclaimer in
*   the documentation and/or other materials provided with the
*   distribution.
*
* - Neither name of author nor the names of its contributors
*   may be used to endorse or promote products derived from this
*   software without specific prior written permission.
*
* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
* ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
* LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
* FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
* REGENTS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
* INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
* (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
* OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
* INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
* WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
* OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
* EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

/* AUTO-GENERATED by ta_codegen — DO NOT EDIT.
* Source of truth: ta_codegen/input/<name>/  (regenerate: cd ta_codegen/generator && cargo run -- generate)
*/

#include <string.h>
#include <math.h>
#include "ta_func.h"
#include "ta_utility.h"
#include "ta_memory.h"
#include "ta_func_stream_private.h"

/* List of contributors:
 *
 *  Initial  Name/description
 *  -------------------------------------------------------------------
 *  MF       Mario Fortier
 *  CC       Claude Code (AI assistant)
 *
 * Change history:
 *
 *  MMDDYY BY     Description
 *  -------------------------------------------------------------------
 *  100726 MF,CC  Initial version (#490).
 */

TA_LIB_API int TA_ICHIMOKU_Lookback( int optInTenkanPeriod, int optInKijunPeriod, int optInSenkouBPeriod )
{
   int longest;
   if( (int)optInTenkanPeriod == TA_INTEGER_DEFAULT )
      optInTenkanPeriod = 9;
   else if( (int)optInTenkanPeriod < 2 || (int)optInTenkanPeriod > 100000 )
      return -1;
   if( (int)optInKijunPeriod == TA_INTEGER_DEFAULT )
      optInKijunPeriod = 26;
   else if( (int)optInKijunPeriod < 2 || (int)optInKijunPeriod > 100000 )
      return -1;
   if( (int)optInSenkouBPeriod == TA_INTEGER_DEFAULT )
      optInSenkouBPeriod = 52;
   else if( (int)optInSenkouBPeriod < 2 || (int)optInSenkouBPeriod > 100000 )
      return -1;
   /* Each line is a midpoint over its own window, so each needs its own
    * window filled; the first bar that has all of them is the longest one's.
    * The MAX is not simplified to the Senkou B period: nothing orders the
    * three, and a kijun longer than senkouB dominates.
    *
    * Span A is the mean of the other two lines, so it adds nothing: it is
    * ready on the bar they both are.
    */
   longest = optInTenkanPeriod;
   if( optInKijunPeriod > longest )
   {
      longest = optInKijunPeriod;
   }
   if( optInSenkouBPeriod > longest )
   {
      longest = optInSenkouBPeriod;
   }
   return longest - 1;
}

TA_LIB_API int TA_ICHIMOKU_DisplayShift( int optInTenkanPeriod, int optInKijunPeriod, int optInSenkouBPeriod, int outputIdx )
{
   if( TA_ICHIMOKU_Lookback( optInTenkanPeriod, optInKijunPeriod, optInSenkouBPeriod ) < 0 )
      return INT_MIN;
   if( (int)optInTenkanPeriod == TA_INTEGER_DEFAULT )
      optInTenkanPeriod = 9;
   else if( (int)optInTenkanPeriod < 2 || (int)optInTenkanPeriod > 100000 )
      return INT_MIN;
   if( (int)optInKijunPeriod == TA_INTEGER_DEFAULT )
      optInKijunPeriod = 26;
   else if( (int)optInKijunPeriod < 2 || (int)optInKijunPeriod > 100000 )
      return INT_MIN;
   if( (int)optInSenkouBPeriod == TA_INTEGER_DEFAULT )
      optInSenkouBPeriod = 52;
   else if( (int)optInSenkouBPeriod < 2 || (int)optInSenkouBPeriod > 100000 )
      return INT_MIN;
   if( outputIdx < 0 || outputIdx >= 4 )
      return INT_MIN;
   if( outputIdx == 0 || outputIdx == 1 )
      return 0;
   /* rL9: a shift of s means a chart draws the value computed at bar i at
    * bar i + s. The two spans are the leading ones -- Goichi Hosoda draws
    * them kijun bars into the future, which is what makes the cloud sit
    * ahead of price -- so their shift is POSITIVE, where dpo.c's and
    * fractal.c's are negative. The conversion and base lines are drawn on
    * the bar that computed them.
    *
    * The shift reads the optional parameters and the output index only,
    * never a setting (rL9).
    */
   if( outputIdx == 2 || outputIdx == 3 )
   {
      return optInKijunPeriod;
   }
   return 0;
}

TA_LIB_API TA_RetCode TA_ICHIMOKU( int    startIdx,
                                   int    endIdx,
                                   const double inHigh[],
                                   const double inLow[],
                                   int optInTenkanPeriod,
                                   int optInKijunPeriod,
                                   int optInSenkouBPeriod,
                                   int          *outBegIdx,
                                   int          *outNBElement,
                                   double        outTenkanSen[],
                                   double        outKijunSen[],
                                   double        outSenkouSpanA[],
                                   double        outSenkouSpanB[] )
{
   TA_RetCode retCode;
   int lookbackTotal;
   int n;
   int i;
   int tempBegIdx;
   int tempNbElement;
   double *tempT;
   double *tempK;
   double *tempB;

   if( (startIdx < 0) || (startIdx > TA_INDEX_MAX) )
      return TA_OUT_OF_RANGE_START_INDEX;
   if( (endIdx < 0) || (endIdx > TA_INDEX_MAX) || (endIdx < startIdx) )
      return TA_OUT_OF_RANGE_END_INDEX;

   if( (int)optInTenkanPeriod == TA_INTEGER_DEFAULT )
      optInTenkanPeriod = 9;
   else if( (int)optInTenkanPeriod < 2 || (int)optInTenkanPeriod > 100000 )
      return TA_BAD_PARAM;
   if( (int)optInKijunPeriod == TA_INTEGER_DEFAULT )
      optInKijunPeriod = 26;
   else if( (int)optInKijunPeriod < 2 || (int)optInKijunPeriod > 100000 )
      return TA_BAD_PARAM;
   if( (int)optInSenkouBPeriod == TA_INTEGER_DEFAULT )
      optInSenkouBPeriod = 52;
   else if( (int)optInSenkouBPeriod < 2 || (int)optInSenkouBPeriod > 100000 )
      return TA_BAD_PARAM;
   if( !inHigh )
      return TA_BAD_PARAM;
   if( !inLow )
      return TA_BAD_PARAM;
   if( !outBegIdx || !outNBElement )
      return TA_BAD_PARAM;
   if( !outTenkanSen )
      return TA_BAD_PARAM;
   if( !outKijunSen )
      return TA_BAD_PARAM;
   if( !outSenkouSpanA )
      return TA_BAD_PARAM;
   if( !outSenkouSpanB )
      return TA_BAD_PARAM;
   if( outTenkanSen == outKijunSen || outTenkanSen == outSenkouSpanA || outTenkanSen == outSenkouSpanB || outKijunSen == outSenkouSpanA || outKijunSen == outSenkouSpanB || outSenkouSpanA == outSenkouSpanB )
      return TA_BAD_PARAM;

   /* PROTOTYPE (#490 Q7): each line IS a midpoint over its own window, which is
    * exactly what midprice computes, so the three scans are three midprice calls
    * and Span A is the mean of two of them. MEASURED bit-identical to the fused
    * loop over four parameter triples on the suite's corpus, every line, before
    * this was written.
    *
    * The point is the stream tier: three windows of different periods cannot be
    * one extrema automaton (the census refuses with "expected exactly one
    * window-start variable"), but a composed body is a different tier.
    *
    * The three results go to temporaries and are copied at the end: every read of
    * high and low has to happen before the first write to a caller buffer, or an
    * output aliased onto an input is read after it has been overwritten.
    */
   lookbackTotal = TA_ICHIMOKU_Lookback(optInTenkanPeriod,optInKijunPeriod,optInSenkouBPeriod);
   if( startIdx < lookbackTotal )
   {
      startIdx = lookbackTotal;
   }
   if( startIdx > endIdx )
   {
      *outBegIdx= 0;
      *outNBElement= 0;
      return TA_SUCCESS;
   }
   n = endIdx - startIdx + 1;
   tempT = malloc(n * sizeof(double));
   if( !tempT )
   {
      *outBegIdx= 0;
      *outNBElement= 0;
      return TA_ALLOC_ERR;
   }
   tempK = malloc(n * sizeof(double));
   if( !tempK )
   {
      free(tempT);
      *outBegIdx= 0;
      *outNBElement= 0;
      return TA_ALLOC_ERR;
   }
   tempB = malloc(n * sizeof(double));
   if( !tempB )
   {
      free(tempT);
      free(tempK);
      *outBegIdx= 0;
      *outNBElement= 0;
      return TA_ALLOC_ERR;
   }
   retCode = TA_MIDPRICE(startIdx,endIdx,inHigh,inLow,optInTenkanPeriod,&tempBegIdx,&tempNbElement,tempT);
   if( retCode != TA_SUCCESS )
   {
      free(tempT);
      free(tempK);
      free(tempB);
      *outBegIdx= 0;
      *outNBElement= 0;
      return retCode;
   }
   retCode = TA_MIDPRICE(startIdx,endIdx,inHigh,inLow,optInKijunPeriod,&tempBegIdx,&tempNbElement,tempK);
   if( retCode != TA_SUCCESS )
   {
      free(tempT);
      free(tempK);
      free(tempB);
      *outBegIdx= 0;
      *outNBElement= 0;
      return retCode;
   }
   retCode = TA_MIDPRICE(startIdx,endIdx,inHigh,inLow,optInSenkouBPeriod,&tempBegIdx,&tempNbElement,tempB);
   if( retCode != TA_SUCCESS )
   {
      free(tempT);
      free(tempK);
      free(tempB);
      *outBegIdx= 0;
      *outNBElement= 0;
      return retCode;
   }
   /* Span A is the mean of the two lines, which medprice is over any two series. */
   retCode = TA_MEDPRICE(0,n - 1,tempT,tempK,&tempBegIdx,&tempNbElement,outSenkouSpanA);
   if( retCode != TA_SUCCESS )
   {
      free(tempT);
      free(tempK);
      free(tempB);
      *outBegIdx= 0;
      *outNBElement= 0;
      return retCode;
   }
   for( i = 0; i < n; i += 1 )
   {
      outTenkanSen[i] = tempT[i];
      outKijunSen[i] = tempK[i];
      outSenkouSpanB[i] = tempB[i];
   }
   free(tempT);
   free(tempK);
   free(tempB);
   *outBegIdx= startIdx;
   *outNBElement= n;
   return TA_SUCCESS;
}

TA_RetCode TA_S_ICHIMOKU( int    startIdx,
                          int    endIdx,
                          const float inHigh[],
                          const float inLow[],
                          int optInTenkanPeriod,
                          int optInKijunPeriod,
                          int optInSenkouBPeriod,
                          int          *outBegIdx,
                          int          *outNBElement,
                          double        outTenkanSen[],
                          double        outKijunSen[],
                          double        outSenkouSpanA[],
                          double        outSenkouSpanB[] )
{
   TA_RetCode retCode;
   int lookbackTotal;
   int n;
   int i;
   int tempBegIdx;
   int tempNbElement;
   double *tempT;
   double *tempK;
   double *tempB;

   if( (startIdx < 0) || (startIdx > TA_INDEX_MAX) )
      return TA_OUT_OF_RANGE_START_INDEX;
   if( (endIdx < 0) || (endIdx > TA_INDEX_MAX) || (endIdx < startIdx) )
      return TA_OUT_OF_RANGE_END_INDEX;

   if( (int)optInTenkanPeriod == TA_INTEGER_DEFAULT )
      optInTenkanPeriod = 9;
   else if( (int)optInTenkanPeriod < 2 || (int)optInTenkanPeriod > 100000 )
      return TA_BAD_PARAM;
   if( (int)optInKijunPeriod == TA_INTEGER_DEFAULT )
      optInKijunPeriod = 26;
   else if( (int)optInKijunPeriod < 2 || (int)optInKijunPeriod > 100000 )
      return TA_BAD_PARAM;
   if( (int)optInSenkouBPeriod == TA_INTEGER_DEFAULT )
      optInSenkouBPeriod = 52;
   else if( (int)optInSenkouBPeriod < 2 || (int)optInSenkouBPeriod > 100000 )
      return TA_BAD_PARAM;
   if( !inHigh )
      return TA_BAD_PARAM;
   if( !inLow )
      return TA_BAD_PARAM;
   if( !outBegIdx || !outNBElement )
      return TA_BAD_PARAM;
   if( !outTenkanSen )
      return TA_BAD_PARAM;
   if( !outKijunSen )
      return TA_BAD_PARAM;
   if( !outSenkouSpanA )
      return TA_BAD_PARAM;
   if( !outSenkouSpanB )
      return TA_BAD_PARAM;
   if( outTenkanSen == outKijunSen || outTenkanSen == outSenkouSpanA || outTenkanSen == outSenkouSpanB || outKijunSen == outSenkouSpanA || outKijunSen == outSenkouSpanB || outSenkouSpanA == outSenkouSpanB )
      return TA_BAD_PARAM;

   lookbackTotal = TA_ICHIMOKU_Lookback(optInTenkanPeriod,optInKijunPeriod,optInSenkouBPeriod);
   if( startIdx < lookbackTotal )
   {
      startIdx = lookbackTotal;
   }
   if( startIdx > endIdx )
   {
      *outBegIdx= 0;
      *outNBElement= 0;
      return TA_SUCCESS;
   }
   n = endIdx - startIdx + 1;
   tempT = malloc(n * sizeof(double));
   if( !tempT )
   {
      *outBegIdx= 0;
      *outNBElement= 0;
      return TA_ALLOC_ERR;
   }
   tempK = malloc(n * sizeof(double));
   if( !tempK )
   {
      free(tempT);
      *outBegIdx= 0;
      *outNBElement= 0;
      return TA_ALLOC_ERR;
   }
   tempB = malloc(n * sizeof(double));
   if( !tempB )
   {
      free(tempT);
      free(tempK);
      *outBegIdx= 0;
      *outNBElement= 0;
      return TA_ALLOC_ERR;
   }
   retCode = TA_S_MIDPRICE(startIdx,endIdx,inHigh,inLow,optInTenkanPeriod,&tempBegIdx,&tempNbElement,tempT);
   if( retCode != TA_SUCCESS )
   {
      free(tempT);
      free(tempK);
      free(tempB);
      *outBegIdx= 0;
      *outNBElement= 0;
      return retCode;
   }
   retCode = TA_S_MIDPRICE(startIdx,endIdx,inHigh,inLow,optInKijunPeriod,&tempBegIdx,&tempNbElement,tempK);
   if( retCode != TA_SUCCESS )
   {
      free(tempT);
      free(tempK);
      free(tempB);
      *outBegIdx= 0;
      *outNBElement= 0;
      return retCode;
   }
   retCode = TA_S_MIDPRICE(startIdx,endIdx,inHigh,inLow,optInSenkouBPeriod,&tempBegIdx,&tempNbElement,tempB);
   if( retCode != TA_SUCCESS )
   {
      free(tempT);
      free(tempK);
      free(tempB);
      *outBegIdx= 0;
      *outNBElement= 0;
      return retCode;
   }
   retCode = TA_MEDPRICE(0,n - 1,tempT,tempK,&tempBegIdx,&tempNbElement,outSenkouSpanA);
   if( retCode != TA_SUCCESS )
   {
      free(tempT);
      free(tempK);
      free(tempB);
      *outBegIdx= 0;
      *outNBElement= 0;
      return retCode;
   }
   for( i = 0; i < n; i += 1 )
   {
      outTenkanSen[i] = tempT[i];
      outKijunSen[i] = tempK[i];
      outSenkouSpanB[i] = tempB[i];
   }
   free(tempT);
   free(tempK);
   free(tempB);
   *outBegIdx= startIdx;
   *outNBElement= n;
   return TA_SUCCESS;
}

/**** Streaming API *****/

struct TA_ICHIMOKU_Stream {
   /* The bars this handle has an output for (see TA_ICHIMOKU_OutRange). */
   int outRangeBegIdx;
   int outRangeCount;
   /* The value(s) at the last bar the stream counted (see TA_ICHIMOKU_Value). */
   double cur_outTenkanSen;
   double cur_outKijunSen;
   double cur_outSenkouSpanA;
   double cur_outSenkouSpanB;
   int optInTenkanPeriod;
   int optInKijunPeriod;
   int optInSenkouBPeriod;
   TA_MIDPRICE_Stream *sub0;
   TA_MIDPRICE_Stream *sub1;
   TA_MIDPRICE_Stream *sub2;
   TA_MEDPRICE_Stream *sub3;
};

/* Private function, not in public API. */
static TA_RetCode TA_ICHIMOKU_StepImpl( struct TA_ICHIMOKU_Stream *sp, double inHigh, double inLow, double *outTenkanSen, double *outKijunSen, double *outSenkouSpanA, double *outSenkouSpanB )
{
   double cur_tempT = 0.0;
   double cur_tempK = 0.0;
   double cur_tempB = 0.0;
   double cur_outSenkouSpanA = 0.0;
   double cur_outTenkanSen = 0.0;
   double cur_outKijunSen = 0.0;
   double cur_outSenkouSpanB = 0.0;


   /* Pipeline the new bar through the sub-streams (batch tail order). */
   {
      TA_RetCode subRc = TA_MIDPRICE_Update( sp->sub0, inHigh, inLow, &cur_tempT );
      if( subRc != TA_SUCCESS ) return subRc;
   }
   {
      TA_RetCode subRc = TA_MIDPRICE_Update( sp->sub1, inHigh, inLow, &cur_tempK );
      if( subRc != TA_SUCCESS ) return subRc;
   }
   {
      TA_RetCode subRc = TA_MIDPRICE_Update( sp->sub2, inHigh, inLow, &cur_tempB );
      if( subRc != TA_SUCCESS ) return subRc;
   }
   {
      TA_RetCode subRc = TA_MEDPRICE_Update( sp->sub3, cur_tempT, cur_tempK, &cur_outSenkouSpanA );
      if( subRc != TA_SUCCESS ) return subRc;
   }
   /* Combine map (batch tail, per bar). */
   cur_outTenkanSen = cur_tempT;
   cur_outKijunSen = cur_tempK;
   cur_outSenkouSpanB = cur_tempB;
   *outTenkanSen = cur_outTenkanSen;
   *outKijunSen = cur_outKijunSen;
   *outSenkouSpanA = cur_outSenkouSpanA;
   *outSenkouSpanB = cur_outSenkouSpanB;
   return TA_SUCCESS;
}

static TA_RetCode TA_ICHIMOKU_OpenImpl( struct TA_ICHIMOKU_Stream **stream, const double inHigh[], const double inLow[], int startIdx, int historyLen, int optInTenkanPeriod, int optInKijunPeriod, int optInSenkouBPeriod, int *outBegIdx, int *outNBElement, double outTenkanSen[], double outKijunSen[], double outSenkouSpanA[], double outSenkouSpanB[], int outStride )
{
   struct TA_ICHIMOKU_Stream *sp;
   int endIdx;
   int dummyBegIdx;
   int dummyNBElement;
   TA_RetCode subRc;
   double *sc_outTenkanSen;
   double *sc_outKijunSen;
   double *sc_outSenkouSpanA;
   double *sc_outSenkouSpanB;
   TA_MIDPRICE_Stream *sub0;
   TA_MIDPRICE_Stream *sub1;
   TA_MIDPRICE_Stream *sub2;
   TA_MEDPRICE_Stream *sub3;

   if( !stream ) return TA_BAD_PARAM;
   *stream = NULL;
   if( historyLen < 1 ) return TA_OUT_OF_RANGE_START_INDEX;
   if( historyLen > TA_INDEX_MAX + 1 ) return TA_OUT_OF_RANGE_END_INDEX;
   if( !inHigh || !inLow || !outTenkanSen || !outKijunSen || !outSenkouSpanA || !outSenkouSpanB ) return TA_BAD_PARAM;
   if( (int)optInTenkanPeriod == TA_INTEGER_DEFAULT )
      optInTenkanPeriod = 9;
   else if( (int)optInTenkanPeriod < 2 || (int)optInTenkanPeriod > 100000 )
      return TA_BAD_PARAM;
   if( (int)optInKijunPeriod == TA_INTEGER_DEFAULT )
      optInKijunPeriod = 26;
   else if( (int)optInKijunPeriod < 2 || (int)optInKijunPeriod > 100000 )
      return TA_BAD_PARAM;
   if( (int)optInSenkouBPeriod == TA_INTEGER_DEFAULT )
      optInSenkouBPeriod = 52;
   else if( (int)optInSenkouBPeriod < 2 || (int)optInSenkouBPeriod > 100000 )
      return TA_BAD_PARAM;
   if( startIdx > historyLen - 1 )
   {
      *outBegIdx = 0;
      *outNBElement = 0;
      return TA_INSUFFICIENT_HISTORY;
   }

   endIdx = historyLen - 1;
   dummyBegIdx = 0;
   dummyNBElement = 0;
   subRc = TA_SUCCESS;
   sub0 = NULL;
   sub1 = NULL;
   sub2 = NULL;
   sub3 = NULL;
   if( outStride ) sc_outTenkanSen = outTenkanSen;
   else
   {
      sc_outTenkanSen = (double *)TA_Malloc( sizeof(double) * (size_t)historyLen );
      if( !sc_outTenkanSen ) { return TA_ALLOC_ERR; }
   }
   if( outStride ) sc_outKijunSen = outKijunSen;
   else
   {
      sc_outKijunSen = (double *)TA_Malloc( sizeof(double) * (size_t)historyLen );
      if( !sc_outKijunSen ) { TA_Free( sc_outTenkanSen ); return TA_ALLOC_ERR; }
   }
   if( outStride ) sc_outSenkouSpanA = outSenkouSpanA;
   else
   {
      sc_outSenkouSpanA = (double *)TA_Malloc( sizeof(double) * (size_t)historyLen );
      if( !sc_outSenkouSpanA ) { TA_Free( sc_outTenkanSen ); TA_Free( sc_outKijunSen ); return TA_ALLOC_ERR; }
   }
   if( outStride ) sc_outSenkouSpanB = outSenkouSpanB;
   else
   {
      sc_outSenkouSpanB = (double *)TA_Malloc( sizeof(double) * (size_t)historyLen );
      if( !sc_outSenkouSpanB ) { TA_Free( sc_outTenkanSen ); TA_Free( sc_outKijunSen ); TA_Free( sc_outSenkouSpanA ); return TA_ALLOC_ERR; }
   }

   {
      TA_RetCode retCode;
      int lookbackTotal;
      int n;
      int i;
      int tempBegIdx;
      int tempNbElement;
      double *tempT;
      double *tempK;
      double *tempB;
      /* PROTOTYPE (#490 Q7): each line IS a midpoint over its own window, which is
       * exactly what midprice computes, so the three scans are three midprice calls
       * and Span A is the mean of two of them. MEASURED bit-identical to the fused
       * loop over four parameter triples on the suite's corpus, every line, before
       * this was written.
       *
       * The point is the stream tier: three windows of different periods cannot be
       * one extrema automaton (the census refuses with "expected exactly one
       * window-start variable"), but a composed body is a different tier.
       *
       * The three results go to temporaries and are copied at the end: every read of
       * high and low has to happen before the first write to a caller buffer, or an
       * output aliased onto an input is read after it has been overwritten.
       */
      lookbackTotal = TA_ICHIMOKU_Lookback(optInTenkanPeriod,optInKijunPeriod,optInSenkouBPeriod);
      if( startIdx < lookbackTotal )
      {
         startIdx = lookbackTotal;
      }
      if( startIdx > endIdx )
      {
         dummyBegIdx = 0;
         dummyNBElement = 0;
         *outBegIdx = 0; *outNBElement = 0;
         TA_MIDPRICE_Close( sub0 ); TA_MIDPRICE_Close( sub1 ); TA_MIDPRICE_Close( sub2 ); TA_MEDPRICE_Close( sub3 ); if( !outStride ) TA_Free( sc_outTenkanSen ); if( !outStride ) TA_Free( sc_outKijunSen ); if( !outStride ) TA_Free( sc_outSenkouSpanA ); if( !outStride ) TA_Free( sc_outSenkouSpanB );
         return TA_INSUFFICIENT_HISTORY;
      }
      n = endIdx - startIdx + 1;
      tempT = malloc(n * sizeof(double));
      if( !tempT )
      {
         TA_MIDPRICE_Close( sub0 ); TA_MIDPRICE_Close( sub1 ); TA_MIDPRICE_Close( sub2 ); TA_MEDPRICE_Close( sub3 ); if( !outStride ) TA_Free( sc_outTenkanSen ); if( !outStride ) TA_Free( sc_outKijunSen ); if( !outStride ) TA_Free( sc_outSenkouSpanA ); if( !outStride ) TA_Free( sc_outSenkouSpanB );
         return TA_ALLOC_ERR;
      }
      tempK = malloc(n * sizeof(double));
      if( !tempK )
      {
         free( tempT ); TA_MIDPRICE_Close( sub0 ); TA_MIDPRICE_Close( sub1 ); TA_MIDPRICE_Close( sub2 ); TA_MEDPRICE_Close( sub3 ); if( !outStride ) TA_Free( sc_outTenkanSen ); if( !outStride ) TA_Free( sc_outKijunSen ); if( !outStride ) TA_Free( sc_outSenkouSpanA ); if( !outStride ) TA_Free( sc_outSenkouSpanB );
         return TA_ALLOC_ERR;
      }
      tempB = malloc(n * sizeof(double));
      if( !tempB )
      {
         free( tempT ); free( tempK ); TA_MIDPRICE_Close( sub0 ); TA_MIDPRICE_Close( sub1 ); TA_MIDPRICE_Close( sub2 ); TA_MEDPRICE_Close( sub3 ); if( !outStride ) TA_Free( sc_outTenkanSen ); if( !outStride ) TA_Free( sc_outKijunSen ); if( !outStride ) TA_Free( sc_outSenkouSpanA ); if( !outStride ) TA_Free( sc_outSenkouSpanB );
         return TA_ALLOC_ERR;
      }
      /* Sub-stream 0: midprice over `inHigh, inLow`, warmed from bar 0 up to the
       * sub-call's own startIdx (the seeding point). */
      {
         subRc = TA_MIDPRICE_OpenAndFillInternal( &sub0, inHigh, inLow, (startIdx), (endIdx) + 1, optInTenkanPeriod, &tempBegIdx, &tempNbElement, tempT );
         if( subRc != TA_SUCCESS )
         {
            free(tempT);
            free(tempK);
            free(tempB);
            TA_MIDPRICE_Close( sub0 ); TA_MIDPRICE_Close( sub1 ); TA_MIDPRICE_Close( sub2 ); TA_MEDPRICE_Close( sub3 ); if( !outStride ) TA_Free( sc_outTenkanSen ); if( !outStride ) TA_Free( sc_outKijunSen ); if( !outStride ) TA_Free( sc_outSenkouSpanA ); if( !outStride ) TA_Free( sc_outSenkouSpanB );
            return subRc;
         }
      }
      retCode = subRc;
      if( retCode != TA_SUCCESS )
      {
         free(tempT);
         free(tempK);
         free(tempB);
         dummyBegIdx = 0;
         dummyNBElement = 0;
         TA_MIDPRICE_Close( sub0 ); TA_MIDPRICE_Close( sub1 ); TA_MIDPRICE_Close( sub2 ); TA_MEDPRICE_Close( sub3 ); if( !outStride ) TA_Free( sc_outTenkanSen ); if( !outStride ) TA_Free( sc_outKijunSen ); if( !outStride ) TA_Free( sc_outSenkouSpanA ); if( !outStride ) TA_Free( sc_outSenkouSpanB );
         return retCode;
      }
      /* Sub-stream 1: midprice over `inHigh, inLow`, warmed from bar 0 up to the
       * sub-call's own startIdx (the seeding point). */
      {
         subRc = TA_MIDPRICE_OpenAndFillInternal( &sub1, inHigh, inLow, (startIdx), (endIdx) + 1, optInKijunPeriod, &tempBegIdx, &tempNbElement, tempK );
         if( subRc != TA_SUCCESS )
         {
            free(tempT);
            free(tempK);
            free(tempB);
            TA_MIDPRICE_Close( sub0 ); TA_MIDPRICE_Close( sub1 ); TA_MIDPRICE_Close( sub2 ); TA_MEDPRICE_Close( sub3 ); if( !outStride ) TA_Free( sc_outTenkanSen ); if( !outStride ) TA_Free( sc_outKijunSen ); if( !outStride ) TA_Free( sc_outSenkouSpanA ); if( !outStride ) TA_Free( sc_outSenkouSpanB );
            return subRc;
         }
      }
      retCode = subRc;
      if( retCode != TA_SUCCESS )
      {
         free(tempT);
         free(tempK);
         free(tempB);
         dummyBegIdx = 0;
         dummyNBElement = 0;
         TA_MIDPRICE_Close( sub0 ); TA_MIDPRICE_Close( sub1 ); TA_MIDPRICE_Close( sub2 ); TA_MEDPRICE_Close( sub3 ); if( !outStride ) TA_Free( sc_outTenkanSen ); if( !outStride ) TA_Free( sc_outKijunSen ); if( !outStride ) TA_Free( sc_outSenkouSpanA ); if( !outStride ) TA_Free( sc_outSenkouSpanB );
         return retCode;
      }
      /* Sub-stream 2: midprice over `inHigh, inLow`, warmed from bar 0 up to the
       * sub-call's own startIdx (the seeding point). */
      {
         subRc = TA_MIDPRICE_OpenAndFillInternal( &sub2, inHigh, inLow, (startIdx), (endIdx) + 1, optInSenkouBPeriod, &tempBegIdx, &tempNbElement, tempB );
         if( subRc != TA_SUCCESS )
         {
            free(tempT);
            free(tempK);
            free(tempB);
            TA_MIDPRICE_Close( sub0 ); TA_MIDPRICE_Close( sub1 ); TA_MIDPRICE_Close( sub2 ); TA_MEDPRICE_Close( sub3 ); if( !outStride ) TA_Free( sc_outTenkanSen ); if( !outStride ) TA_Free( sc_outKijunSen ); if( !outStride ) TA_Free( sc_outSenkouSpanA ); if( !outStride ) TA_Free( sc_outSenkouSpanB );
            return subRc;
         }
      }
      retCode = subRc;
      if( retCode != TA_SUCCESS )
      {
         free(tempT);
         free(tempK);
         free(tempB);
         dummyBegIdx = 0;
         dummyNBElement = 0;
         TA_MIDPRICE_Close( sub0 ); TA_MIDPRICE_Close( sub1 ); TA_MIDPRICE_Close( sub2 ); TA_MEDPRICE_Close( sub3 ); if( !outStride ) TA_Free( sc_outTenkanSen ); if( !outStride ) TA_Free( sc_outKijunSen ); if( !outStride ) TA_Free( sc_outSenkouSpanA ); if( !outStride ) TA_Free( sc_outSenkouSpanB );
         return retCode;
      }
      /* Span A is the mean of the two lines, which medprice is over any two series. */
      /* Sub-stream 3: medprice over `tempT, tempK`, warmed from bar 0 up to the
       * sub-call's own startIdx (the seeding point). */
      {
         subRc = TA_MEDPRICE_OpenAndFillInternal( &sub3, tempT, tempK, (0), (n - 1) + 1, &tempBegIdx, &tempNbElement, sc_outSenkouSpanA );
         if( subRc != TA_SUCCESS )
         {
            free(tempT);
            free(tempK);
            free(tempB);
            TA_MIDPRICE_Close( sub0 ); TA_MIDPRICE_Close( sub1 ); TA_MIDPRICE_Close( sub2 ); TA_MEDPRICE_Close( sub3 ); if( !outStride ) TA_Free( sc_outTenkanSen ); if( !outStride ) TA_Free( sc_outKijunSen ); if( !outStride ) TA_Free( sc_outSenkouSpanA ); if( !outStride ) TA_Free( sc_outSenkouSpanB );
            return subRc;
         }
      }
      retCode = subRc;
      if( retCode != TA_SUCCESS )
      {
         free(tempT);
         free(tempK);
         free(tempB);
         dummyBegIdx = 0;
         dummyNBElement = 0;
         TA_MIDPRICE_Close( sub0 ); TA_MIDPRICE_Close( sub1 ); TA_MIDPRICE_Close( sub2 ); TA_MEDPRICE_Close( sub3 ); if( !outStride ) TA_Free( sc_outTenkanSen ); if( !outStride ) TA_Free( sc_outKijunSen ); if( !outStride ) TA_Free( sc_outSenkouSpanA ); if( !outStride ) TA_Free( sc_outSenkouSpanB );
         return retCode;
      }
      for( i = 0; i < n; i += 1 )
      {
         sc_outTenkanSen[i] = tempT[i];
         sc_outKijunSen[i] = tempK[i];
         sc_outSenkouSpanB[i] = tempB[i];
      }
      free(tempT);
      free(tempK);
      free(tempB);
      dummyBegIdx = startIdx;
      dummyNBElement = n;

      /* Capture the live producer state + sub handles. */
      if( dummyNBElement < 1 ) { *outBegIdx = 0; *outNBElement = 0; TA_MIDPRICE_Close( sub0 ); TA_MIDPRICE_Close( sub1 ); TA_MIDPRICE_Close( sub2 ); TA_MEDPRICE_Close( sub3 ); if( !outStride ) TA_Free( sc_outTenkanSen ); if( !outStride ) TA_Free( sc_outKijunSen ); if( !outStride ) TA_Free( sc_outSenkouSpanA ); if( !outStride ) TA_Free( sc_outSenkouSpanB ); return TA_INSUFFICIENT_HISTORY; }
      sp = (struct TA_ICHIMOKU_Stream *)TA_Malloc( sizeof(*sp) );
      if( !sp ) { TA_MIDPRICE_Close( sub0 ); TA_MIDPRICE_Close( sub1 ); TA_MIDPRICE_Close( sub2 ); TA_MEDPRICE_Close( sub3 ); if( !outStride ) TA_Free( sc_outTenkanSen ); if( !outStride ) TA_Free( sc_outKijunSen ); if( !outStride ) TA_Free( sc_outSenkouSpanA ); if( !outStride ) TA_Free( sc_outSenkouSpanB ); return TA_ALLOC_ERR; }
      memset( sp, 0, sizeof(*sp) );
      sp->optInTenkanPeriod = optInTenkanPeriod;
      sp->optInKijunPeriod = optInKijunPeriod;
      sp->optInSenkouBPeriod = optInSenkouBPeriod;
      sp->sub0 = sub0;
      sp->sub1 = sub1;
      sp->sub2 = sub2;
      sp->sub3 = sub3;
      *outBegIdx = dummyBegIdx;
      *outNBElement = dummyNBElement;
      if( !outStride ) outTenkanSen[0] = sc_outTenkanSen[dummyNBElement - 1];
      if( !outStride ) outKijunSen[0] = sc_outKijunSen[dummyNBElement - 1];
      if( !outStride ) outSenkouSpanA[0] = sc_outSenkouSpanA[dummyNBElement - 1];
      if( !outStride ) outSenkouSpanB[0] = sc_outSenkouSpanB[dummyNBElement - 1];
      if( !outStride ) TA_Free( sc_outTenkanSen );
      if( !outStride ) TA_Free( sc_outKijunSen );
      if( !outStride ) TA_Free( sc_outSenkouSpanA );
      if( !outStride ) TA_Free( sc_outSenkouSpanB );
      sp->outRangeBegIdx = *outBegIdx;
      sp->outRangeCount = *outNBElement;
      sp->cur_outTenkanSen = outTenkanSen[(*outNBElement - 1) * outStride];
      sp->cur_outKijunSen = outKijunSen[(*outNBElement - 1) * outStride];
      sp->cur_outSenkouSpanA = outSenkouSpanA[(*outNBElement - 1) * outStride];
      sp->cur_outSenkouSpanB = outSenkouSpanB[(*outNBElement - 1) * outStride];
      *stream = sp;
      return TA_SUCCESS;
   }
}

/* Private function, not in public API. */
TA_RetCode TA_ICHIMOKU_OpenInternal( struct TA_ICHIMOKU_Stream **stream, const double inHigh[], const double inLow[], int startIdx, int historyLen, int optInTenkanPeriod, int optInKijunPeriod, int optInSenkouBPeriod, double *outTenkanSen, double *outKijunSen, double *outSenkouSpanA, double *outSenkouSpanB )
{
   TA_RetCode retCode;
   int dummyBegIdx = 0;
   int dummyNBElement = 0;
   double sink_outTenkanSen = 0.0;
   double sink_outKijunSen = 0.0;
   double sink_outSenkouSpanA = 0.0;
   double sink_outSenkouSpanB = 0.0;
   retCode = TA_ICHIMOKU_OpenImpl( stream, inHigh, inLow, startIdx, historyLen, optInTenkanPeriod, optInKijunPeriod, optInSenkouBPeriod, &dummyBegIdx, &dummyNBElement, &sink_outTenkanSen, &sink_outKijunSen, &sink_outSenkouSpanA, &sink_outSenkouSpanB, 0 );
   if( retCode == TA_SUCCESS )
   {
      *outTenkanSen = sink_outTenkanSen;
      *outKijunSen = sink_outKijunSen;
      *outSenkouSpanA = sink_outSenkouSpanA;
      *outSenkouSpanB = sink_outSenkouSpanB;
   }
   return retCode;
}

TA_LIB_API TA_RetCode TA_ICHIMOKU_Open( TA_ICHIMOKU_Stream **stream, const double inHigh[], const double inLow[], int historyLen, int optInTenkanPeriod, int optInKijunPeriod, int optInSenkouBPeriod, double *outTenkanSen, double *outKijunSen, double *outSenkouSpanA, double *outSenkouSpanB )
{
   if( !stream ) return TA_BAD_PARAM;
   *stream = NULL;
   if( historyLen < 1 ) return TA_OUT_OF_RANGE_START_INDEX;
   if( historyLen > TA_INDEX_MAX + 1 ) return TA_OUT_OF_RANGE_END_INDEX;
   if( !inHigh || !inLow || !outTenkanSen || !outKijunSen || !outSenkouSpanA || !outSenkouSpanB ) return TA_BAD_PARAM;
   return TA_ICHIMOKU_OpenInternal( stream, inHigh, inLow, 0, historyLen, optInTenkanPeriod, optInKijunPeriod, optInSenkouBPeriod, outTenkanSen, outKijunSen, outSenkouSpanA, outSenkouSpanB );
}

TA_LIB_API TA_RetCode TA_ICHIMOKU_OpenAndFill( TA_ICHIMOKU_Stream **stream, const double inHigh[], const double inLow[], int historyLen, int optInTenkanPeriod, int optInKijunPeriod, int optInSenkouBPeriod, int *outBegIdx, int *outNBElement, double outTenkanSen[], double outKijunSen[], double outSenkouSpanA[], double outSenkouSpanB[] )
{
   if( !stream ) return TA_BAD_PARAM;
   *stream = NULL;
   if( historyLen < 1 ) return TA_OUT_OF_RANGE_START_INDEX;
   if( historyLen > TA_INDEX_MAX + 1 ) return TA_OUT_OF_RANGE_END_INDEX;
   if( !inHigh || !inLow || !outBegIdx || !outNBElement || !outTenkanSen || !outKijunSen || !outSenkouSpanA || !outSenkouSpanB ) return TA_BAD_PARAM;
   if( (const void *)outTenkanSen == (const void *)inHigh || (const void *)outTenkanSen == (const void *)inLow || (const void *)outKijunSen == (const void *)inHigh || (const void *)outKijunSen == (const void *)inLow || (const void *)outSenkouSpanA == (const void *)inHigh || (const void *)outSenkouSpanA == (const void *)inLow || (const void *)outSenkouSpanB == (const void *)inHigh || (const void *)outSenkouSpanB == (const void *)inLow || (const void *)outTenkanSen == (const void *)outKijunSen || (const void *)outTenkanSen == (const void *)outSenkouSpanA || (const void *)outTenkanSen == (const void *)outSenkouSpanB || (const void *)outKijunSen == (const void *)outSenkouSpanA || (const void *)outKijunSen == (const void *)outSenkouSpanB || (const void *)outSenkouSpanA == (const void *)outSenkouSpanB ) return TA_BAD_PARAM;
   return TA_ICHIMOKU_OpenAndFillInternal( stream, inHigh, inLow, 0, historyLen, optInTenkanPeriod, optInKijunPeriod, optInSenkouBPeriod, outBegIdx, outNBElement, outTenkanSen, outKijunSen, outSenkouSpanA, outSenkouSpanB );
}

/* Private function, not in public API. */
TA_RetCode TA_ICHIMOKU_OpenAndFillInternal( struct TA_ICHIMOKU_Stream **stream, const double inHigh[], const double inLow[], int startIdx, int historyLen, int optInTenkanPeriod, int optInKijunPeriod, int optInSenkouBPeriod, int *outBegIdx, int *outNBElement, double outTenkanSen[], double outKijunSen[], double outSenkouSpanA[], double outSenkouSpanB[] )
{
   return TA_ICHIMOKU_OpenImpl( stream, inHigh, inLow, startIdx, historyLen, optInTenkanPeriod, optInKijunPeriod, optInSenkouBPeriod, outBegIdx, outNBElement, outTenkanSen, outKijunSen, outSenkouSpanA, outSenkouSpanB, 1 );
}

TA_LIB_API TA_RetCode TA_ICHIMOKU_Update( TA_ICHIMOKU_Stream *stream, double inHigh, double inLow, double *outTenkanSen, double *outKijunSen, double *outSenkouSpanA, double *outSenkouSpanB )
{
   TA_RetCode retCode;

   if( !stream ) return TA_BAD_PARAM;
   if( stream->outRangeBegIdx + stream->outRangeCount > TA_INDEX_MAX )
      return TA_OUT_OF_RANGE_END_INDEX;
   if( !outTenkanSen || !outKijunSen || !outSenkouSpanA || !outSenkouSpanB ) return TA_BAD_PARAM;
   if( !TA_IS_FINITE( inHigh ) || !TA_IS_FINITE( inLow ) ) return TA_BAD_PARAM;
   retCode = TA_ICHIMOKU_StepImpl( stream, inHigh, inLow, outTenkanSen, outKijunSen, outSenkouSpanA, outSenkouSpanB );
   if( retCode != TA_SUCCESS ) return retCode;
   stream->cur_outTenkanSen = *outTenkanSen;
   stream->cur_outKijunSen = *outKijunSen;
   stream->cur_outSenkouSpanA = *outSenkouSpanA;
   stream->cur_outSenkouSpanB = *outSenkouSpanB;
   stream->outRangeCount++;
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_ICHIMOKU_Peek( const TA_ICHIMOKU_Stream *stream, double inHigh, double inLow, double *outTenkanSen, double *outKijunSen, double *outSenkouSpanA, double *outSenkouSpanB )
{
   const struct TA_ICHIMOKU_Stream *sp = stream;
   double cur_tempT = 0.0;
   double cur_tempK = 0.0;
   double cur_tempB = 0.0;
   double cur_outSenkouSpanA = 0.0;
   double cur_outTenkanSen = 0.0;
   double cur_outKijunSen = 0.0;
   double cur_outSenkouSpanB = 0.0;

   if( !stream || !outTenkanSen || !outKijunSen || !outSenkouSpanA || !outSenkouSpanB ) return TA_BAD_PARAM;
   if( !TA_IS_FINITE( inHigh ) || !TA_IS_FINITE( inLow ) ) return TA_BAD_PARAM;

   /* Pipeline the new bar through the sub-streams (batch tail order). */
   {
      TA_RetCode subRc = TA_MIDPRICE_Peek( (const TA_MIDPRICE_Stream *)sp->sub0, inHigh, inLow, &cur_tempT );
      if( subRc != TA_SUCCESS ) return subRc;
   }
   {
      TA_RetCode subRc = TA_MIDPRICE_Peek( (const TA_MIDPRICE_Stream *)sp->sub1, inHigh, inLow, &cur_tempK );
      if( subRc != TA_SUCCESS ) return subRc;
   }
   {
      TA_RetCode subRc = TA_MIDPRICE_Peek( (const TA_MIDPRICE_Stream *)sp->sub2, inHigh, inLow, &cur_tempB );
      if( subRc != TA_SUCCESS ) return subRc;
   }
   {
      TA_RetCode subRc = TA_MEDPRICE_Peek( (const TA_MEDPRICE_Stream *)sp->sub3, cur_tempT, cur_tempK, &cur_outSenkouSpanA );
      if( subRc != TA_SUCCESS ) return subRc;
   }
   /* Combine map (batch tail, per bar). */
   cur_outTenkanSen = cur_tempT;
   cur_outKijunSen = cur_tempK;
   cur_outSenkouSpanB = cur_tempB;
   *outTenkanSen = cur_outTenkanSen;
   *outKijunSen = cur_outKijunSen;
   *outSenkouSpanA = cur_outSenkouSpanA;
   *outSenkouSpanB = cur_outSenkouSpanB;
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_ICHIMOKU_Close( TA_ICHIMOKU_Stream *stream )
{
   if( !stream ) return TA_SUCCESS;
   TA_MIDPRICE_Close( stream->sub0 );
   TA_MIDPRICE_Close( stream->sub1 );
   TA_MIDPRICE_Close( stream->sub2 );
   TA_MEDPRICE_Close( stream->sub3 );
   TA_Free( stream );
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_ICHIMOKU_Value( const TA_ICHIMOKU_Stream *stream, double *outTenkanSen, double *outKijunSen, double *outSenkouSpanA, double *outSenkouSpanB )
{
   if( !stream || !outTenkanSen || !outKijunSen || !outSenkouSpanA || !outSenkouSpanB ) return TA_BAD_PARAM;
   *outTenkanSen = stream->cur_outTenkanSen;
   *outKijunSen = stream->cur_outKijunSen;
   *outSenkouSpanA = stream->cur_outSenkouSpanA;
   *outSenkouSpanB = stream->cur_outSenkouSpanB;
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_ICHIMOKU_OutRange( const TA_ICHIMOKU_Stream *stream, int *outBegIdx, int *outNBElement )
{
   if( !stream || !outBegIdx || !outNBElement ) return TA_BAD_PARAM;
   *outBegIdx = stream->outRangeBegIdx;
   *outNBElement = stream->outRangeCount;
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_ICHIMOKU_Advance( TA_ICHIMOKU_Stream *stream )
{
   if( !stream ) return TA_BAD_PARAM;
   if( stream->outRangeBegIdx + stream->outRangeCount > TA_INDEX_MAX )
      return TA_OUT_OF_RANGE_END_INDEX;
   stream->outRangeCount++;
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_ICHIMOKU_Clone( const TA_ICHIMOKU_Stream *stream, TA_ICHIMOKU_Stream **clone )
{
   struct TA_ICHIMOKU_Stream *sp;

   if( !clone ) return TA_BAD_PARAM;
   *clone = NULL;
   if( !stream ) return TA_BAD_PARAM;
   sp = (struct TA_ICHIMOKU_Stream *)TA_Malloc( sizeof(*sp) );
   if( !sp ) return TA_ALLOC_ERR;
   *sp = *stream;
   sp->sub0 = NULL;
   sp->sub1 = NULL;
   sp->sub2 = NULL;
   sp->sub3 = NULL;
   if( stream->sub0 )
   { TA_RetCode subRc = TA_MIDPRICE_Clone( stream->sub0, &sp->sub0 );
     if( subRc != TA_SUCCESS ) { TA_ICHIMOKU_Close( sp ); return subRc; } }
   if( stream->sub1 )
   { TA_RetCode subRc = TA_MIDPRICE_Clone( stream->sub1, &sp->sub1 );
     if( subRc != TA_SUCCESS ) { TA_ICHIMOKU_Close( sp ); return subRc; } }
   if( stream->sub2 )
   { TA_RetCode subRc = TA_MIDPRICE_Clone( stream->sub2, &sp->sub2 );
     if( subRc != TA_SUCCESS ) { TA_ICHIMOKU_Close( sp ); return subRc; } }
   if( stream->sub3 )
   { TA_RetCode subRc = TA_MEDPRICE_Clone( stream->sub3, &sp->sub3 );
     if( subRc != TA_SUCCESS ) { TA_ICHIMOKU_Close( sp ); return subRc; } }
   *clone = sp;
   return TA_SUCCESS;
}

