/* TA-LIB Copyright (c) 1999-2026, Mario Fortier
* All rights reserved.
*
* Redistribution and use in source and binary forms, with or
* without modification, are permitted provided that the following
* conditions are met:
*
* - Redistributions of source code must retain the above copyright
*   notice, this list of conditions and the following disclaimer.
*
* - Redistributions in binary form must reproduce the above copyright
*   notice, this list of conditions and the following disclaimer in
*   the documentation and/or other materials provided with the
*   distribution.
*
* - Neither name of author nor the names of its contributors
*   may be used to endorse or promote products derived from this
*   software without specific prior written permission.
*
* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
* ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
* LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
* FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
* REGENTS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
* INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
* (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
* OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
* INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
* WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
* OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
* EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

/* AUTO-GENERATED by ta_codegen — DO NOT EDIT.
* Source of truth: ta_codegen/input/<name>/  (regenerate: cd ta_codegen/generator && cargo run -- generate)
*/

#include <string.h>
#include <math.h>
#include "ta_func.h"
#include "ta_utility.h"
#include "ta_memory.h"
#include "ta_func_stream_private.h"

/* List of contributors:
 *
 *  Initial  Name/description
 *  -------------------------------------------------------------------
 *  MF       Mario Fortier
 *  CC       Claude Code (AI assistant)
 *
 * Change history:
 *
 *  MMDDYY BY     Description
 *  -------------------------------------------------------------------
 *  100726 MF,CC  Initial version (#484).
 */

static TA_COLD int kvo_auto_offset( int optInFastPeriod, int optInSlowPeriod, int optInSignalPeriod )
{
   return TA_GLOBALS_UNSTABLE_AUTO(TA_FUNC_UNST_EMA,Ema,(((max(optInFastPeriod,max(optInSlowPeriod,optInSignalPeriod)) > 1) ? ((4 * 10 + 23) / 3 * max(optInFastPeriod,max(optInSlowPeriod,optInSignalPeriod)) + 1) / 2 : 0) - ((max(optInFastPeriod,max(optInSlowPeriod,optInSignalPeriod)) > 1) ? (10 * max(optInFastPeriod,max(optInSlowPeriod,optInSignalPeriod)) + 1) / 2 : 0)),(((max(optInFastPeriod,max(optInSlowPeriod,optInSignalPeriod)) > 1) ? ((4 * 19 + 23) / 3 * max(optInFastPeriod,max(optInSlowPeriod,optInSignalPeriod)) + 1) / 2 : 0) - ((max(optInFastPeriod,max(optInSlowPeriod,optInSignalPeriod)) > 1) ? (19 * max(optInFastPeriod,max(optInSlowPeriod,optInSignalPeriod)) + 1) / 2 : 0)));
}

TA_LIB_API int TA_KVO_Lookback( int optInFastPeriod, int optInSlowPeriod, int optInSignalPeriod )
{
   int longestPeriod;
   if( (int)optInFastPeriod == TA_INTEGER_DEFAULT )
      optInFastPeriod = 34;
   else if( (int)optInFastPeriod < 2 || (int)optInFastPeriod > 100000 )
      return -1;
   if( (int)optInSlowPeriod == TA_INTEGER_DEFAULT )
      optInSlowPeriod = 55;
   else if( (int)optInSlowPeriod < 2 || (int)optInSlowPeriod > 100000 )
      return -1;
   if( (int)optInSignalPeriod == TA_INTEGER_DEFAULT )
      optInSignalPeriod = 13;
   else if( (int)optInSignalPeriod < 2 || (int)optInSignalPeriod > 100000 )
      return -1;
   /* The three smoothings share ONE anchor -- they are all seeded from the
    * volume force of the same bar -- so the warm-up is one EMA lookback of the
    * longest of them, not the sum of three. The extra 1 is the reference bar:
    * the trend needs a previous H+L+C to compare against, and the cumulative
    * range needs a previous bar's range to open with.
    */
   longestPeriod = optInFastPeriod;
   if( optInSlowPeriod > longestPeriod )
   {
      longestPeriod = optInSlowPeriod;
   }
   if( optInSignalPeriod > longestPeriod )
   {
      longestPeriod = optInSignalPeriod;
   }
   return 1 + TA_EMA_Lookback(longestPeriod) + TA_GLOBALS_UNSTABLE_OFFSET(TA_FUNC_UNST_EMA,kvo_auto_offset(optInFastPeriod, optInSlowPeriod, optInSignalPeriod));
}

TA_LIB_API int TA_KVO_DisplayShift( int optInFastPeriod, int optInSlowPeriod, int optInSignalPeriod, int outputIdx )
{
   if( TA_KVO_Lookback( optInFastPeriod, optInSlowPeriod, optInSignalPeriod ) < 0 )
      return INT_MIN;
   if( outputIdx < 0 || outputIdx >= 2 )
      return INT_MIN;
   return 0;
}

TA_FMA_MULTIVERSION
TA_LIB_API TA_RetCode TA_KVO( int    startIdx,
                              int    endIdx,
                              const double inHigh[],
                              const double inLow[],
                              const double inClose[],
                              const double inVolume[],
                              int optInFastPeriod,
                              int optInSlowPeriod,
                              int optInSignalPeriod,
                              int          *outBegIdx,
                              int          *outNBElement,
                              double        outKVO[],
                              double        outKVOSignal[] )
{
   double kFast;
   double kSlow;
   double kSignal;
   double hlc;
   double prevHlc;
   double dmToday;
   double prevDm;
   double cm;
   double vf;
   double factor;
   double emaFast;
   double emaSlow;
   double kvoValue;
   double signalValue;
   int lookbackTotal;
   int trend;
   int prevTrend;
   int today;
   int outIdx;

   if( (startIdx < 0) || (startIdx > TA_INDEX_MAX) )
      return TA_OUT_OF_RANGE_START_INDEX;
   if( (endIdx < 0) || (endIdx > TA_INDEX_MAX) || (endIdx < startIdx) )
      return TA_OUT_OF_RANGE_END_INDEX;

   if( (int)optInFastPeriod == TA_INTEGER_DEFAULT )
      optInFastPeriod = 34;
   else if( (int)optInFastPeriod < 2 || (int)optInFastPeriod > 100000 )
      return TA_BAD_PARAM;
   if( (int)optInSlowPeriod == TA_INTEGER_DEFAULT )
      optInSlowPeriod = 55;
   else if( (int)optInSlowPeriod < 2 || (int)optInSlowPeriod > 100000 )
      return TA_BAD_PARAM;
   if( (int)optInSignalPeriod == TA_INTEGER_DEFAULT )
      optInSignalPeriod = 13;
   else if( (int)optInSignalPeriod < 2 || (int)optInSignalPeriod > 100000 )
      return TA_BAD_PARAM;
   if( !inHigh )
      return TA_BAD_PARAM;
   if( !inLow )
      return TA_BAD_PARAM;
   if( !inClose )
      return TA_BAD_PARAM;
   if( !inVolume )
      return TA_BAD_PARAM;
   if( !outBegIdx || !outNBElement )
      return TA_BAD_PARAM;
   if( !outKVO )
      return TA_BAD_PARAM;
   if( !outKVOSignal )
      return TA_BAD_PARAM;
   if( outKVO == outKVOSignal )
      return TA_BAD_PARAM;

   /* Stephen J. Klinger, "Identifying Trends With Volume Analysis", Technical
    * Analysis of Stocks & Commodities V15:12 (December 1997).
    *
    * Each bar's volume is signed by the trend of H+L+C and weighted by where
    * the bar's own range sits inside the cumulative range of the current trend
    * run. KVO is the difference of two exponential averages of that volume
    * force; the trigger is a third exponential average of KVO.
    *
    *    trend  = +1 if H+L+C rose, -1 if it fell, UNCHANGED if it repeated
    *    cm     = the previous and current ranges on a trend change,
    *             otherwise the running sum plus this bar's range
    *    vf     = volume * |2*(dm/cm) - 1| * 100 * trend
    *
    * The tie rule is the article's own tenet -- "When equality occurs, the
    * existing trend is maintained" -- and it is one line that a corpus with
    * few ties barely exercises. MEASURED on the committed 252-bar corpus:
    * exactly one tie (bar 187), and reading it as +1, or as a reversal, moves
    * KVO by up to 1.0e7 from the next bar on. So it is cheap to get wrong and
    * not cheap to notice.
    *
    * The factor is the 1997 form |2*(dm/cm) - 1| (#484, form A), which is what
    * the December 1997 Traders' Tips all print. It is not LEAN's.
    *
    * The three averages are seeded RAW, from the volume force of the anchor
    * bar, not from a simple average of their first `period` inputs the way
    * ema.c seeds a standalone TA_EMA. That is what every 1997 transcription
    * does, and it is why one lookback covers all three.
    */
   lookbackTotal = TA_KVO_Lookback(optInFastPeriod,optInSlowPeriod,optInSignalPeriod);
   /* Move up the start index if there is not
    * enough initial data.
    */
   if( startIdx < lookbackTotal )
   {
      startIdx = lookbackTotal;
   }
   /* Make sure there is still something to evaluate. */
   if( startIdx > endIdx )
   {
      *outBegIdx= 0;
      *outNBElement= 0;
      return TA_SUCCESS;
   }
   kFast = 2.0 / ((double)optInFastPeriod + 1.0);
   kSlow = 2.0 / ((double)optInSlowPeriod + 1.0);
   kSignal = 2.0 / ((double)optInSignalPeriod + 1.0);
   /* The anchor. Its H+L+C and its range are read, nothing else: the trend
    * starts at +1 there by convention and the first volume force is the bar
    * after it.
    */
   today = startIdx - lookbackTotal;
   prevHlc = inHigh[today] + inLow[today] + inClose[today];
   prevDm = inHigh[today] - inLow[today];
   prevTrend = 1;
   cm = 0.0;
   emaFast = 0.0;
   emaSlow = 0.0;
   signalValue = 0.0;
   kvoValue = 0.0;
   today = today + 1;
   /* The seed bar. Both averages start at this bar's volume force, so KVO is
    * exactly zero here and the trigger seeds on that exact zero.
    */
   hlc = inHigh[today] + inLow[today] + inClose[today];
   dmToday = inHigh[today] - inLow[today];
   if( hlc > prevHlc )
   {
      trend = 1;
   } else if( hlc < prevHlc )
   {
      trend = -1;
   } else 
   {
      trend = prevTrend;
   }
   cm = prevDm + dmToday;
   if( cm == 0.0 )
   {
      vf = 0.0;
   } else 
   {
      factor = 2.0 * (dmToday / cm) - 1.0;
      if( factor < 0.0 )
      {
         factor = -factor;
      }
      vf = inVolume[today] * factor * 100.0 * (double)trend;
   }
   emaFast = vf;
   emaSlow = vf;
   kvoValue = emaFast - emaSlow;
   signalValue = kvoValue;
   prevHlc = hlc;
   prevDm = dmToday;
   prevTrend = trend;
   today = today + 1;
   /* Warm-up. Every bar from here is a pure recursion; only the cumulative
    * range branches, and it branches on the data, not on a counter.
    */
   while( today < startIdx )
   {
      hlc = inHigh[today] + inLow[today] + inClose[today];
      dmToday = inHigh[today] - inLow[today];
      if( hlc > prevHlc )
      {
         trend = 1;
      } else if( hlc < prevHlc )
      {
         trend = -1;
      } else 
      {
         trend = prevTrend;
      }
      if( trend != prevTrend )
      {
         cm = prevDm + dmToday;
      } else 
      {
         cm = cm + dmToday;
      }
      if( cm == 0.0 )
      {
         vf = 0.0;
      } else 
      {
         factor = 2.0 * (dmToday / cm) - 1.0;
         if( factor < 0.0 )
         {
            factor = -factor;
         }
         vf = inVolume[today] * factor * 100.0 * (double)trend;
      }
      emaFast = fma(vf - emaFast, kFast, emaFast);
      emaSlow = fma(vf - emaSlow, kSlow, emaSlow);
      kvoValue = emaFast - emaSlow;
      signalValue = fma(kvoValue - signalValue, kSignal, signalValue);
      prevHlc = hlc;
      prevDm = dmToday;
      prevTrend = trend;
      today = today + 1;
   }
   /* The requested range. */
   outIdx = 0;
   while( today <= endIdx )
   {
      hlc = inHigh[today] + inLow[today] + inClose[today];
      dmToday = inHigh[today] - inLow[today];
      if( hlc > prevHlc )
      {
         trend = 1;
      } else if( hlc < prevHlc )
      {
         trend = -1;
      } else 
      {
         trend = prevTrend;
      }
      if( trend != prevTrend )
      {
         cm = prevDm + dmToday;
      } else 
      {
         cm = cm + dmToday;
      }
      if( cm == 0.0 )
      {
         vf = 0.0;
      } else 
      {
         factor = 2.0 * (dmToday / cm) - 1.0;
         if( factor < 0.0 )
         {
            factor = -factor;
         }
         vf = inVolume[today] * factor * 100.0 * (double)trend;
      }
      emaFast = fma(vf - emaFast, kFast, emaFast);
      emaSlow = fma(vf - emaSlow, kSlow, emaSlow);
      kvoValue = emaFast - emaSlow;
      signalValue = fma(kvoValue - signalValue, kSignal, signalValue);
      outKVO[outIdx] = kvoValue;
      outKVOSignal[outIdx] = signalValue;
      outIdx = outIdx + 1;
      prevHlc = hlc;
      prevDm = dmToday;
      prevTrend = trend;
      today = today + 1;
   }
   *outNBElement= outIdx;
   *outBegIdx= startIdx;
   return TA_SUCCESS;
}

TA_FMA_MULTIVERSION
TA_RetCode TA_S_KVO( int    startIdx,
                     int    endIdx,
                     const float inHigh[],
                     const float inLow[],
                     const float inClose[],
                     const float inVolume[],
                     int optInFastPeriod,
                     int optInSlowPeriod,
                     int optInSignalPeriod,
                     int          *outBegIdx,
                     int          *outNBElement,
                     double        outKVO[],
                     double        outKVOSignal[] )
{
   double kFast;
   double kSlow;
   double kSignal;
   double hlc;
   double prevHlc;
   double dmToday;
   double prevDm;
   double cm;
   double vf;
   double factor;
   double emaFast;
   double emaSlow;
   double kvoValue;
   double signalValue;
   int lookbackTotal;
   int trend;
   int prevTrend;
   int today;
   int outIdx;

   if( (startIdx < 0) || (startIdx > TA_INDEX_MAX) )
      return TA_OUT_OF_RANGE_START_INDEX;
   if( (endIdx < 0) || (endIdx > TA_INDEX_MAX) || (endIdx < startIdx) )
      return TA_OUT_OF_RANGE_END_INDEX;

   if( (int)optInFastPeriod == TA_INTEGER_DEFAULT )
      optInFastPeriod = 34;
   else if( (int)optInFastPeriod < 2 || (int)optInFastPeriod > 100000 )
      return TA_BAD_PARAM;
   if( (int)optInSlowPeriod == TA_INTEGER_DEFAULT )
      optInSlowPeriod = 55;
   else if( (int)optInSlowPeriod < 2 || (int)optInSlowPeriod > 100000 )
      return TA_BAD_PARAM;
   if( (int)optInSignalPeriod == TA_INTEGER_DEFAULT )
      optInSignalPeriod = 13;
   else if( (int)optInSignalPeriod < 2 || (int)optInSignalPeriod > 100000 )
      return TA_BAD_PARAM;
   if( !inHigh )
      return TA_BAD_PARAM;
   if( !inLow )
      return TA_BAD_PARAM;
   if( !inClose )
      return TA_BAD_PARAM;
   if( !inVolume )
      return TA_BAD_PARAM;
   if( !outBegIdx || !outNBElement )
      return TA_BAD_PARAM;
   if( !outKVO )
      return TA_BAD_PARAM;
   if( !outKVOSignal )
      return TA_BAD_PARAM;
   if( outKVO == outKVOSignal )
      return TA_BAD_PARAM;

   lookbackTotal = TA_KVO_Lookback(optInFastPeriod,optInSlowPeriod,optInSignalPeriod);
   if( startIdx < lookbackTotal )
   {
      startIdx = lookbackTotal;
   }
   if( startIdx > endIdx )
   {
      *outBegIdx= 0;
      *outNBElement= 0;
      return TA_SUCCESS;
   }
   kFast = 2.0 / ((double)optInFastPeriod + 1.0);
   kSlow = 2.0 / ((double)optInSlowPeriod + 1.0);
   kSignal = 2.0 / ((double)optInSignalPeriod + 1.0);
   today = startIdx - lookbackTotal;
   prevHlc = (double)inHigh[today] + (double)inLow[today] + (double)inClose[today];
   prevDm = (double)inHigh[today] - (double)inLow[today];
   prevTrend = 1;
   cm = 0.0;
   emaFast = 0.0;
   emaSlow = 0.0;
   signalValue = 0.0;
   kvoValue = 0.0;
   today = today + 1;
   hlc = (double)inHigh[today] + (double)inLow[today] + (double)inClose[today];
   dmToday = (double)inHigh[today] - (double)inLow[today];
   if( hlc > prevHlc )
   {
      trend = 1;
   } else if( hlc < prevHlc )
   {
      trend = -1;
   } else 
   {
      trend = prevTrend;
   }
   cm = prevDm + dmToday;
   if( cm == 0.0 )
   {
      vf = 0.0;
   } else 
   {
      factor = 2.0 * (dmToday / cm) - 1.0;
      if( factor < 0.0 )
      {
         factor = -factor;
      }
      vf = (double)inVolume[today] * factor * 100.0 * (double)trend;
   }
   emaFast = vf;
   emaSlow = vf;
   kvoValue = emaFast - emaSlow;
   signalValue = kvoValue;
   prevHlc = hlc;
   prevDm = dmToday;
   prevTrend = trend;
   today = today + 1;
   while( today < startIdx )
   {
      hlc = (double)inHigh[today] + (double)inLow[today] + (double)inClose[today];
      dmToday = (double)inHigh[today] - (double)inLow[today];
      if( hlc > prevHlc )
      {
         trend = 1;
      } else if( hlc < prevHlc )
      {
         trend = -1;
      } else 
      {
         trend = prevTrend;
      }
      if( trend != prevTrend )
      {
         cm = prevDm + dmToday;
      } else 
      {
         cm = cm + dmToday;
      }
      if( cm == 0.0 )
      {
         vf = 0.0;
      } else 
      {
         factor = 2.0 * (dmToday / cm) - 1.0;
         if( factor < 0.0 )
         {
            factor = -factor;
         }
         vf = (double)inVolume[today] * factor * 100.0 * (double)trend;
      }
      emaFast = fma(vf - emaFast, kFast, emaFast);
      emaSlow = fma(vf - emaSlow, kSlow, emaSlow);
      kvoValue = emaFast - emaSlow;
      signalValue = fma(kvoValue - signalValue, kSignal, signalValue);
      prevHlc = hlc;
      prevDm = dmToday;
      prevTrend = trend;
      today = today + 1;
   }
   outIdx = 0;
   while( today <= endIdx )
   {
      hlc = (double)inHigh[today] + (double)inLow[today] + (double)inClose[today];
      dmToday = (double)inHigh[today] - (double)inLow[today];
      if( hlc > prevHlc )
      {
         trend = 1;
      } else if( hlc < prevHlc )
      {
         trend = -1;
      } else 
      {
         trend = prevTrend;
      }
      if( trend != prevTrend )
      {
         cm = prevDm + dmToday;
      } else 
      {
         cm = cm + dmToday;
      }
      if( cm == 0.0 )
      {
         vf = 0.0;
      } else 
      {
         factor = 2.0 * (dmToday / cm) - 1.0;
         if( factor < 0.0 )
         {
            factor = -factor;
         }
         vf = (double)inVolume[today] * factor * 100.0 * (double)trend;
      }
      emaFast = fma(vf - emaFast, kFast, emaFast);
      emaSlow = fma(vf - emaSlow, kSlow, emaSlow);
      kvoValue = emaFast - emaSlow;
      signalValue = fma(kvoValue - signalValue, kSignal, signalValue);
      outKVO[outIdx] = kvoValue;
      outKVOSignal[outIdx] = signalValue;
      outIdx = outIdx + 1;
      prevHlc = hlc;
      prevDm = dmToday;
      prevTrend = trend;
      today = today + 1;
   }
   *outNBElement= outIdx;
   *outBegIdx= startIdx;
   return TA_SUCCESS;
}

/**** Streaming API *****/

struct TA_KVO_Stream {
   /* The bars this handle has an output for (see TA_KVO_OutRange). */
   int outRangeBegIdx;
   int outRangeCount;
   /* The value(s) at the last bar the stream counted (see TA_KVO_Value). */
   double cur_outKVO;
   double cur_outKVOSignal;
   int optInFastPeriod;
   int optInSlowPeriod;
   int optInSignalPeriod;
   double kFast;
   double kSlow;
   double kSignal;
   double pad_0;
   double prevHlc;
   double prevDm;
   double cm;
   double emaFast;
   double emaSlow;
   double signalValue;
   int prevTrend;
};

/* Private function, not in public API. */
static TA_FMA_STEP_INLINE void TA_KVO_StepImpl( struct TA_KVO_Stream *sp, double inHigh, double inLow, double inClose, double inVolume, double *outKVO, double *outKVOSignal )
{
   double hlc;
   double dmToday;
   double vf;
   double factor;
   double kvoValue;
   int trend;
   double signalValue;

   signalValue = sp->signalValue;
   hlc = inHigh + inLow + inClose;
   dmToday = inHigh - inLow;
   if( hlc > sp->prevHlc )
   {
      trend = 1;
   } else if( hlc < sp->prevHlc )
   {
      trend = -1;
   } else 
   {
      trend = sp->prevTrend;
   }
   if( trend != sp->prevTrend )
   {
      sp->cm = sp->prevDm + dmToday;
   } else 
   {
      sp->cm = sp->cm + dmToday;
   }
   if( sp->cm == 0.0 )
   {
      vf = 0.0;
   } else 
   {
      factor = 2.0 * (dmToday / sp->cm) - 1.0;
      if( factor < 0.0 )
      {
         factor = -factor;
      }
      vf = inVolume * factor * 100.0 * (double)trend;
   }
   sp->emaFast = fma(vf - sp->emaFast, sp->kFast, sp->emaFast);
   sp->emaSlow = fma(vf - sp->emaSlow, sp->kSlow, sp->emaSlow);
   kvoValue = sp->emaFast - sp->emaSlow;
   signalValue = fma(kvoValue - signalValue, sp->kSignal, signalValue);
   *outKVO= kvoValue;
   *outKVOSignal= signalValue;
   sp->prevHlc = hlc;
   sp->prevDm = dmToday;
   sp->prevTrend = trend;
   sp->cur_outKVO = *outKVO;
   sp->cur_outKVOSignal = *outKVOSignal;
   sp->signalValue = signalValue;
}

static TA_FMA_STEP_INLINE TA_RetCode TA_KVO_OpenImpl( struct TA_KVO_Stream **stream, const double inHigh[], const double inLow[], const double inClose[], const double inVolume[], int startIdx, int historyLen, int optInFastPeriod, int optInSlowPeriod, int optInSignalPeriod, int *outBegIdx, int *outNBElement, double outKVO[], double outKVOSignal[], int outStride )
{
   struct TA_KVO_Stream *sp;
   int endIdx;

   if( !stream ) return TA_BAD_PARAM;
   *stream = NULL;
   if( historyLen < 1 ) return TA_OUT_OF_RANGE_START_INDEX;
   if( historyLen > TA_INDEX_MAX + 1 ) return TA_OUT_OF_RANGE_END_INDEX;
   if( !inHigh || !inLow || !inClose || !inVolume || !outKVO || !outKVOSignal ) return TA_BAD_PARAM;
   if( (int)optInFastPeriod == TA_INTEGER_DEFAULT )
      optInFastPeriod = 34;
   else if( (int)optInFastPeriod < 2 || (int)optInFastPeriod > 100000 )
      return TA_BAD_PARAM;
   if( (int)optInSlowPeriod == TA_INTEGER_DEFAULT )
      optInSlowPeriod = 55;
   else if( (int)optInSlowPeriod < 2 || (int)optInSlowPeriod > 100000 )
      return TA_BAD_PARAM;
   if( (int)optInSignalPeriod == TA_INTEGER_DEFAULT )
      optInSignalPeriod = 13;
   else if( (int)optInSignalPeriod < 2 || (int)optInSignalPeriod > 100000 )
      return TA_BAD_PARAM;
   if( startIdx > historyLen - 1 )
   {
      *outBegIdx = 0;
      *outNBElement = 0;
      return TA_INSUFFICIENT_HISTORY;
   }

   endIdx = historyLen - 1;

   {
      double kFast = 0.0;
      double kSlow = 0.0;
      double kSignal = 0.0;
      double hlc;
      double prevHlc = 0.0;
      double dmToday;
      double prevDm = 0.0;
      double cm = 0.0;
      double vf;
      double factor;
      double emaFast = 0.0;
      double emaSlow = 0.0;
      double kvoValue;
      double signalValue = 0.0;
      int lookbackTotal;
      int trend;
      int prevTrend = 0;
      int today;
      int outIdx;
      /* Stephen J. Klinger, "Identifying Trends With Volume Analysis", Technical
       * Analysis of Stocks & Commodities V15:12 (December 1997).
       *
       * Each bar's volume is signed by the trend of H+L+C and weighted by where
       * the bar's own range sits inside the cumulative range of the current trend
       * run. KVO is the difference of two exponential averages of that volume
       * force; the trigger is a third exponential average of KVO.
       *
       *    trend  = +1 if H+L+C rose, -1 if it fell, UNCHANGED if it repeated
       *    cm     = the previous and current ranges on a trend change,
       *             otherwise the running sum plus this bar's range
       *    vf     = volume * |2*(dm/cm) - 1| * 100 * trend
       *
       * The tie rule is the article's own tenet -- "When equality occurs, the
       * existing trend is maintained" -- and it is one line that a corpus with
       * few ties barely exercises. MEASURED on the committed 252-bar corpus:
       * exactly one tie (bar 187), and reading it as +1, or as a reversal, moves
       * KVO by up to 1.0e7 from the next bar on. So it is cheap to get wrong and
       * not cheap to notice.
       *
       * The factor is the 1997 form |2*(dm/cm) - 1| (#484, form A), which is what
       * the December 1997 Traders' Tips all print. It is not LEAN's.
       *
       * The three averages are seeded RAW, from the volume force of the anchor
       * bar, not from a simple average of their first `period` inputs the way
       * ema.c seeds a standalone TA_EMA. That is what every 1997 transcription
       * does, and it is why one lookback covers all three.
       */
      lookbackTotal = TA_KVO_Lookback(optInFastPeriod,optInSlowPeriod,optInSignalPeriod);
      /* Move up the start index if there is not
       * enough initial data.
       */
      if( startIdx < lookbackTotal )
      {
         startIdx = lookbackTotal;
      }
      /* Make sure there is still something to evaluate. */
      if( startIdx > endIdx )
      {
         *outBegIdx= 0;
         *outNBElement= 0;
         return TA_INSUFFICIENT_HISTORY;
      }
      kFast = 2.0 / ((double)optInFastPeriod + 1.0);
      kSlow = 2.0 / ((double)optInSlowPeriod + 1.0);
      kSignal = 2.0 / ((double)optInSignalPeriod + 1.0);
      /* The anchor. Its H+L+C and its range are read, nothing else: the trend
       * starts at +1 there by convention and the first volume force is the bar
       * after it.
       */
      today = startIdx - lookbackTotal;
      prevHlc = inHigh[today] + inLow[today] + inClose[today];
      prevDm = inHigh[today] - inLow[today];
      prevTrend = 1;
      cm = 0.0;
      emaFast = 0.0;
      emaSlow = 0.0;
      signalValue = 0.0;
      kvoValue = 0.0;
      today = today + 1;
      /* The seed bar. Both averages start at this bar's volume force, so KVO is
       * exactly zero here and the trigger seeds on that exact zero.
       */
      hlc = inHigh[today] + inLow[today] + inClose[today];
      dmToday = inHigh[today] - inLow[today];
      if( hlc > prevHlc )
      {
         trend = 1;
      } else if( hlc < prevHlc )
      {
         trend = -1;
      } else 
      {
         trend = prevTrend;
      }
      cm = prevDm + dmToday;
      if( cm == 0.0 )
      {
         vf = 0.0;
      } else 
      {
         factor = 2.0 * (dmToday / cm) - 1.0;
         if( factor < 0.0 )
         {
            factor = -factor;
         }
         vf = inVolume[today] * factor * 100.0 * (double)trend;
      }
      emaFast = vf;
      emaSlow = vf;
      kvoValue = emaFast - emaSlow;
      signalValue = kvoValue;
      prevHlc = hlc;
      prevDm = dmToday;
      prevTrend = trend;
      today = today + 1;
      /* Warm-up. Every bar from here is a pure recursion; only the cumulative
       * range branches, and it branches on the data, not on a counter.
       */
      while( today < startIdx )
      {
         hlc = inHigh[today] + inLow[today] + inClose[today];
         dmToday = inHigh[today] - inLow[today];
         if( hlc > prevHlc )
         {
            trend = 1;
         } else if( hlc < prevHlc )
         {
            trend = -1;
         } else 
         {
            trend = prevTrend;
         }
         if( trend != prevTrend )
         {
            cm = prevDm + dmToday;
         } else 
         {
            cm = cm + dmToday;
         }
         if( cm == 0.0 )
         {
            vf = 0.0;
         } else 
         {
            factor = 2.0 * (dmToday / cm) - 1.0;
            if( factor < 0.0 )
            {
               factor = -factor;
            }
            vf = inVolume[today] * factor * 100.0 * (double)trend;
         }
         emaFast = fma(vf - emaFast, kFast, emaFast);
         emaSlow = fma(vf - emaSlow, kSlow, emaSlow);
         kvoValue = emaFast - emaSlow;
         signalValue = fma(kvoValue - signalValue, kSignal, signalValue);
         prevHlc = hlc;
         prevDm = dmToday;
         prevTrend = trend;
         today = today + 1;
      }
      /* The requested range. */
      outIdx = 0;
      while( today <= endIdx )
      {
         hlc = inHigh[today] + inLow[today] + inClose[today];
         dmToday = inHigh[today] - inLow[today];
         if( hlc > prevHlc )
         {
            trend = 1;
         } else if( hlc < prevHlc )
         {
            trend = -1;
         } else 
         {
            trend = prevTrend;
         }
         if( trend != prevTrend )
         {
            cm = prevDm + dmToday;
         } else 
         {
            cm = cm + dmToday;
         }
         if( cm == 0.0 )
         {
            vf = 0.0;
         } else 
         {
            factor = 2.0 * (dmToday / cm) - 1.0;
            if( factor < 0.0 )
            {
               factor = -factor;
            }
            vf = inVolume[today] * factor * 100.0 * (double)trend;
         }
         emaFast = fma(vf - emaFast, kFast, emaFast);
         emaSlow = fma(vf - emaSlow, kSlow, emaSlow);
         kvoValue = emaFast - emaSlow;
         signalValue = fma(kvoValue - signalValue, kSignal, signalValue);
         outKVO[outIdx * outStride] = kvoValue;
         outKVOSignal[outIdx * outStride] = signalValue;
         outIdx = outIdx + 1;
         prevHlc = hlc;
         prevDm = dmToday;
         prevTrend = trend;
         today = today + 1;
      }
      *outNBElement= outIdx;
      *outBegIdx= startIdx;

      /* Capture the live batch state into the handle. */
      sp = (struct TA_KVO_Stream *)TA_Malloc( sizeof(*sp) );
      if( !sp ) { return TA_ALLOC_ERR; }
      memset( sp, 0, sizeof(*sp) );
      sp->optInFastPeriod = optInFastPeriod;
      sp->optInSlowPeriod = optInSlowPeriod;
      sp->optInSignalPeriod = optInSignalPeriod;
      sp->kFast = kFast;
      sp->kSlow = kSlow;
      sp->kSignal = kSignal;
      sp->prevHlc = prevHlc;
      sp->prevDm = prevDm;
      sp->cm = cm;
      sp->emaFast = emaFast;
      sp->emaSlow = emaSlow;
      sp->signalValue = signalValue;
      sp->prevTrend = prevTrend;
      sp->outRangeBegIdx = *outBegIdx;
      sp->outRangeCount = *outNBElement;
      sp->cur_outKVO = outKVO[(*outNBElement - 1) * outStride];
      sp->cur_outKVOSignal = outKVOSignal[(*outNBElement - 1) * outStride];
      *stream = sp;
      return TA_SUCCESS;
   }
}

TA_FMA_OPEN_CLONE static TA_RetCode TA_KVO_OpenImplFma( struct TA_KVO_Stream **stream, const double inHigh[], const double inLow[], const double inClose[], const double inVolume[], int startIdx, int historyLen, int optInFastPeriod, int optInSlowPeriod, int optInSignalPeriod, int *outBegIdx, int *outNBElement, double outKVO[], double outKVOSignal[], int outStride )
{
   return TA_KVO_OpenImpl( stream, inHigh, inLow, inClose, inVolume, startIdx, historyLen, optInFastPeriod, optInSlowPeriod, optInSignalPeriod, outBegIdx, outNBElement, outKVO, outKVOSignal, outStride );
}

TA_FMA_OPEN_PLAIN static TA_RetCode TA_KVO_OpenImplPlain( struct TA_KVO_Stream **stream, const double inHigh[], const double inLow[], const double inClose[], const double inVolume[], int startIdx, int historyLen, int optInFastPeriod, int optInSlowPeriod, int optInSignalPeriod, int *outBegIdx, int *outNBElement, double outKVO[], double outKVOSignal[], int outStride )
{
   return TA_KVO_OpenImpl( stream, inHigh, inLow, inClose, inVolume, startIdx, historyLen, optInFastPeriod, optInSlowPeriod, optInSignalPeriod, outBegIdx, outNBElement, outKVO, outKVOSignal, outStride );
}

TA_FMA_OPEN_CLONE static TA_RetCode TA_KVO_OpenSinkFma( struct TA_KVO_Stream **stream, const double inHigh[], const double inLow[], const double inClose[], const double inVolume[], int startIdx, int historyLen, int optInFastPeriod, int optInSlowPeriod, int optInSignalPeriod, double *outKVO, double *outKVOSignal )
{
   TA_RetCode retCode;
   int dummyBegIdx = 0;
   int dummyNBElement = 0;
   double sink_outKVO = 0.0;
   double sink_outKVOSignal = 0.0;
   retCode = TA_KVO_OpenImpl( stream, inHigh, inLow, inClose, inVolume, startIdx, historyLen, optInFastPeriod, optInSlowPeriod, optInSignalPeriod, &dummyBegIdx, &dummyNBElement, &sink_outKVO, &sink_outKVOSignal, 0 );
   if( retCode == TA_SUCCESS )
   {
      *outKVO = sink_outKVO;
      *outKVOSignal = sink_outKVOSignal;
   }
   return retCode;
}

/* Private function, not in public API. */
TA_RetCode TA_KVO_OpenInternal( struct TA_KVO_Stream **stream, const double inHigh[], const double inLow[], const double inClose[], const double inVolume[], int startIdx, int historyLen, int optInFastPeriod, int optInSlowPeriod, int optInSignalPeriod, double *outKVO, double *outKVOSignal )
{
   TA_RetCode retCode;
   int dummyBegIdx = 0;
   int dummyNBElement = 0;
   double sink_outKVO = 0.0;
   double sink_outKVOSignal = 0.0;
   retCode = TA_FMA_AVAILABLE ? TA_KVO_OpenImplFma( stream, inHigh, inLow, inClose, inVolume, startIdx, historyLen, optInFastPeriod, optInSlowPeriod, optInSignalPeriod, &dummyBegIdx, &dummyNBElement, &sink_outKVO, &sink_outKVOSignal, 0 ) : TA_KVO_OpenImplPlain( stream, inHigh, inLow, inClose, inVolume, startIdx, historyLen, optInFastPeriod, optInSlowPeriod, optInSignalPeriod, &dummyBegIdx, &dummyNBElement, &sink_outKVO, &sink_outKVOSignal, 0 );
   if( retCode == TA_SUCCESS )
   {
      *outKVO = sink_outKVO;
      *outKVOSignal = sink_outKVOSignal;
   }
   return retCode;
}

TA_LIB_API TA_RetCode TA_KVO_Open( TA_KVO_Stream **stream, const double inHigh[], const double inLow[], const double inClose[], const double inVolume[], int historyLen, int optInFastPeriod, int optInSlowPeriod, int optInSignalPeriod, double *outKVO, double *outKVOSignal )
{
   if( !stream ) return TA_BAD_PARAM;
   *stream = NULL;
   if( historyLen < 1 ) return TA_OUT_OF_RANGE_START_INDEX;
   if( historyLen > TA_INDEX_MAX + 1 ) return TA_OUT_OF_RANGE_END_INDEX;
   if( !inHigh || !inLow || !inClose || !inVolume || !outKVO || !outKVOSignal ) return TA_BAD_PARAM;
   return TA_FMA_AVAILABLE ? TA_KVO_OpenSinkFma( stream, inHigh, inLow, inClose, inVolume, 0, historyLen, optInFastPeriod, optInSlowPeriod, optInSignalPeriod, outKVO, outKVOSignal ) : TA_KVO_OpenInternal( stream, inHigh, inLow, inClose, inVolume, 0, historyLen, optInFastPeriod, optInSlowPeriod, optInSignalPeriod, outKVO, outKVOSignal );
}

TA_LIB_API TA_RetCode TA_KVO_OpenAndFill( TA_KVO_Stream **stream, const double inHigh[], const double inLow[], const double inClose[], const double inVolume[], int historyLen, int optInFastPeriod, int optInSlowPeriod, int optInSignalPeriod, int *outBegIdx, int *outNBElement, double outKVO[], double outKVOSignal[] )
{
   if( !stream ) return TA_BAD_PARAM;
   *stream = NULL;
   if( historyLen < 1 ) return TA_OUT_OF_RANGE_START_INDEX;
   if( historyLen > TA_INDEX_MAX + 1 ) return TA_OUT_OF_RANGE_END_INDEX;
   if( !inHigh || !inLow || !inClose || !inVolume || !outBegIdx || !outNBElement || !outKVO || !outKVOSignal ) return TA_BAD_PARAM;
   if( (const void *)outKVO == (const void *)inHigh || (const void *)outKVO == (const void *)inLow || (const void *)outKVO == (const void *)inClose || (const void *)outKVO == (const void *)inVolume || (const void *)outKVOSignal == (const void *)inHigh || (const void *)outKVOSignal == (const void *)inLow || (const void *)outKVOSignal == (const void *)inClose || (const void *)outKVOSignal == (const void *)inVolume || (const void *)outKVO == (const void *)outKVOSignal ) return TA_BAD_PARAM;
   return TA_KVO_OpenAndFillInternal( stream, inHigh, inLow, inClose, inVolume, 0, historyLen, optInFastPeriod, optInSlowPeriod, optInSignalPeriod, outBegIdx, outNBElement, outKVO, outKVOSignal );
}

/* Private function, not in public API. */
TA_RetCode TA_KVO_OpenAndFillInternal( struct TA_KVO_Stream **stream, const double inHigh[], const double inLow[], const double inClose[], const double inVolume[], int startIdx, int historyLen, int optInFastPeriod, int optInSlowPeriod, int optInSignalPeriod, int *outBegIdx, int *outNBElement, double outKVO[], double outKVOSignal[] )
{
   return TA_FMA_AVAILABLE ? TA_KVO_OpenImplFma( stream, inHigh, inLow, inClose, inVolume, startIdx, historyLen, optInFastPeriod, optInSlowPeriod, optInSignalPeriod, outBegIdx, outNBElement, outKVO, outKVOSignal, 1 ) : TA_KVO_OpenImplPlain( stream, inHigh, inLow, inClose, inVolume, startIdx, historyLen, optInFastPeriod, optInSlowPeriod, optInSignalPeriod, outBegIdx, outNBElement, outKVO, outKVOSignal, 1 );
}

TA_FMA_MULTIVERSION
TA_LIB_API TA_RetCode TA_KVO_Update( TA_KVO_Stream *stream, double inHigh, double inLow, double inClose, double inVolume, double *outKVO, double *outKVOSignal )
{
   if( !stream ) return TA_BAD_PARAM;
   if( stream->outRangeBegIdx + stream->outRangeCount > TA_INDEX_MAX )
      return TA_OUT_OF_RANGE_END_INDEX;
   if( !outKVO || !outKVOSignal ) return TA_BAD_PARAM;
   if( !TA_IS_FINITE( inHigh ) || !TA_IS_FINITE( inLow ) || !TA_IS_FINITE( inClose ) || !TA_IS_FINITE( inVolume ) ) return TA_BAD_PARAM;
   TA_KVO_StepImpl( stream, inHigh, inLow, inClose, inVolume, outKVO, outKVOSignal );
   stream->outRangeCount++;
   return TA_SUCCESS;
}

TA_FMA_MULTIVERSION
TA_LIB_API TA_RetCode TA_KVO_Peek( const TA_KVO_Stream *stream, double inHigh, double inLow, double inClose, double inVolume, double *outKVO, double *outKVOSignal )
{
   const struct TA_KVO_Stream *sp = stream;
   double hlc;
   double dmToday;
   double vf;
   double factor;
   double kvoValue;
   int trend;
   double cm;
   double emaFast;
   double emaSlow;
   double signalValue;

   if( !stream || !outKVO || !outKVOSignal ) return TA_BAD_PARAM;
   if( !TA_IS_FINITE( inHigh ) || !TA_IS_FINITE( inLow ) || !TA_IS_FINITE( inClose ) || !TA_IS_FINITE( inVolume ) ) return TA_BAD_PARAM;
   cm = sp->cm;
   emaFast = sp->emaFast;
   emaSlow = sp->emaSlow;
   signalValue = sp->signalValue;
   hlc = inHigh + inLow + inClose;
   dmToday = inHigh - inLow;
   if( hlc > sp->prevHlc )
   {
      trend = 1;
   } else if( hlc < sp->prevHlc )
   {
      trend = -1;
   } else 
   {
      trend = sp->prevTrend;
   }
   if( trend != sp->prevTrend )
   {
      cm = sp->prevDm + dmToday;
   } else 
   {
      cm = cm + dmToday;
   }
   if( cm == 0.0 )
   {
      vf = 0.0;
   } else 
   {
      factor = 2.0 * (dmToday / cm) - 1.0;
      if( factor < 0.0 )
      {
         factor = -factor;
      }
      vf = inVolume * factor * 100.0 * (double)trend;
   }
   emaFast = fma(vf - emaFast, sp->kFast, emaFast);
   emaSlow = fma(vf - emaSlow, sp->kSlow, emaSlow);
   kvoValue = emaFast - emaSlow;
   signalValue = fma(kvoValue - signalValue, sp->kSignal, signalValue);
   *outKVO= kvoValue;
   *outKVOSignal= signalValue;
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_KVO_Close( TA_KVO_Stream *stream )
{
   if( stream ) TA_Free( stream );
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_KVO_Value( const TA_KVO_Stream *stream, double *outKVO, double *outKVOSignal )
{
   if( !stream || !outKVO || !outKVOSignal ) return TA_BAD_PARAM;
   *outKVO = stream->cur_outKVO;
   *outKVOSignal = stream->cur_outKVOSignal;
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_KVO_OutRange( const TA_KVO_Stream *stream, int *outBegIdx, int *outNBElement )
{
   if( !stream || !outBegIdx || !outNBElement ) return TA_BAD_PARAM;
   *outBegIdx = stream->outRangeBegIdx;
   *outNBElement = stream->outRangeCount;
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_KVO_Advance( TA_KVO_Stream *stream )
{
   if( !stream ) return TA_BAD_PARAM;
   if( stream->outRangeBegIdx + stream->outRangeCount > TA_INDEX_MAX )
      return TA_OUT_OF_RANGE_END_INDEX;
   stream->outRangeCount++;
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_KVO_Clone( const TA_KVO_Stream *stream, TA_KVO_Stream **clone )
{
   struct TA_KVO_Stream *sp;

   if( !clone ) return TA_BAD_PARAM;
   *clone = NULL;
   if( !stream ) return TA_BAD_PARAM;
   sp = (struct TA_KVO_Stream *)TA_Malloc( sizeof(*sp) );
   if( !sp ) return TA_ALLOC_ERR;
   *sp = *stream;
   *clone = sp;
   return TA_SUCCESS;
}

