/* TA-LIB Copyright (c) 1999-2026, Mario Fortier
* All rights reserved.
*
* Redistribution and use in source and binary forms, with or
* without modification, are permitted provided that the following
* conditions are met:
*
* - Redistributions of source code must retain the above copyright
*   notice, this list of conditions and the following disclaimer.
*
* - Redistributions in binary form must reproduce the above copyright
*   notice, this list of conditions and the following disclaimer in
*   the documentation and/or other materials provided with the
*   distribution.
*
* - Neither name of author nor the names of its contributors
*   may be used to endorse or promote products derived from this
*   software without specific prior written permission.
*
* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
* ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
* LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
* FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
* REGENTS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
* INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
* (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
* OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
* INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
* WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
* OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
* EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

/* AUTO-GENERATED by ta_codegen — DO NOT EDIT.
* Source of truth: ta_codegen/input/<name>/  (regenerate: cd ta_codegen/generator && cargo run -- generate)
*/

#include <string.h>
#include <math.h>
#include "ta_func.h"
#include "ta_utility.h"
#include "ta_memory.h"
#include "ta_func_stream_private.h"

/* List of contributors:
 *
 *  Initial  Name/description
 *  -------------------------------------------------------------------
 *  KL       Kevin Lin
 *
 * Change history:
 *
 *  MMDDYY BY   Description
 *  -------------------------------------------------------------------
 *  090426 KL   First version (issue #348). Wilder's smoothing, already
 *              embedded in ATR/RSI/ADX, exposed as a standalone MA.
 */

TA_LIB_API int TA_RMA_Lookback( int optInTimePeriod )
{
   if( (int)optInTimePeriod == TA_INTEGER_DEFAULT )
      optInTimePeriod = 30;
   else if( (int)optInTimePeriod < 1 || (int)optInTimePeriod > 100000 )
      return -1;
   return optInTimePeriod - 1 + TA_GLOBALS_UNSTABLE_PERIOD(TA_FUNC_UNST_RMA,Rma);
}

TA_FMA_MULTIVERSION
TA_LIB_API TA_RetCode TA_RMA( int    startIdx,
                              int    endIdx,
                              const double inReal[],
                              int optInTimePeriod,
                              int          *outBegIdx,
                              int          *outNBElement,
                              double        outReal[] )
{
   double tempReal;
   double prevMA;
   double wAlpha;
   double wBeta;
   int i;
   int today;
   int outIdx;
   int lookbackTotal;

   if( (startIdx < 0) || (startIdx > TA_MAX_INDEX) )
      return TA_OUT_OF_RANGE_START_INDEX;
   if( (endIdx < 0) || (endIdx > TA_MAX_INDEX) || (endIdx < startIdx) )
      return TA_OUT_OF_RANGE_END_INDEX;

   if( (int)optInTimePeriod == TA_INTEGER_DEFAULT )
      optInTimePeriod = 30;
   else if( (int)optInTimePeriod < 1 || (int)optInTimePeriod > 100000 )
      return TA_BAD_PARAM;
   if( !inReal )
      return TA_BAD_PARAM;
   if( !outBegIdx || !outNBElement )
      return TA_BAD_PARAM;
   if( !outReal )
      return TA_BAD_PARAM;

   *outBegIdx= 0;
   *outNBElement= 0;
   /* Identify the minimum number of price bar needed
    * to calculate at least one output.
    */
   lookbackTotal = TA_RMA_Lookback(optInTimePeriod);
   /* Move up the start index if there is not
    * enough initial data.
    */
   if( startIdx < lookbackTotal )
   {
      startIdx = lookbackTotal;
   }
   /* Make sure there is still something to evaluate. */
   if( startIdx > endIdx )
   {
      return TA_SUCCESS;
   }
   /* This IS the smoothing inside TA_ATR, TA_RSI, TA_ADX and TA_PLUS_DM,
    * and TA_RMA(TA_TRANGE(h,l,c), n) is TA_ATR(n) bit for bit -- with the
    * two unstable periods equal, which is a contract the caller has to
    * hold up, since each function owns its own knob.
    *
    * That differential is the strongest gate this function has, and it is
    * the ONLY thing that sees the three choices below. Every one of them
    * therefore has to stay spelled exactly as ta_codegen/input/atr/atr.c
    * spells it:
    *
    *  - wAlpha derived FROM wBeta, never the reverse. Only that order
    *    makes wAlpha + wBeta exactly 1 (Sterbenz -- wBeta lands in
    *    [0.5, 1)); the alpha = 1.0/period spelling misses at 199982 of the
    *    first 200000 periods and mismatches shipped ATR on nearly every
    *    bar. The pair is exactly (1, 0) at period 1 -- hence no period-1
    *    arm below.
    *  - The seed is the first 'period' values summed from 0.0 in input
    *    order, then divided by the period.
    *  - The Wilder step is ONE statement. Splitting it unfuses the
    *    multiply-add and puts a second latency on the recurrence.
    *    The fused operand ORDER matters too -- fma(wBeta, prevMA,
    *    wAlpha * x) and fma(wAlpha, x, wBeta * prevMA) round
    *    differently -- but it is not spelled here: the generator
    *    canonicalizes the sum and elects the accumulator as the fused
    *    multiplicand, so writing the two products the other way round
    *    emits byte-identical C. To watch the differential catch an
    *    order change, patch the generated src/ta_func/ta_RMA.c.
    *
    * In-place (outReal being inReal) is supported: each bar's input is
    * read before that bar's output is written, and the output index never
    * exceeds the bar index of any remaining read.
    */
   wBeta = (double)(optInTimePeriod - 1) / (double)optInTimePeriod;
   wAlpha = 1.0 - wBeta;
   *outBegIdx= startIdx;
   /* Seed with a simple average of the first 'period' values. */
   today = startIdx - lookbackTotal;
   i = optInTimePeriod;
   tempReal = 0.0;
   while( i-- > 0 )
   {
      tempReal += inReal[today++];
   }
   prevMA = tempReal / optInTimePeriod;
   /* Skip the unstable period. */
   while( today <= startIdx )
   {
      prevMA = fma(wBeta, prevMA, wAlpha * inReal[today]);
      today += 1;
   }
   outReal[0] = prevMA;
   outIdx = 1;
   while( today <= endIdx )
   {
      prevMA = fma(wBeta, prevMA, wAlpha * inReal[today]);
      today += 1;
      outReal[outIdx++] = prevMA;
   }
   *outNBElement= outIdx;
   return TA_SUCCESS;
}

TA_FMA_MULTIVERSION
TA_RetCode TA_S_RMA( int    startIdx,
                     int    endIdx,
                     const float inReal[],
                     int optInTimePeriod,
                     int          *outBegIdx,
                     int          *outNBElement,
                     double        outReal[] )
{
   double tempReal;
   double prevMA;
   double wAlpha;
   double wBeta;
   int i;
   int today;
   int outIdx;
   int lookbackTotal;

   if( (startIdx < 0) || (startIdx > TA_MAX_INDEX) )
      return TA_OUT_OF_RANGE_START_INDEX;
   if( (endIdx < 0) || (endIdx > TA_MAX_INDEX) || (endIdx < startIdx) )
      return TA_OUT_OF_RANGE_END_INDEX;

   if( (int)optInTimePeriod == TA_INTEGER_DEFAULT )
      optInTimePeriod = 30;
   else if( (int)optInTimePeriod < 1 || (int)optInTimePeriod > 100000 )
      return TA_BAD_PARAM;
   if( !inReal )
      return TA_BAD_PARAM;
   if( !outBegIdx || !outNBElement )
      return TA_BAD_PARAM;
   if( !outReal )
      return TA_BAD_PARAM;

   *outBegIdx= 0;
   *outNBElement= 0;
   lookbackTotal = TA_RMA_Lookback(optInTimePeriod);
   if( startIdx < lookbackTotal )
   {
      startIdx = lookbackTotal;
   }
   if( startIdx > endIdx )
   {
      return TA_SUCCESS;
   }
   wBeta = (double)(optInTimePeriod - 1) / (double)optInTimePeriod;
   wAlpha = 1.0 - wBeta;
   *outBegIdx= startIdx;
   today = startIdx - lookbackTotal;
   i = optInTimePeriod;
   tempReal = 0.0;
   while( i-- > 0 )
   {
      tempReal += (double)inReal[today++];
   }
   prevMA = tempReal / optInTimePeriod;
   while( today <= startIdx )
   {
      prevMA = fma(wBeta, prevMA, wAlpha * (double)inReal[today]);
      today += 1;
   }
   outReal[0] = prevMA;
   outIdx = 1;
   while( today <= endIdx )
   {
      prevMA = fma(wBeta, prevMA, wAlpha * (double)inReal[today]);
      today += 1;
      outReal[outIdx++] = prevMA;
   }
   *outNBElement= outIdx;
   return TA_SUCCESS;
}

/**** Streaming API *****/

struct TA_RMA_Stream {
   /* The bars this handle has an output for (see TA_StreamOutRange).
    * Kept first, and in this order, in every stream struct. */
   int outRangeBegIdx;
   int outRangeCount;
   /* The value(s) at the last bar the stream counted (see TA_RMA_Value). */
   double cur_outReal;
   int optInTimePeriod;
   double prevMA;
   double wAlpha;
   double wBeta;
};

/* Private function, not in public API. */
static void TA_RMA_StepImpl( struct TA_RMA_Stream *sp, double inReal, double *outReal )
{
   sp->prevMA = fma(sp->wBeta, sp->prevMA, sp->wAlpha * inReal);
   *outReal= sp->prevMA;
   sp->cur_outReal = *outReal;
}

static TA_RetCode TA_RMA_OpenImpl( struct TA_RMA_Stream **stream, const double inReal[], int startIdx, int historyLen, int optInTimePeriod, int *outBegIdx, int *outNBElement, double outReal[], int outStride )
{
   struct TA_RMA_Stream *sp;
   int endIdx;

   if( !stream ) return TA_BAD_PARAM;
   *stream = NULL;
   if( historyLen < 1 ) return TA_OUT_OF_RANGE_START_INDEX;
   if( historyLen > TA_MAX_INDEX + 1 ) return TA_OUT_OF_RANGE_END_INDEX;
   if( !inReal || !outReal ) return TA_BAD_PARAM;
   if( (int)optInTimePeriod == TA_INTEGER_DEFAULT )
      optInTimePeriod = 30;
   else if( (int)optInTimePeriod < 1 || (int)optInTimePeriod > 100000 )
      return TA_BAD_PARAM;
   if( startIdx > historyLen - 1 )
   {
      *outBegIdx = 0;
      *outNBElement = 0;
      return TA_INSUFFICIENT_HISTORY;
   }

   endIdx = historyLen - 1;

   {
      double tempReal;
      double prevMA = 0.0;
      double wAlpha = 0.0;
      double wBeta = 0.0;
      int i;
      int today;
      int outIdx;
      int lookbackTotal;
      *outBegIdx= 0;
      *outNBElement= 0;
      /* Identify the minimum number of price bar needed
       * to calculate at least one output.
       */
      lookbackTotal = TA_RMA_Lookback(optInTimePeriod);
      /* Move up the start index if there is not
       * enough initial data.
       */
      if( startIdx < lookbackTotal )
      {
         startIdx = lookbackTotal;
      }
      /* Make sure there is still something to evaluate. */
      if( startIdx > endIdx )
      {
         return TA_INSUFFICIENT_HISTORY;
      }
      /* This IS the smoothing inside TA_ATR, TA_RSI, TA_ADX and TA_PLUS_DM,
       * and TA_RMA(TA_TRANGE(h,l,c), n) is TA_ATR(n) bit for bit -- with the
       * two unstable periods equal, which is a contract the caller has to
       * hold up, since each function owns its own knob.
       *
       * That differential is the strongest gate this function has, and it is
       * the ONLY thing that sees the three choices below. Every one of them
       * therefore has to stay spelled exactly as ta_codegen/input/atr/atr.c
       * spells it:
       *
       *  - wAlpha derived FROM wBeta, never the reverse. Only that order
       *    makes wAlpha + wBeta exactly 1 (Sterbenz -- wBeta lands in
       *    [0.5, 1)); the alpha = 1.0/period spelling misses at 199982 of the
       *    first 200000 periods and mismatches shipped ATR on nearly every
       *    bar. The pair is exactly (1, 0) at period 1 -- hence no period-1
       *    arm below.
       *  - The seed is the first 'period' values summed from 0.0 in input
       *    order, then divided by the period.
       *  - The Wilder step is ONE statement. Splitting it unfuses the
       *    multiply-add and puts a second latency on the recurrence.
       *    The fused operand ORDER matters too -- fma(wBeta, prevMA,
       *    wAlpha * x) and fma(wAlpha, x, wBeta * prevMA) round
       *    differently -- but it is not spelled here: the generator
       *    canonicalizes the sum and elects the accumulator as the fused
       *    multiplicand, so writing the two products the other way round
       *    emits byte-identical C. To watch the differential catch an
       *    order change, patch the generated src/ta_func/ta_RMA.c.
       *
       * In-place (outReal being inReal) is supported: each bar's input is
       * read before that bar's output is written, and the output index never
       * exceeds the bar index of any remaining read.
       */
      wBeta = (double)(optInTimePeriod - 1) / (double)optInTimePeriod;
      wAlpha = 1.0 - wBeta;
      *outBegIdx= startIdx;
      /* Seed with a simple average of the first 'period' values. */
      today = startIdx - lookbackTotal;
      i = optInTimePeriod;
      tempReal = 0.0;
      while( i-- > 0 )
      {
         tempReal += inReal[today++];
      }
      prevMA = tempReal / optInTimePeriod;
      /* Skip the unstable period. */
      while( today <= startIdx )
      {
         prevMA = fma(wBeta, prevMA, wAlpha * inReal[today]);
         today += 1;
      }
      outReal[0 * outStride] = prevMA;
      outIdx = 1;
      while( today <= endIdx )
      {
         prevMA = fma(wBeta, prevMA, wAlpha * inReal[today]);
         today += 1;
         outReal[outIdx++ * outStride] = prevMA;
      }
      *outNBElement= outIdx;

      /* Capture the live batch state into the handle. */
      sp = (struct TA_RMA_Stream *)TA_Malloc( sizeof(*sp) );
      if( !sp ) { return TA_ALLOC_ERR; }
      memset( sp, 0, sizeof(*sp) );
      sp->optInTimePeriod = optInTimePeriod;
      sp->prevMA = prevMA;
      sp->wAlpha = wAlpha;
      sp->wBeta = wBeta;
      sp->outRangeBegIdx = *outBegIdx;
      sp->outRangeCount = *outNBElement;
      sp->cur_outReal = outReal[(*outNBElement - 1) * outStride];
      *stream = sp;
      return TA_SUCCESS;
   }
}

/* Private function, not in public API. */
TA_RetCode TA_RMA_OpenInternal( struct TA_RMA_Stream **stream, const double inReal[], int startIdx, int historyLen, int optInTimePeriod, double *outReal )
{
   TA_RetCode retCode;
   int dummyBegIdx = 0;
   int dummyNBElement = 0;
   double sink_outReal = 0.0;
   retCode = TA_RMA_OpenImpl( stream, inReal, startIdx, historyLen, optInTimePeriod, &dummyBegIdx, &dummyNBElement, &sink_outReal, 0 );
   if( retCode == TA_SUCCESS )
   {
      *outReal = sink_outReal;
   }
   return retCode;
}

TA_LIB_API TA_RetCode TA_RMA_Open( TA_RMA_Stream **stream, const double inReal[], int historyLen, int optInTimePeriod, double *outReal )
{
   if( !stream ) return TA_BAD_PARAM;
   *stream = NULL;
   if( historyLen < 1 ) return TA_OUT_OF_RANGE_START_INDEX;
   if( historyLen > TA_MAX_INDEX + 1 ) return TA_OUT_OF_RANGE_END_INDEX;
   if( !inReal || !outReal ) return TA_BAD_PARAM;
   return TA_RMA_OpenInternal( stream, inReal, 0, historyLen, optInTimePeriod, outReal );
}

TA_LIB_API TA_RetCode TA_RMA_OpenAndFill( TA_RMA_Stream **stream, const double inReal[], int historyLen, int optInTimePeriod, int *outBegIdx, int *outNBElement, double outReal[] )
{
   if( !stream ) return TA_BAD_PARAM;
   *stream = NULL;
   if( historyLen < 1 ) return TA_OUT_OF_RANGE_START_INDEX;
   if( historyLen > TA_MAX_INDEX + 1 ) return TA_OUT_OF_RANGE_END_INDEX;
   if( !inReal || !outBegIdx || !outNBElement || !outReal ) return TA_BAD_PARAM;
   if( (const void *)outReal == (const void *)inReal ) return TA_BAD_PARAM;
   return TA_RMA_OpenAndFillInternal( stream, inReal, 0, historyLen, optInTimePeriod, outBegIdx, outNBElement, outReal );
}

/* Private function, not in public API. */
TA_RetCode TA_RMA_OpenAndFillInternal( struct TA_RMA_Stream **stream, const double inReal[], int startIdx, int historyLen, int optInTimePeriod, int *outBegIdx, int *outNBElement, double outReal[] )
{
   return TA_RMA_OpenImpl( stream, inReal, startIdx, historyLen, optInTimePeriod, outBegIdx, outNBElement, outReal, 1 );
}

TA_LIB_API TA_RetCode TA_RMA_Update( TA_RMA_Stream *stream, double inReal, double *outReal )
{
   if( !stream || !outReal ) return TA_BAD_PARAM;
   if( !TA_IS_FINITE( inReal ) )
   {
      if( stream->outRangeCount < TA_MAX_INDEX ) stream->outRangeCount++;
      return TA_BAD_PARAM;
   }
   TA_RMA_StepImpl( stream, inReal, outReal );
   if( stream->outRangeCount < TA_MAX_INDEX ) stream->outRangeCount++;
   return TA_SUCCESS;
}

TA_FMA_MULTIVERSION
TA_LIB_API TA_RetCode TA_RMA_Peek( const TA_RMA_Stream *stream, double inReal, double *outReal )
{
   const struct TA_RMA_Stream *sp = stream;
   double prevMA;

   if( !stream || !outReal ) return TA_BAD_PARAM;
   if( !TA_IS_FINITE( inReal ) ) return TA_BAD_PARAM;
   prevMA = sp->prevMA;
   prevMA = fma(sp->wBeta, prevMA, sp->wAlpha * inReal);
   *outReal= prevMA;
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_RMA_UpdateAndFill( TA_RMA_Stream *stream, const double inReal[], int barCount, double outReal[] )
{
   int i;

   if( !stream || !inReal || !outReal ) return TA_BAD_PARAM;
   if( barCount < 0 ) return TA_BAD_PARAM;
   if( (const void *)outReal == (const void *)inReal ) return TA_BAD_PARAM;
   for( i = 0; i < barCount; i++ )
   {
      if( !TA_IS_FINITE( inReal[i] ) )
      {
         if( stream->outRangeCount < TA_MAX_INDEX ) stream->outRangeCount++;
         return TA_BAD_PARAM;
      }
      TA_RMA_StepImpl( stream, inReal[i], &outReal[i] );
      if( stream->outRangeCount < TA_MAX_INDEX ) stream->outRangeCount++;
   }
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_RMA_Close( TA_RMA_Stream *stream )
{
   if( stream ) TA_Free( stream );
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_RMA_Value( const TA_RMA_Stream *stream, double *outReal )
{
   if( !stream || !outReal ) return TA_BAD_PARAM;
   *outReal = stream->cur_outReal;
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_RMA_Clone( const TA_RMA_Stream *stream, TA_RMA_Stream **clone )
{
   struct TA_RMA_Stream *sp;

   if( !clone ) return TA_BAD_PARAM;
   *clone = NULL;
   if( !stream ) return TA_BAD_PARAM;
   sp = (struct TA_RMA_Stream *)TA_Malloc( sizeof(*sp) );
   if( !sp ) return TA_ALLOC_ERR;
   *sp = *stream;
   *clone = sp;
   return TA_SUCCESS;
}

