/* TA-LIB Copyright (c) 1999-2026, Mario Fortier
* All rights reserved.
*
* Redistribution and use in source and binary forms, with or
* without modification, are permitted provided that the following
* conditions are met:
*
* - Redistributions of source code must retain the above copyright
*   notice, this list of conditions and the following disclaimer.
*
* - Redistributions in binary form must reproduce the above copyright
*   notice, this list of conditions and the following disclaimer in
*   the documentation and/or other materials provided with the
*   distribution.
*
* - Neither name of author nor the names of its contributors
*   may be used to endorse or promote products derived from this
*   software without specific prior written permission.
*
* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
* ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
* LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
* FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
* REGENTS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
* INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
* (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
* OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
* INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
* WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
* OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
* EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

/* AUTO-GENERATED by ta_codegen — DO NOT EDIT.
* Source of truth: ta_codegen/input/<name>/  (regenerate: cd ta_codegen/generator && cargo run -- generate)
*/

#include <string.h>
#include <math.h>
#include "ta_func.h"
#include "ta_utility.h"
#include "ta_memory.h"
#include "ta_func_stream_private.h"

/* List of contributors:
 *
 *  Initial  Name/description
 *  -------------------------------------------------------------------
 *  KL       Kevin Lin
 *
 * Change history:
 *
 *  MMDDYY BY     Description
 *  -------------------------------------------------------------------
 *  090426 KL     First version (issue #347).
 */

TA_LIB_API int TA_ZLEMA_Lookback( int optInTimePeriod )
{
   if( (int)optInTimePeriod == TA_INTEGER_DEFAULT )
      optInTimePeriod = 30;
   else if( (int)optInTimePeriod < 1 || (int)optInTimePeriod > 100000 )
      return -1;
   /* The de-lagged series is undefined for its first `lag` bars, and the EMA
    * over it then needs a full window to seed. ZLEMA has no unstable-period id
    * of its own: it converges as its EMA does, so it reads EMA's knob (the
    * DEMA/TEMA/TRIX convention).
    */
   return (optInTimePeriod - 1) / 2 + optInTimePeriod - 1 + TA_GLOBALS_UNSTABLE_PERIOD(TA_FUNC_UNST_EMA,Ema);
}

TA_FMA_MULTIVERSION
TA_LIB_API TA_RetCode TA_ZLEMA( int    startIdx,
                                int    endIdx,
                                const double inReal[],
                                int optInTimePeriod,
                                int          *outBegIdx,
                                int          *outNBElement,
                                double        outReal[] )
{
   double k;
   double tempReal;
   double prevMA;
   int i;
   int lag;
   int today;
   int trailingIdx;
   int outIdx;
   int lookbackTotal;

   if( (startIdx < 0) || (startIdx > TA_MAX_INDEX) )
      return TA_OUT_OF_RANGE_START_INDEX;
   if( (endIdx < 0) || (endIdx > TA_MAX_INDEX) || (endIdx < startIdx) )
      return TA_OUT_OF_RANGE_END_INDEX;

   if( (int)optInTimePeriod == TA_INTEGER_DEFAULT )
      optInTimePeriod = 30;
   else if( (int)optInTimePeriod < 1 || (int)optInTimePeriod > 100000 )
      return TA_BAD_PARAM;
   if( !inReal )
      return TA_BAD_PARAM;
   if( !outBegIdx || !outNBElement )
      return TA_BAD_PARAM;
   if( !outReal )
      return TA_BAD_PARAM;

   /* Identify the minimum number of price bar needed
    * to calculate at least one output.
    */
   lookbackTotal = TA_ZLEMA_Lookback(optInTimePeriod);
   /* Move up the start index if there is not
    * enough initial data.
    */
   if( startIdx < lookbackTotal )
   {
      startIdx = lookbackTotal;
   }
   /* Make sure there is still something to evaluate. */
   if( startIdx > endIdx )
   {
      *outBegIdx= 0;
      *outNBElement= 0;
      return TA_SUCCESS;
   }
   *outBegIdx= startIdx;
   /* No smoothing at period of 1: the output is a copy of the input (same
    * convention as TA_MA for every MAType). The de-lag is already the identity
    * there -- lag is 0 and `2.0*x - x` is exact -- but the recursion is not:
    * at period 1 k is exactly 1.0, so the step reduces to (x-prev)+prev, which
    * returns x only while consecutive values stay within a factor of two of
    * each other. This is TA_EMA's trap, and it takes TA_EMA's explicit copy.
    */
   if( optInTimePeriod == 1 )
   {
      outIdx = 0;
      today = startIdx;
      while( today <= endIdx )
      {
         outReal[outIdx++] = inReal[today++];
      }
      *outNBElement= outIdx;
      return TA_SUCCESS;
   }
   k = 2.0 / (double)(optInTimePeriod + 1);
   lag = (optInTimePeriod - 1) / 2;
   /* The de-lagged value 2*P[t] - P[t-lag] is spelled `2.0*x - trailing`, with
    * one rounding rather than the two of x + (x - trailing), and the EMA step
    * keeps TA_EMA's own ((v-prev)*k)+prev. Both are the bit-exactness contract
    * against the shipped TA_EMA over a materialised de-lagged series, which the
    * regression test asserts by memcmp -- reordering either is a test failure,
    * not a style change.
    */
   today = startIdx - lookbackTotal + lag;
   trailingIdx = today - lag;
   /* The first EMA value is a simple average of the first `period` de-lagged
    * values; it then becomes the seed for the recursion below.
    */
   i = optInTimePeriod;
   tempReal = 0.0;
   while( i-- > 0 )
   {
      tempReal += 2.0 * inReal[today++] - inReal[trailingIdx++];
   }
   prevMA = tempReal / optInTimePeriod;
   while( today <= startIdx )
   {
      prevMA = fma(2.0 * inReal[today++] - inReal[trailingIdx++] - prevMA, k, prevMA);
   }
   outReal[0] = prevMA;
   outIdx = 1;
   while( today <= endIdx )
   {
      prevMA = fma(2.0 * inReal[today++] - inReal[trailingIdx++] - prevMA, k, prevMA);
      outReal[outIdx++] = prevMA;
   }
   *outNBElement= outIdx;
   return TA_SUCCESS;
}

TA_FMA_MULTIVERSION
TA_RetCode TA_S_ZLEMA( int    startIdx,
                       int    endIdx,
                       const float inReal[],
                       int optInTimePeriod,
                       int          *outBegIdx,
                       int          *outNBElement,
                       double        outReal[] )
{
   double k;
   double tempReal;
   double prevMA;
   int i;
   int lag;
   int today;
   int trailingIdx;
   int outIdx;
   int lookbackTotal;

   if( (startIdx < 0) || (startIdx > TA_MAX_INDEX) )
      return TA_OUT_OF_RANGE_START_INDEX;
   if( (endIdx < 0) || (endIdx > TA_MAX_INDEX) || (endIdx < startIdx) )
      return TA_OUT_OF_RANGE_END_INDEX;

   if( (int)optInTimePeriod == TA_INTEGER_DEFAULT )
      optInTimePeriod = 30;
   else if( (int)optInTimePeriod < 1 || (int)optInTimePeriod > 100000 )
      return TA_BAD_PARAM;
   if( !inReal )
      return TA_BAD_PARAM;
   if( !outBegIdx || !outNBElement )
      return TA_BAD_PARAM;
   if( !outReal )
      return TA_BAD_PARAM;

   lookbackTotal = TA_ZLEMA_Lookback(optInTimePeriod);
   if( startIdx < lookbackTotal )
   {
      startIdx = lookbackTotal;
   }
   if( startIdx > endIdx )
   {
      *outBegIdx= 0;
      *outNBElement= 0;
      return TA_SUCCESS;
   }
   *outBegIdx= startIdx;
   if( optInTimePeriod == 1 )
   {
      outIdx = 0;
      today = startIdx;
      while( today <= endIdx )
      {
         outReal[outIdx++] = (double)inReal[today++];
      }
      *outNBElement= outIdx;
      return TA_SUCCESS;
   }
   k = 2.0 / (double)(optInTimePeriod + 1);
   lag = (optInTimePeriod - 1) / 2;
   today = startIdx - lookbackTotal + lag;
   trailingIdx = today - lag;
   i = optInTimePeriod;
   tempReal = 0.0;
   while( i-- > 0 )
   {
      tempReal += 2.0 * (double)inReal[today++] - (double)inReal[trailingIdx++];
   }
   prevMA = tempReal / optInTimePeriod;
   while( today <= startIdx )
   {
      prevMA = fma(2.0 * (double)inReal[today++] - (double)inReal[trailingIdx++] - prevMA, k, prevMA);
   }
   outReal[0] = prevMA;
   outIdx = 1;
   while( today <= endIdx )
   {
      prevMA = fma(2.0 * (double)inReal[today++] - (double)inReal[trailingIdx++] - prevMA, k, prevMA);
      outReal[outIdx++] = prevMA;
   }
   *outNBElement= outIdx;
   return TA_SUCCESS;
}

/**** Streaming API *****/

struct TA_ZLEMA_Stream {
   /* The bars this handle has an output for (see TA_StreamOutRange).
    * Kept first, and in this order, in every stream struct. */
   int outRangeBegIdx;
   int outRangeCount;
   /* The value(s) at the last bar the stream counted (see TA_ZLEMA_Value). */
   double cur_outReal;
   int optInTimePeriod;
   double k;
   double prevMA;
   int ringPos_trailingIdx;
   int ringCap_trailingIdx;
   double *ring_trailingIdx_inReal;
};

/* Private function, not in public API. */
static void TA_ZLEMA_ReleaseImpl( struct TA_ZLEMA_Stream *sp )
{
   if( !sp ) return;
   if( sp->ring_trailingIdx_inReal ) TA_Free( sp->ring_trailingIdx_inReal );
   TA_Free( sp );
}

/* Private function, not in public API. */
static void TA_ZLEMA_StepImpl( struct TA_ZLEMA_Stream *sp, double inReal, double *outReal )
{
   if( sp->optInTimePeriod == 1 )
   {
      *outReal= inReal;
      sp->cur_outReal = *outReal;
      return;
   }
   if( sp->ringCap_trailingIdx == 0 )
   {
      sp->ring_trailingIdx_inReal[0] = inReal;
   }
   sp->prevMA = fma(2.0 * inReal - sp->ring_trailingIdx_inReal[sp->ringPos_trailingIdx] - sp->prevMA, sp->k, sp->prevMA);
   *outReal= sp->prevMA;
   sp->cur_outReal = *outReal;
   sp->ring_trailingIdx_inReal[sp->ringPos_trailingIdx] = inReal;
   sp->ringPos_trailingIdx = sp->ringPos_trailingIdx + 1;
   if( sp->ringPos_trailingIdx >= sp->ringCap_trailingIdx )
   {
      sp->ringPos_trailingIdx = 0;
   }
}

static TA_RetCode TA_ZLEMA_OpenImpl( struct TA_ZLEMA_Stream **stream, const double inReal[], int startIdx, int historyLen, int optInTimePeriod, int *outBegIdx, int *outNBElement, double outReal[], int outStride )
{
   struct TA_ZLEMA_Stream *sp;
   int endIdx;

   if( !stream ) return TA_BAD_PARAM;
   *stream = NULL;
   if( historyLen < 1 ) return TA_OUT_OF_RANGE_START_INDEX;
   if( historyLen > TA_MAX_INDEX + 1 ) return TA_OUT_OF_RANGE_END_INDEX;
   if( !inReal || !outReal ) return TA_BAD_PARAM;
   if( (int)optInTimePeriod == TA_INTEGER_DEFAULT )
      optInTimePeriod = 30;
   else if( (int)optInTimePeriod < 1 || (int)optInTimePeriod > 100000 )
      return TA_BAD_PARAM;
   if( startIdx > historyLen - 1 )
   {
      *outBegIdx = 0;
      *outNBElement = 0;
      return TA_INSUFFICIENT_HISTORY;
   }

   endIdx = historyLen - 1;

   if( optInTimePeriod == 1 )
   {
      int fillLb = TA_ZLEMA_Lookback( optInTimePeriod );
      if( startIdx > fillLb ) fillLb = startIdx;
      if( historyLen < fillLb + 1 ) return TA_INSUFFICIENT_HISTORY;
      sp = (struct TA_ZLEMA_Stream *)TA_Malloc( sizeof(*sp) );
      if( !sp ) { return TA_ALLOC_ERR; }
      memset( sp, 0, sizeof(*sp) );
      sp->optInTimePeriod = optInTimePeriod;
      sp->ringCap_trailingIdx = 0;
      { size_t allocN = (size_t)(sp->ringCap_trailingIdx > 0 ? sp->ringCap_trailingIdx : 1);
        sp->ring_trailingIdx_inReal = (double *)TA_Malloc( sizeof(double) * allocN );
        if( !sp->ring_trailingIdx_inReal ) { TA_ZLEMA_ReleaseImpl( sp ); return TA_ALLOC_ERR; }
        memset( sp->ring_trailingIdx_inReal, 0, sizeof(double) * allocN );
      }
      sp->ringPos_trailingIdx = 0;
      {
         int fillIdx;
         *outBegIdx = fillLb;
         *outNBElement = historyLen - fillLb;
         if( outStride )
         {
            for( fillIdx = 0; fillIdx < historyLen - fillLb; fillIdx++ )
            {
               outReal[fillIdx] = inReal[fillLb + fillIdx];
            }
         }
         else
         {
            outReal[0] = inReal[historyLen - 1];
         }
      }
      sp->outRangeBegIdx = *outBegIdx;
      sp->outRangeCount = *outNBElement;
      sp->cur_outReal = outReal[(*outNBElement - 1) * outStride];
      *stream = sp;
      return TA_SUCCESS;
   }

   {
      double k = 0.0;
      double tempReal;
      double prevMA = 0.0;
      int i;
      int lag;
      int today;
      int trailingIdx;
      int outIdx;
      int lookbackTotal;
      /* Identify the minimum number of price bar needed
       * to calculate at least one output.
       */
      lookbackTotal = TA_ZLEMA_Lookback(optInTimePeriod);
      /* Move up the start index if there is not
       * enough initial data.
       */
      if( startIdx < lookbackTotal )
      {
         startIdx = lookbackTotal;
      }
      /* Make sure there is still something to evaluate. */
      if( startIdx > endIdx )
      {
         *outBegIdx= 0;
         *outNBElement= 0;
         return TA_INSUFFICIENT_HISTORY;
      }
      *outBegIdx= startIdx;
      k = 2.0 / (double)(optInTimePeriod + 1);
      lag = (optInTimePeriod - 1) / 2;
      /* The de-lagged value 2*P[t] - P[t-lag] is spelled `2.0*x - trailing`, with
       * one rounding rather than the two of x + (x - trailing), and the EMA step
       * keeps TA_EMA's own ((v-prev)*k)+prev. Both are the bit-exactness contract
       * against the shipped TA_EMA over a materialised de-lagged series, which the
       * regression test asserts by memcmp -- reordering either is a test failure,
       * not a style change.
       */
      today = startIdx - lookbackTotal + lag;
      trailingIdx = today - lag;
      /* The first EMA value is a simple average of the first `period` de-lagged
       * values; it then becomes the seed for the recursion below.
       */
      i = optInTimePeriod;
      tempReal = 0.0;
      while( i-- > 0 )
      {
         tempReal += 2.0 * inReal[today++] - inReal[trailingIdx++];
      }
      prevMA = tempReal / optInTimePeriod;
      while( today <= startIdx )
      {
         prevMA = fma(2.0 * inReal[today++] - inReal[trailingIdx++] - prevMA, k, prevMA);
      }
      outReal[0 * outStride] = prevMA;
      outIdx = 1;
      while( today <= endIdx )
      {
         prevMA = fma(2.0 * inReal[today++] - inReal[trailingIdx++] - prevMA, k, prevMA);
         outReal[outIdx++ * outStride] = prevMA;
      }
      *outNBElement= outIdx;

      /* Capture the live batch state into the handle. */
      sp = (struct TA_ZLEMA_Stream *)TA_Malloc( sizeof(*sp) );
      if( !sp ) { return TA_ALLOC_ERR; }
      memset( sp, 0, sizeof(*sp) );
      sp->optInTimePeriod = optInTimePeriod;
      sp->k = k;
      sp->prevMA = prevMA;
      sp->ringCap_trailingIdx = (int)(today - trailingIdx);
      if( sp->ringCap_trailingIdx < 0 || sp->ringCap_trailingIdx > historyLen ) { TA_ZLEMA_ReleaseImpl( sp ); return TA_INTERNAL_ERROR(404); }
      { size_t allocN = (size_t)(sp->ringCap_trailingIdx > 0 ? sp->ringCap_trailingIdx : 1);
        sp->ring_trailingIdx_inReal = (double *)TA_Malloc( sizeof(double) * allocN );
        if( !sp->ring_trailingIdx_inReal ) { TA_ZLEMA_ReleaseImpl( sp ); return TA_ALLOC_ERR; }
        memcpy( sp->ring_trailingIdx_inReal, inReal + (historyLen - sp->ringCap_trailingIdx), sizeof(double) * (size_t)sp->ringCap_trailingIdx );
      }
      sp->ringPos_trailingIdx = 0;
      sp->outRangeBegIdx = *outBegIdx;
      sp->outRangeCount = *outNBElement;
      sp->cur_outReal = outReal[(*outNBElement - 1) * outStride];
      *stream = sp;
      return TA_SUCCESS;
   }
}

/* Private function, not in public API. */
TA_RetCode TA_ZLEMA_OpenInternal( struct TA_ZLEMA_Stream **stream, const double inReal[], int startIdx, int historyLen, int optInTimePeriod, double *outReal )
{
   TA_RetCode retCode;
   int dummyBegIdx = 0;
   int dummyNBElement = 0;
   double sink_outReal = 0.0;
   retCode = TA_ZLEMA_OpenImpl( stream, inReal, startIdx, historyLen, optInTimePeriod, &dummyBegIdx, &dummyNBElement, &sink_outReal, 0 );
   if( retCode == TA_SUCCESS )
   {
      *outReal = sink_outReal;
   }
   return retCode;
}

TA_LIB_API TA_RetCode TA_ZLEMA_Open( TA_ZLEMA_Stream **stream, const double inReal[], int historyLen, int optInTimePeriod, double *outReal )
{
   if( !stream ) return TA_BAD_PARAM;
   *stream = NULL;
   if( historyLen < 1 ) return TA_OUT_OF_RANGE_START_INDEX;
   if( historyLen > TA_MAX_INDEX + 1 ) return TA_OUT_OF_RANGE_END_INDEX;
   if( !inReal || !outReal ) return TA_BAD_PARAM;
   return TA_ZLEMA_OpenInternal( stream, inReal, 0, historyLen, optInTimePeriod, outReal );
}

TA_LIB_API TA_RetCode TA_ZLEMA_OpenAndFill( TA_ZLEMA_Stream **stream, const double inReal[], int historyLen, int optInTimePeriod, int *outBegIdx, int *outNBElement, double outReal[] )
{
   if( !stream ) return TA_BAD_PARAM;
   *stream = NULL;
   if( historyLen < 1 ) return TA_OUT_OF_RANGE_START_INDEX;
   if( historyLen > TA_MAX_INDEX + 1 ) return TA_OUT_OF_RANGE_END_INDEX;
   if( !inReal || !outBegIdx || !outNBElement || !outReal ) return TA_BAD_PARAM;
   if( (const void *)outReal == (const void *)inReal ) return TA_BAD_PARAM;
   return TA_ZLEMA_OpenAndFillInternal( stream, inReal, 0, historyLen, optInTimePeriod, outBegIdx, outNBElement, outReal );
}

/* Private function, not in public API. */
TA_RetCode TA_ZLEMA_OpenAndFillInternal( struct TA_ZLEMA_Stream **stream, const double inReal[], int startIdx, int historyLen, int optInTimePeriod, int *outBegIdx, int *outNBElement, double outReal[] )
{
   return TA_ZLEMA_OpenImpl( stream, inReal, startIdx, historyLen, optInTimePeriod, outBegIdx, outNBElement, outReal, 1 );
}

TA_LIB_API TA_RetCode TA_ZLEMA_Update( TA_ZLEMA_Stream *stream, double inReal, double *outReal )
{
   if( !stream || !outReal ) return TA_BAD_PARAM;
   if( !TA_IS_FINITE( inReal ) )
   {
      if( stream->outRangeCount < TA_MAX_INDEX ) stream->outRangeCount++;
      return TA_BAD_PARAM;
   }
   TA_ZLEMA_StepImpl( stream, inReal, outReal );
   if( stream->outRangeCount < TA_MAX_INDEX ) stream->outRangeCount++;
   return TA_SUCCESS;
}

TA_FMA_MULTIVERSION
TA_LIB_API TA_RetCode TA_ZLEMA_Peek( const TA_ZLEMA_Stream *stream, double inReal, double *outReal )
{
   const struct TA_ZLEMA_Stream *sp = stream;
   double prevMA;
   double *ring_trailingIdx_inReal;
   int pkSlot0 = -1;
   double pkVal0 = 0.0;

   if( !stream || !outReal ) return TA_BAD_PARAM;
   if( !TA_IS_FINITE( inReal ) ) return TA_BAD_PARAM;
   prevMA = sp->prevMA;
   ring_trailingIdx_inReal = sp->ring_trailingIdx_inReal;
   if( sp->optInTimePeriod == 1 )
   {
      *outReal= inReal;
      return TA_SUCCESS;
   }
   if( sp->ringCap_trailingIdx == 0 )
   {
      pkSlot0 = 0;
      pkVal0 = inReal;
   }
   prevMA = fma(2.0 * inReal - ((sp->ringPos_trailingIdx != pkSlot0) ? ring_trailingIdx_inReal[sp->ringPos_trailingIdx] : pkVal0) - prevMA, sp->k, prevMA);
   *outReal= prevMA;
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_ZLEMA_UpdateAndFill( TA_ZLEMA_Stream *stream, const double inReal[], int barCount, double outReal[] )
{
   int i;

   if( !stream || !inReal || !outReal ) return TA_BAD_PARAM;
   if( barCount < 0 ) return TA_BAD_PARAM;
   if( (const void *)outReal == (const void *)inReal ) return TA_BAD_PARAM;
   for( i = 0; i < barCount; i++ )
   {
      if( !TA_IS_FINITE( inReal[i] ) )
      {
         if( stream->outRangeCount < TA_MAX_INDEX ) stream->outRangeCount++;
         return TA_BAD_PARAM;
      }
      TA_ZLEMA_StepImpl( stream, inReal[i], &outReal[i] );
      if( stream->outRangeCount < TA_MAX_INDEX ) stream->outRangeCount++;
   }
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_ZLEMA_Close( TA_ZLEMA_Stream *stream )
{
   TA_ZLEMA_ReleaseImpl( stream );
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_ZLEMA_Value( const TA_ZLEMA_Stream *stream, double *outReal )
{
   if( !stream || !outReal ) return TA_BAD_PARAM;
   *outReal = stream->cur_outReal;
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_ZLEMA_Clone( const TA_ZLEMA_Stream *stream, TA_ZLEMA_Stream **clone )
{
   struct TA_ZLEMA_Stream *sp;

   if( !clone ) return TA_BAD_PARAM;
   *clone = NULL;
   if( !stream ) return TA_BAD_PARAM;
   sp = (struct TA_ZLEMA_Stream *)TA_Malloc( sizeof(*sp) );
   if( !sp ) return TA_ALLOC_ERR;
   *sp = *stream;
   sp->ring_trailingIdx_inReal = NULL;
   if( stream->ring_trailingIdx_inReal )
   { size_t copyN = (size_t)(sp->ringCap_trailingIdx > 0 ? sp->ringCap_trailingIdx : 1);
     sp->ring_trailingIdx_inReal = (double *)TA_Malloc( sizeof(double) * copyN );
     if( !sp->ring_trailingIdx_inReal ) { TA_ZLEMA_Close( sp ); return TA_ALLOC_ERR; }
     memcpy( sp->ring_trailingIdx_inReal, stream->ring_trailingIdx_inReal, sizeof(double) * copyN ); }
   *clone = sp;
   return TA_SUCCESS;
}

